### ISSUE TITLE
Allow importing BNS data from .sql backup instead of .tar.gz data

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain-api#1121]
When an event-replay is ran and `--wipe` is passed in, the entire database gets wiped. This means the subdomain import and re-index will occur every time event-replay is ran.
If this could be further configured to leave the BNS import table(s)/indices when wiping the database, this could reduce event-replay time by at least a few hours depending on the size of the node.

For example, a new flag could be added which would be used in conjunction with `--wipe`:

`node ./lib/index.js import-events --file ${STACKS_EXPORT_EVENTS_FILE} --wipe-db --force --preserve-bns`

**Comment by zone117x** [comment]
I'm looking into folding this BNS import process into the `preorg` event-import, leveraging some optimizations now available in https://github.com/hirosystems/stacks-blockchain-api/pull/1166

It may be just as fast / faster than importing a .sql backup or other approaches.

**Comment by rafaelcr** [comment]
Closing this as obsolete now that the BNS v1 import takes only 3 minutes to complete thanks to #1287
