### ISSUE TITLE
Websocket updates for txs of a given STX address

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#156]
> ... subscribe to transactions of a given STX address. A WS companion of `/sidecar/v1/address/<address>/transactions`.

> Asking [in context of the Stacks Wallet](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=442%3A1839), where we will likely want to update transactions in real time.

_Originally posted by @kyranjamie in https://github.com/blockstack/stacks-blockchain-sidecar/pull/145#issuecomment-651692021_

**Comment by kyranjamie** [comment]
In addition, it'd be great if we had another socket/stream for balance updates of a given address.

**Comment by agraebe** [comment]
@zone117x could you please review this and the real-time data requirements conversation to see what next steps should be here? thanks!

**Comment by zone117x** [comment]
Yep, next step is to define the API. AFAIK OpenAPI doesn't support websockets. 
Other than that, the actual implementation is easy.

**Comment by kyranjamie** [comment]
Shame it doesn't tbh, have encountered this before. We can make a websockets folder in `docs/` and have JSON Schema/types.

**Comment by zone117x** [comment]
This seems like the best lib that provides some existing API structure https://github.com/elpheria/rpc-websockets/blob/master/API.md

I think best approach here is to use this lib to implement the following event streams: 
* tx lifecycle updates for a given txid
* transactions updates for a given address
* stx balance updates for a given address

Then for docs we can either use [typedoc](https://github.com/TypeStrong/typedoc) generator on the client code, or manually define the underlying json-rpc schemas.
