### ISSUE TITLE
Create initial perf-test suite

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#165]
Setup the initial set of perf-test scripts as part of release test planning.

This is primarily simulation of blockchain activity (filling up the db) and API endpoint load testing.

**Comment by agraebe** [comment]
cc @timstackblock

**Comment by timstackblock** [comment]
@agraebe @zone117x please add the PR for the scripts. Do we have a list of calls or scenarios we are running?

**Comment by timstackblock** [comment]
https://github.com/blockstackpbc/devops/issues/395
