### ISSUE TITLE
Create an API client/SDK

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#170]
This issue is mostly a research task.

One potential option is to leverage the OpenAPI spec/schema with a tool like https://github.com/OpenAPITools/openapi-generator to auto-generate a typescript API client library.

**Comment by agraebe** [comment]
We could also look into https://www.apimatic.io/continuous-code-generation

**Comment by zone117x** [comment]
`openapi-generator` is able to generate a pretty good client library, except it has a bug with the transaction response types: https://github.com/OpenAPITools/openapi-generator/issues/6513

Unfortunately, I'm not finding any other feasible alternatives that provide automatic client lib generation. @kyranjamie suggested we write one ourselves, but I'm not sure how to do that without quite a bit of repeated code/paths/descriptions etc from the `openapi.yaml` file.

**Comment by agraebe** [comment]
I also looked more into generators but ended up with the same conclusion @zone117x has. To get something usable out of this, I think we could do the following:

- generate the library for TS (done)
- push the library sources into a dedicated folder (or repo?)
- publish an "alpha" version NPM package so it can be used as a dependency
- callout that we're not maintaining the package officially and would love to have community members help improve

If down the road there will be a strong need for this library, we can revisit. But right now the ROI is unclear and this shouldn't be a blocking item for the developer preview release

**Comment by kyranjamie** [comment]
It's not clear to me what the decision is here.

Will try and make use of an auto-generated client and try and extend it where possible, or proceed as we are with @hstove's [`@blockstack/rpc-client`](https://github.com/blockstack/ux/tree/master/packages/rpc-client), potentially extending this as and when we need it?

No need for it to slow up developer preview release, but it is something we need for ourselves (explorer, wallet, connect, cli).

**Comment by agraebe** [comment]
Good point. We will have a manual client covering RPC+Sidecar (not fully) and one generated client, with overlapping capabilities but significant limitations.

This conversation seems to be related to a [recent discussion we had](https://paper.dropbox.com/doc/Discussion-JS-RPC-API-Client--A4vPZ97PNk3zi58TQ4UiijqGAQ-QDfS02NMBfkSxZIHX4vd1). Maybe we can pick up that conversation and see what @yknl might propose as part of the blockstack.js monorepo work? Specifically, the question would be: What sources would the monorepo import with the following:

```js
import * from '@stacks/api'
```

I'd also love to understand how easy/difficult it is to extend the generated library while still being able to regenerate some parts upon API changes. Is there a way to extend the generated code in "isolation" @zone117x ?

**Comment by zone117x** [comment]
> I'd also love to understand how easy/difficult it is to extend the generated library while still being able to regenerate some parts upon API changes. Is there a way to extend the generated code in "isolation" @zone117x ?

Really depends on what kind of extensions we'd want to make. Some easy, others more monkey-patch-y. I tested out a couple that turned out to be relatively easy. 

Adding `BigInt` support to a specific function:
![image](https://user-images.githubusercontent.com/1447546/88900716-17660500-d250-11ea-83ef-9de233e03157.png)


Adding a `x-client-id` param to http requests:
![image](https://user-images.githubusercontent.com/1447546/88902525-a247ff00-d252-11ea-8f6e-6b62b0752e69.png)

**Comment by agraebe** [comment]
@hstove and @aulneau - could you please provide your input?

**Comment by hstove** [comment]
I think an auto-generated client could be a solid investment. It'll provide a few convenience factors that force us to keep types consistent on the server and client. it would act as a backbone for client libs in other languages
