### ISSUE TITLE
Rosetta API for Stacks 2.0

### ISSUE THREAD

**Issue by noumanahmad001** [blockstack/stacks-blockchain-api#187]
### **Rosetta API for Stacks 2.0**
Rosetta is an open-source initiative from Coinbase to standardize blockchain deployment and interaction. Currently, it specifies two API classes — a “Data API” and a “Construction API”. The Data API provides the ability to access blocks, transactions, and balances of any blockchain in a standard format. The Construction API enables developers to write to a blockchain (i.e. construct transactions) in a standard format. 

### **Scope**
Implement the full Rosetta API for Stacks 2.0. We can start with the Data API, and then follow with the Construction API. The implementation should meet expectations outlined in the Rosetta docs.

### **Deliverables**
A self-contained Docker image that one can run Rosetta CLI against to validate correctness.

### **Suggested Implementation Path**
The Stacks Blockchain Sidecar implements a set of API endpoints to support the Stacks 2.0 Explorer. These APIs have very similar functionality to those specified by the Rosetta API, albeit with variations in parameters and coverage. So a possible implementation path would be to add the Rosetta APIs to the sidecar under a dedicated scope (e.g. /v1/rosetta).

### **Unknowns:**
- [ ] Not sure how to get the Network Information for Rosetta API. May have to extend the stacks-blockchain to expose this information?
- [ ] Rosetta allows multiple operations in a single transaction. We didn’t find such behaviour in blockstack transactions. Keeping it simple for now to have a single operation per transaction.

**Comment by zone117x** [comment]
For the [network information API](https://www.rosetta-api.org/docs/NetworkApi.html):
* `/network/list` and `/network/options` endpoints are simple in our case because we don't have sub-networks/shards
* `/network/status` block info can be queried from postgres, but `sync_status` and `peers` would indeed have to be pulled from the stacks-blockchain. I don't think the stacks-blockchain API currently exposes these.

Regarding the `/construction/payloads` endpoint, I'm not sure how exactly blockstack transactions are limited to a single "operation" any more than Ethereum transactions. Could you provide some examples of how this is handled in Ethereum (or Ethereum-like/fork) rosetta implementation?

**Comment by noumanahmad001** [comment]
- Rosetta Api implementation require network details in the request. To do that I have updated the info api `/v2/info` and added the network name `network_name` in response. Here is the [commit](https://github.com/noumanahmad001/stacks-blockchain/commit/e1f146e1a21f315ac7e0b5d2619317fa3dfb910).
- Do we have any peer information in the database or any pointer for getting that information?

**Comment by zone117x** [comment]
@noumanahmad001 
> Do we have any peer information in the database or any pointer for getting that information?

I recommend opening an issue in the https://github.com/blockstack/stacks-blockchain repo with this question. This repo doesn't have any peer info.

**Comment by diwakergupta** [comment]
@noumanahmad001 might I suggest (as I'd previously mentioned on email and Discord) you include a design doc of sorts that outlines the implementation plan before you actually start making a lot of code changes. That way we can align on the implementation and avoid any unnecessary thrash.

For instance, any given stacks-node will be the part of _a_ network and wouldn't know the set of all available networks at a given point in time, so it probably doesn't make sense for that to be a part of `/v2/info`. The simplest thing might be to just maintain a static list as part of the Rosetta implementation for now.

**Comment by zone117x** [comment]
This has been done (not including potential bugs, or out-of-scope features, or new features).
