### ISSUE TITLE
Question: What PoX-related updates should be exposed through the API?

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#190]
The implementation of the consensus protocol is underway ([PoX label in the stacks repo](https://github.com/blockstack/stacks-blockchain/issues?q=is%3Aissue+is%3Aopen+label%3APoX)). We should identify what we should expose through the API.

@zone117x Do you have initial thoughts?

**Comment by psq** [comment]
a few thoughts, in random order, which should also translate into what the explorer shows:
- list of POX anchor blocks (or none is consensus wasn't reached for a given reward period), with consensus information
- list of stacking addresses, and their BTC addresses for each reward period
- STX rewards paid to miners (the coinbase transactions)
- BTC rewards to stackers (aggregate, and per address)

**Comment by psq** [comment]
A few more things:
- delegation (who delegates to whom, how much)
- minimum amount that needs to be stacked per slot for each reward cycle
- total amount stacked per reward cycle
- current amount of STX available (liquid/locked/stacked), or better, over time (daily? monthly enough?)


You also have the implementation of the STX lockups coming with the POX implementation, and there's information you can expose from this as well (maybe as a separate issue?)
