### ISSUE TITLE
Publish WebSocket client as JS with .d.ts

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-blockchain-api#197]
Experienced build issues trying to use client as it tries to compile the TS on install.

Publishing as JS with declarations will prevent these issues and give the installer less to do.

**Comment by agraebe** [comment]
@zone117x - can we get a new release for the package with this fix?

**Comment by zone117x** [comment]
@kyranjamie how is the client being installed on your project? Unless theres' a packaging bug, it should only be compiling TS if the JS isn't available (e.g. install as git dependency).

**Comment by zone117x** [comment]
Here's the postinstall script: https://github.com/blockstack/stacks-blockchain-api/blob/c9c9127d294be5174d201eff7cef55c2e2f73244/client/package.json#L20

**Comment by kyranjamie** [comment]
I tried installing it in the wallet, which is a ts/webpack set up. May well be a yarn related issue.

If I'm not mistaken, only the .ts is published so it'll always try building? 🤔

**Comment by zone117x** [comment]
Seems to be working as intended with both npm and yarn install:
```
$ npm i @stacks/blockchain-api-client

> @stacks/blockchain-api-client@0.6.0 postinstall /Users/matt/Projects/c32check/node_modules/@stacks/blockchain-api-client
> npx shx find lib/index.js || npm run build

npx: installed 19 in 2.317s
lib/index.js
npm notice created a lockfile as package-lock.json. You should commit this file.
+ @stacks/blockchain-api-client@0.6.0
```

Similar results with `yarn add @stacks/blockchain-api-client`. 

What output are you getting during install?

**Comment by kyranjamie** [comment]
Ah, I was trying to install `@blockstack/ws-rpc-client'` as mentioned in your PR. `@stacks/blockchain-api-client` installs just fine and looks like it's bundled there 👍
