### ISSUE TITLE
Stacking: Materialized view for BTC reward details

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#198]
In reference to https://github.com/blockstack/stacks-blockchain/issues/1822

**Comment by zone117x** [comment]
The API exposes BTC rewards in a few endpoints here: https://blockstack.github.io/stacks-blockchain-api/#operation/get_burnchain_rewards_total_by_address (ones starting with `/extended/v1/burnchain/rewards`). Looks like we can close this issue?

**Comment by agraebe** [comment]
yes!
