### ISSUE TITLE
Functional tests for developer release

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#203]
* Ensure usage/instructions in readme work as expected https://github.com/blockstack/stacks-blockchain-api#readme
* Ensure API endpoints work as documented (postman and/or curl) https://blockstack.github.io/stacks-blockchain-api/
* Ensure client lib works as documented at https://blockstack.github.io/stacks-blockchain-api/client/index.html

**Comment by timstackblock** [comment]
thanks guys is this related to https://github.com/blockstack/stacks-blockchain-api/issues/184

**Comment by timstackblock** [comment]
https://github.com/blockstack/stacks-blockchain-api/issues/209

**Comment by timstackblock** [comment]
Post man docs have issues 
https://github.com/blockstack/stacks-blockchain-api/issues/210
