### ISSUE TITLE
[Client] Critical dependency error

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-blockchain-api#208]
**Describe the bug**

Browser bundle emits the following error, when importing and using the client

```
../stacks-blockchain-api/client/node_modules/jsonrpc-lite/jsonrpc.js 16:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

See this PR, which references the same issue: https://github.com/teambition/jsonrpc-lite/pull/17

Supposedly it's fixed in that PR, but hasn't been spoken of in 12 months.

**Comment by zone117x** [comment]
We may need to fork, merge that PR and publish an updated package. Or inline the code we use from it.

**Comment by zensh** [comment]
https://github.com/teambition/jsonrpc-lite/blob/master/jsonrpc.js#L16
the `jsonrpc.js` is generated by tsc with option`module=UMD`, and `require` function do not need by jsonrpc.

could you close the warning message in webpack?

**Comment by kyranjamie** [comment]
@zensh I tried setting the `stats` property to `none` and `errors-only`, but that doesn't remove the error.

Can the issue be fixed in the jsonrpc package by bundling it differently, or perhaps merging the PR with the fix?

**Comment by zensh** [comment]
@kyranjamie change the code https://github.com/teambition/jsonrpc-lite/blob/master/jsonrpc.js#L16 to
```
var v = factory(null, exports);
```
will work?

**Comment by zone117x** [comment]
@zensh The library should be bundled in a more friendly way. UMD format for package.js `main` field is problematic. Typically libraries should use a `cjs` file output for `main`, and use a esm file output for the `module ` field. UMD is useful for CDNs like unpkg which have their own package.json field.

Something like a `package.json:
```json
{
  "main": "dist/lib.cjs.js",
  "module": "dist/lib.esm.js",
  "unpkg": "dist/lib.umd.js",
}
```

**Comment by zensh** [comment]
v2.2.0 released, https://github.com/teambition/jsonrpc-lite/blob/master/package.json#L8
