### ISSUE TITLE
FAUCET errors found while testing API endpoints in postman https://blockstack.github.io/stacks-blockchain-api/

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-blockchain-api#210]
**Describe the bug**
We get FAUCET error messages when we follow the link listed in the postman docs below 

Problem links 
https://stacks-node-api-latest.argon.blockstack.xyz/extended/v1/faucets/btc
https://stacks-node-api-latest.argon.blockstack.xyz/extended/v1/faucets/stx
http://localhost:3999/extended/v1/faucets/stx
http://localhost:3999/extended/v1/faucets/btc

We may need to update the docs here https://blockstack.github.io/stacks-blockchain-api/#operation/run_faucet_stx

<img width="725" alt="Screen Shot 2020-08-27 at 11 29 35 AM" src="https://user-images.githubusercontent.com/49165468/91462844-a585d900-e858-11ea-860e-1e99bb551698.png">
<img width="526" alt="Screen Shot 2020-08-27 at 11 29 25 AM" src="https://user-images.githubusercontent.com/49165468/91462846-a61e6f80-e858-11ea-87ad-2f7e45268903.png">
<img width="435" alt="Screen Shot 2020-08-27 at 11 30 48 AM" src="https://user-images.githubusercontent.com/49165468/91462961-cd753c80-e858-11ea-981a-06b7426e86f1.png">

**Comment by agraebe** [comment]
This is not postman but a wrong URL in the openapi spec I assume. @zone117x - what's the current URL we should put in there for now?

**Comment by zone117x** [comment]
`https://stacks-node-api-latest.argon.blockstack.xyz` is correct. See https://github.com/blockstack/stacks-blockchain-api/issues/181#issuecomment-679305955 for related. 

If faucet isn't working I think we'd need devops to help out, CC @CharlieC3

**Comment by agraebe** [comment]
I was able to confirm that the faucet call works. The issue described by @timstackblock seems to be related to making a `GET` HTTP request. The endpoints only support `POST`. This should POST fine:

```shell
curl --location --request POST 'https://stacks-node-api-latest.argon.blockstack.xyz/extended/v1/faucets/stx?address=STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6'
```
