### ISSUE TITLE
callReadOnlyFunction does not return a value

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#217]
**Describe the bug**
`callReadOnlyFunction` just calls `callReadOnlyFunctionRaw`

**Expected behavior**
`callReadOnlyFunction` should return a value

**Comment by zone117x** [comment]
Related to https://github.com/blockstack/stacks-blockchain-api/issues/218#issuecomment-684913931

Can be fixed here https://github.com/blockstack/stacks-blockchain-api/blob/0f59e5a0948cb9caba2f95cf153355c478a2898b/docs/openapi.yaml#L404

Notice it only has an `example` return value specified, and is missing `schema`.
