### ISSUE TITLE
CallReadOnlyFunctionRequest should have functionArgs as property

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#218]
**Describe the bug**
It is not possible to call a read-only contract function that takes arguments

**Additional context**
#217 

I want to call `get-optional-winner-at` from https://testnet-explorer.blockstack.org/txid/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.flip-coin-jackpot

**Comment by zone117x** [comment]
Thanks @friedger, see https://github.com/blockstack/stacks-blockchain-api/issues/219#issuecomment-684911766

Also, this specific issue can be fixed here: https://github.com/blockstack/stacks-blockchain-api/blob/0f59e5a0948cb9caba2f95cf153355c478a2898b/docs/openapi.yaml#L404
Notice it is lacking any input param specifications.
