### ISSUE TITLE
getContractDataMap should be getContractDataMapEntry

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#219]
**Describe the bug**
`getContractDataMap` only returns one entry from the map, therefore `getContractDataMapEntry` is more appropriate.
Furthermore, the `GetContractDataMapRequest.body` should be `GetContractDataMapRequest.key`

**Comment by zone117x** [comment]
Thanks for pointing these out @friedger. 
This issue, https://github.com/blockstack/stacks-blockchain-api/issues/217, and https://github.com/blockstack/stacks-blockchain-api/issues/218 can all be solved by improving the openAPI spec used to generate the client lib. 
That file is located here: 
https://github.com/blockstack/stacks-blockchain-api/blob/master/docs/openapi.yaml

**Comment by zone117x** [comment]
This issue specifically should be fixed by modifying this endpoint https://github.com/blockstack/stacks-blockchain-api/blob/0f59e5a0948cb9caba2f95cf153355c478a2898b/docs/openapi.yaml#L317
