### ISSUE TITLE
List identifiers of nfts in AccountsApi.getAccountBalance()

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#227]
**Is your feature request related to a problem? Please describe.**
I want to list all nfts owned by an address

**Describe the solution you'd like**
Similar to getAccountAssets() the result should contain the clarity value of the identifier of the nft

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered:

```
{
  "balance": {
    "stx": {
      "balance": "499820",
      "total_sent": "0",
      "total_received": "500000"
    },
    "fungible_tokens": {},
    "non_fungible_tokens": {
      "ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.monsters::nft-monsters": {
        "count": "1",
        "total_sent": "0",
        "total_received": "1",
        "identifiers": [ "0x1223", "0x0112.."]
      }
    }
  }
}
``` 

**Additional context**
https://testnet-explorer.blockstack.org/txid/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.monsters

**Comment by zone117x** [comment]
This would likely need to be an endpoint for a specific address and nft identifier i.e. `/<address>/<nft-id>`.

**Comment by friedger** [comment]
New endpoint should be good as well

**Comment by friedger** [comment]
Looking at the code, there is currently nothing in the code that stores the state of contracts.

The api would live in `accounts.js`:
```
  router.getAsync('/:stx_address/nfts/:contract_id/:asset_name', async (req, res) => {
```

**Comment by friedger** [comment]
The endpoint should be something like:
```
  router.getAsync('/:stx_address/assets/:contract_id/:asset_name', async (req, res) => {
```

What should be the SQL query?

**Comment by friedger** [comment]
Does this makes sense?

```SQL
WITH lastTransfers AS (
        SELECT MAX(block_height) as max_block_height, asset_identifier, value
        FROM nft_events
        GROUP BY asset_identifier, value
        WHERE canonical = true AND (sender = $1 OR recipient = $1)
      )
      SELECT sender, recipient, asset_identifier, value
      FROM lastTransfer FULL JOIN nft_events USING (asset_identifier, value)
      WHERE canonical = true AND (recipient = $1) 
        AND nft_events.block_height = lastTransfers.max_block_height   
```

**Comment by zone117x** [comment]
The query needs to determine if a given NFT is still owned by the address. One way would be to take something like the above query, then query for the latest recipient (current owner) for each of the NFTs, and return the intersection of the two sets.

**Comment by friedger** [comment]
The recipient of the latest nft mint or transfer event is the current owner, isn't it? No need to query for ownership.

**Comment by zone117x** [comment]
Hmm yes I think you are correct. Something like the above query should work

**Comment by asimm241** [comment]
@zone117x I have started working on this issue! , 
I am implementing this as follows: 
Added a new endpoint(` router.getAsync('/:stx_address/nf_id', async (req, res) => {` ) in `/extended/v1address` 
and return results using this query. 
`        WITH lastTransfers AS (
          SELECT MAX(block_height) as max_block_height, asset_identifier, value
          FROM nft_events
          WHERE canonical = true AND (sender = $1 OR recipient = $1)
          GROUP BY asset_identifier, value
        )
        SELECT sender, recipient, asset_identifier, value
        FROM lastTransfers FULL JOIN nft_events USING (asset_identifier, value)
        WHERE canonical = true AND (recipient = $1) 
         AND nft_events.block_height = lastTransfers.max_block_height 
        LIMIT $2 OFFSET $3`
 am I in the right direction?
