### ISSUE TITLE
Exit at block height returns wrong value

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#228]
**Describe the bug**
Calling https://stacks-node-api-latest.argon.blockstack.xyz/v2/info returns a different value than http://testnet-master.blockstack.org:20443/v2/info

**To Reproduce**
1. In a browser open http://testnet-master.blockstack.org:20443/v2/info and https://stacks-node-api-latest.argon.blockstack.xyz/v2/info 
1. Compare `exit_at_block_height`

**Expected behavior**
the values from both api calls should be the same

**Screenshots**
![Screenshot from 2020-09-07 10-05-21](https://user-images.githubusercontent.com/1449049/92363384-b3a5e600-f0f1-11ea-9b6b-dbaf4d05f2fb.png)
![Screenshot from 2020-09-07 10-05-30](https://user-images.githubusercontent.com/1449049/92363386-b43e7c80-f0f1-11ea-8fe2-2a9e35316e1e.png)

**Comment by psq** [comment]
the stacks-node-api is not running off the master node, so the value may be different.  The only one that matters, though, is the one from `testnet-master`.  This parameter is not a global parameter across all nodes.

**Comment by friedger** [comment]
Thank you for the explanation, @psq
