### ISSUE TITLE
docker run.sh starts stacks-node twice.

### ISSUE THREAD

**Issue by fariedt** [blockstack/stacks-blockchain-api#229]
`run.sh` in the `blockstack/stacks-blockchain-api-standalone` docker image starts `stacks-node` twice.

I don't know if this is the right repo for it, but the file does

```
[...]
  if [ $1 = "mocknet" ]; then
    stacks-node start --config=/home/stacky/Stacks-mocknet.toml &> stacks-node.log &
  else
    stacks-node argon &> stacks-node.log &
  fi
  stacks-node argon &> stacks-node.log &
[...]
```
It shouldn't run `stacks-node argon` outside the if/else block.

Found in `blockstack/stacks-blockchain-api-standalone:latest`, as of September 7 2020.

**Comment by zone117x** [comment]
Thanks for finding @fariedt. Just pushed a fix. Please comment if you run into any other issues.
