### ISSUE TITLE
Support subscribe for next block event

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#233]
**Is your feature request related to a problem? Please describe.**
I would like to notify the user about data that is in the current block. To get these info I have to wait for the next block.
E.g. the time for the current block is `(get-block-info? time block-height)` and will return `none`. Only after the next block I would receive the correct time for that previous block.

**Describe the solution you'd like**
Something like:
```
      client = await connectWebSocketClient('ws://stacks-node-api-latest.argon.blockstack.xyz/');
      sub = await client.subscribeBlockUpdates(updates);

``` 

**Describe alternatives you've considered**
Loop on the client

**Additional context**
`flip-coin-jackpot.get-optional-winner-at`

**Comment by agraebe** [comment]
With the roll out of socket.io functionality, this is now possible.
