### ISSUE TITLE
AccountsApi.getAccountBalance should return locked and unlocked balances

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain-api#241]
**Is your feature request related to a problem? Please describe.**
There is currently no way to find account locked balance

**Describe the solution you'd like**
Add a "lockedBalance" property to result.stx Object returned from getAccountBalance

**Describe alternatives you've considered**
Option to pull directly from the api endpoint, when it is available.

**Additional context**

**Comment by zone117x** [comment]
Locked balances from the Stacks 1.0 chain data (AKA vesting amount) are being tracked in this issue: https://github.com/blockstack/stacks-blockchain-api/issues/423

PoX locked balances were added a while ago, docs here: https://blockstack.github.io/stacks-blockchain-api/#operation/get_account_stx_balance
