### ISSUE TITLE
Faucet endpoint differentiations 

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain-api#247]
Now that PoX is about to go live, we should probably revisit our faucet strategy and have 2 different endpoints:

- /faucet/stacker: available once per address, per testnet cycle, transferring enough STX for stacking 
- /faucet/developer: cooldown 5m, transferring 500 STX

**Comment by diwakergupta** [comment]
We'll need to do this soon cc/ @zone117x @agraebe -- right now the faucet is handing out large sums and will fully drain after ~120 requests or so.

I'm wondering if we should just have a single endpoint that accepts requested STX amount as a faucet: most people hit the faucet through the Explorer Sandbox, Wallet, testnet page etc, so we could update those clients to request small amounts. And Stackers would need to curl the endpoit maybe with a special value. Thoughts?

**Comment by agraebe** [comment]
@zone117x - can you take this on right away or should we discuss during the sprint check-in next Tue?

**Comment by zone117x** [comment]
@diwakergupta's suggestion can be easily implemented. It can default to previous amount, and have an optional param that stackers can use.
Should the optional param be something like `?stacking=true` or `?amount=<int>` ?

**Comment by agraebe** [comment]
I would like to understand what downstream changes we'd need to follow up on:

- Do we need to update the testnet faucet view? https://www.blockstack.org/testnet/faucet
- Do we need to update the explorer sandbox faucet view? https://testnet-explorer.blockstack.org/sandbox?tab=faucet

cc @hstove @aulneau

**Comment by zone117x** [comment]
Those faucets shouldn't need changed. The `&stacking=true` change is only needed for Stacking purposes.

**Comment by agraebe** [comment]
Right - I was surfacing a question to see if we would like to enable an option for the faucet UIs to do stacking faucet calls.

**Comment by diwakergupta** [comment]
> Right - I was surfacing a question to see if we would like to enable an option for the faucet UIs to do stacking faucet calls.

My preference would be to have UIs use the default endpoint: by adding the stacking endpoint as an option, we run the risk of over-exposure and draining the faucet too quickly. Asking people interested in stacking to issue a cURL command seems like a reasonable trade-off.

**Comment by iamgenchi** [comment]
Requesting testnet stacks for stacking fails

https://github.com/blockstack/stacks-blockchain-api/issues/527
