### ISSUE TITLE
Add ability to fetch all asset types in the network

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#248]
**Is your feature request related to a problem? Please describe.**
I'm interested in building out a new version of the app I made a long time ago, Coins, but I want it to be able to track all assets that might exist within the Stacks network.

**Describe the solution you'd like**
It'd be nice to be able to query for a list of all, and then be able to query specific assets for their details.

**Comment by asimm241** [comment]
@zone117x I think it is a different request than `feat/tokens metadata`.  `feat/token metadata`  only list the metadata for ft and and nft seperately and also gives you ability for a specific metadata. It does not show all the assets in  a single api.

**Comment by zone117x** [comment]
I confirmed with @aulneau that the new endpoints `/extended/v1/tokens/nft/metadata` and `/extended/v1/tokens/ft/metadata` do resolve this issue, with the caveat that the assets must conform to their corresponding SIPs.
