### ISSUE TITLE
Add Rosetta API to openapi.yaml

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#260]
The Rosetta endpoints need added to the OpenAPI file: https://github.com/blockstack/stacks-blockchain-api/blob/master/docs/openapi.yaml

This should be pretty easy because all of the request and response schemas are already defined.

**Comment by zone117x** [comment]
@fariedt can you take this on as part of the Rosetta work, now that many of the endpoints are ready for documentation?

**Comment by fariedt** [comment]
Sure, I'll get this done.

**Comment by zone117x** [comment]
Closed with https://github.com/blockstack/stacks-blockchain-api/pull/269

The openapi.yaml will be updated with the remaining endpoints in their respective PRs.
