### ISSUE TITLE
Expose STX lock up events

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#268]
The events emitted by the node should be exposed/proxied through the API (irt https://github.com/blockstack/stacks-blockchain/issues/1930). This would include:

* lockup event (already exposed as `STXLockEvent`)
* ~reward events (soon to be exposed)~ EDIT: tracking BTC/reward work in issue https://github.com/blockstack/stacks-blockchain-api/issues/320

This requires changes to the DB, creation of queries, and new endpoints inside this project. @zone117x would we also make these available through websockets?

**Comment by zone117x** [comment]
Update: the reward events will likely be in the core-node next week and then we can start this

**Comment by zone117x** [comment]
Reward events are now merged into core https://github.com/blockstack/stacks-blockchain/pull/2021
