### ISSUE TITLE
Tests for Rosetta `account/` and `mempool/` endpoints

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#273]
These endpoints are currently missing any testing. For reference see:
* https://codecov.io/gh/blockstack/stacks-blockchain-api/src/master/src/api/routes/rosetta/mempool.ts
* https://codecov.io/gh/blockstack/stacks-blockchain-api/src/master/src/api/routes/rosetta/account.ts

@fariedt can we make sure include test coverage for these before the Rosetta work is finished up?

**Comment by asimm241** [comment]
I have test cases ready for rosetta mempool and account-balance endpoints. I'm waiting for the merging of https://github.com/blockstack/stacks-blockchain-api/pull/275 and https://github.com/blockstack/stacks-blockchain-api/pull/276 to avoid conflicts.

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/290
