### ISSUE TITLE
[ws] New events

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#283]
The explorer would really benefit from two additional event streams: a stream of txs and blocks. This would be implemented for the homepage to give some sense of the activity of the network.

**Comment by zone117x** [comment]
@aulneau anything specific you still want added for this? Most of these should be in the new socket.io features

**Comment by agraebe** [comment]
closing this for now. @aulneau please reopen with more specifics if it still isn't resolved by the socket.io features
