### ISSUE TITLE
Publish gh-pages docs from CI

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#297]
The `npm run docs:deploy` script should be ran in CI when PRs are merged into master.

Right now this is ran manually and sometimes breaks.

**Comment by zone117x** [comment]
@CharlieC3 could you help out with this? The gh actions need to be:
```
cd docs
npm i
npm run deploy:docs
```
This should only be ran on merge into master branch. I'm not quite sure how to implement this. It would be super useful if you could help.

**Comment by kyranjamie** [comment]
See @CharlieC3's commit on stacks wallet https://github.com/blockstack/stacks-wallet/commit/ba9906fbc8c60049ad02613b6de5ac8ade2f6505
