### ISSUE TITLE
[TESTNET BUG] Faucet is inadequate for Stacking Testing

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain-api#306]
## Describe the bug

"Official" faucet doesnt provide enough stacks for testing stacking even with "stacking=true" param.  As of the time of this writing, the pox contract has `"min_amount_ustx": 83333333333333` and the faucet with stacking param provides `    "amount": "3000000000000"`

http://krypton.blockstack.org:20443/v2/pox
https://testnet-explorer.blockstack.org/txid/0x1f4036f939e0b4e31a537f67903aaa8314f9bb450ba654cd1c368e35a89de4dc

## Steps To Reproduce

1. request stacks with param stacking=true, for example:
`https://stacks-node-api.blockstack.org/extended/v1/faucets/stx?address=ST9SW39M98MZXBGWSDVN228NW1NWENWCF321GWMK&stacking=true`

## Expected behavior

Devs shouldn't have to get themselves blocked by requesting stacks multiple times in order to test functionality.

## Additional context

----

**Comment by diwakergupta** [comment]
Faucet should use the info in `/v2/pox` to compute the threshold vs. a hard-coded amount.

**Comment by zone117x** [comment]
@dantrevino This should be fixed in latest deployment. Could you give it a try and let me know?

**Comment by dantrevino** [comment]
Looks good!

**Comment by agraebe** [comment]
I just ran the stacking faucet and got [`83337888541666`](https://testnet-explorer.blockstack.org/txid/0x7e3c4f2027f11999e3ce82d5db6a587977cec9a98874a80b1b4b053e15b29828). However, pinging `v2/pox` returns `"min_amount_ustx": 83337892708333`.

I seem to miss `4166667` additional microSTX to run stacking - any idea what might be going on?

**Comment by diwakergupta** [comment]
> I just ran the stacking faucet and got [`83337888541666`](https://testnet-explorer.blockstack.org/txid/0x7e3c4f2027f11999e3ce82d5db6a587977cec9a98874a80b1b4b053e15b29828). However, pinging `v2/pox` returns `"min_amount_ustx": 83337892708333`.
> 
> I seem to miss `4166667` additional microSTX to run stacking - any idea what might be going on?
> 
> @zone117x

Keep in mind that the threshold _is_ a function of how many liquid STX are participating in Stacking, so it is completely expected that `v2/pox` and faucet's notion of the threshold don't match, depending on how far apart you pinged them.

@agraebe I'd suggest just using the regular faucet call to get some additional STX to bump yourself over the threshold.

**Comment by zone117x** [comment]
We can modify the faucet to send something like `min_amount_ustx + (min_amount_ustx * 0.1)`?

**Comment by agraebe** [comment]
that'd be helpful. In my experience testing it so far, I only had a couple of minutes before another faucet run was required
