### ISSUE TITLE
Include tx data within block response

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#307]
Currently when fetching a single block, the txs included are only the tx_id. It would be ideal if on the API side we could expose the actual tx data that you'd get by fetching via the tx route. I think doing concurrent fetches in user-land would not be ideal for this, whereas doing it on the api side seems to make more sense.

I think an ideal solution would be something like this:

`/tx/block/[block_hash]` and `/tx/principal/[principal]`

Which would expose the same kind of limit/offset api that the main tx endpoint has. This would give us an identical API and allow for us to fetch pending tx's assoicated with an address.

 eg the response would be this:

```tsx
export interface TransactionResults {
  limit: number;
  offset: number;
  total: number;
  results: Transaction[] | MempoolTransaction[];
}
```

**Comment by zone117x** [comment]
The block endpoint would never return mempool transactions (by definition blocks only contained mined txs). 

It's also not clear to me how we'd sort (for offset/limit) combined mempool-tx and mined-tx array in the `/tx/principal/[principal]` endpoint results. The couple ways we could do it lead to unwelcome surprising behavior. 

I think we'd want to have a have a separate endpoint like `/address/[address]/mempool` for these.

**Comment by noumanahmads** [comment]
I am working on this one. 
I think here we should have implementation for a couple of endpoints

- /tx/block/[block_hash]
response: 
```
export interface TransactionResults {
  limit: number;
  offset: number;
  total: number;
  results: Transaction[];
}
```
- /address/[address]/mempool
response: 
```
export interface TransactionResults {
  limit: number;
  offset: number;
  total: number;
  results: MempoolTransaction[];
}
```
@zone117x

**Comment by zone117x** [comment]
@noumanahmads That looks good to me!

**Comment by agraebe** [comment]
with the PR merged, can this be closed @noumanahmads ?

**Comment by noumanahmads** [comment]
> with the PR merged, can this be closed @noumanahmads ?

@agraebe 
Yes this can be closed
