### ISSUE TITLE
Balance reported by API does not match balance reported by miner/follower

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain-api#314]
**Describe the bug**
API is reporting different STX balances than the miner or even the sidecar follower.

**To Reproduce**
Compare
- https://stacks-node-api.krypton.blockstack.org/extended/v1/address/ST4ZD7PZ8VVF4G5T2F7QH84TS7CTRHX52ECJ2A2Q/stx
- http://krypton.blockstack.org:20443/v2/accounts/ST4ZD7PZ8VVF4G5T2F7QH84TS7CTRHX52ECJ2A2Q?proof=0
- https://stacks-node-api.krypton.blockstack.org/v2/accounts/ST4ZD7PZ8VVF4G5T2F7QH84TS7CTRHX52ECJ2A2Q?proof=0

**Expected behavior**
Balances should match.

**Additional context**

Above address is for a miner, and has had no transactions other than coinbase. @zone117x suspects coinbase transactions are not emitting STX asset events, in which case this might have to be addressed in stacks-blockchain.

**Comment by psq** [comment]
stacks-blockchai-api relies on events to calculate the balance, and coinbase rewards, when/if they are distributed, do not generate events, and same issue for pre-seeding balances from the `toml` config file.

So this issue probably belongs in stacks-blockchain.

**Comment by zone117x** [comment]
This can be fixed now that we have `matured_miner_rewards` event data merged into master. Added the `before code freeze` label this issue, seems critical.
