### ISSUE TITLE
Ensure that faucet returns adequate amount to initiate Stacking with stacking=true

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain-api#330]
Currently it provides 83336816.666666 STX when 83336825 STX or more are needed for the wallet to initiate Stacking (presumably including fees)

**Comment by zone117x** [comment]
@markmhx closing at duplicate of this issue https://github.com/blockstack/stacks-blockchain-api/issues/319
Should have this ready today or early this week 👍
