### ISSUE TITLE
Resolve Overly Permissive Cross-Origin Resource Sharing (CORS) Policy

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain-api#338]
As reported by NCC as a low risk and low impact concern when auditing the Stacks Wallet, in relation to access-control-allow-origin header in interactions with stacks-node-api.krypton.blockstack.org:

An attacking site could abuse the application’s weak CORS policy to steal user data or perform dangerous actions in the context of the user’s account.

Cross-Origin Resource Sharing (CORS) is a browser standard which allows for the resources or functionality of a web application to be accessed by other web pages originating from a different domain. Before CORS, browsers had a number of strict limitations on the ability of different web applications to communicate with each other. For example, an application could send a request to an application on a different domain, but could not read the response, making “web API” functionality impossible.

CORS makes safe cross-domain requests possible by allowing applications to opt-in to cross- domain communication. If an application wants to allow this type of communication, it can use the following CORS headers:

• Access-Control-Allow-Origin: a domain (or wildcard) which the application wants to allow communication from

By returning these headers, the responding application explicitly states that cross-domain communication is acceptable. The user’s browser checks that the returned values are valid; if so, the browser permits the requesting application to send a cross-domain request and to read the response.

Caution must be taken when defining these header values. Normally, the Same-Origin Policy prevents most cross-domain requests. By returning CORS headers, that protection is severely weakened. An attacking site could abuse this weakness to steal user data or perform danger-ous actions.

The server returns a permissive CORS policy, this could allow any site to make cross origin requests with the Electron application backend.

It should be noted that within the context of the Stacks Wallet there is little chance of ex- ploitability because there are not sensitive values such as cookies or API tokens that could be returned from cross-origin requests. Nevertheless, good defense in depth would be to limit interactions from only whitelisted and trusted sources.

Access-Control headers should be limited to the minimal set of permissions necessary to perform cross-domain functionality. First, Access-Control headers should only be returned for specific, necessary resources or routes, rather than applied globally. For each route, explicitly set the relevant Access-Control headers to allow only the specific methods, headers, or credentials which are necessary.

**Comment by kyranjamie** [comment]
As I understand, this won't be a problem when launched as a production instance? @zone117x

**Comment by zone117x** [comment]
This is a Hira infrastructure related issue, rather than a security issue. We're aware of the consequences of open CORS and will take appropriate measures when necessary.
