### ISSUE TITLE
Locked balance seems cached/stale

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#344]
from the extended api -> https://stacks-node-api.blockstack.org/extended/v1/address/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV/balances
```json
{
  "stx": {
    "balance": "373336112489882",
    "locked": "93334402000000",
    "unlock_height": 3120,
    "total_sent": "0",
    "total_received": "373336112500000",
    "total_fees_sent": "10118",
    "total_miner_rewards_received": "0"
  },
  "fungible_tokens": {},
  "non_fungible_tokens": {}
}
```

From the rpc endpoint (proofs removed) -> https://stacks-node-api.blockstack.org/v2/accounts/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV

```json
{
  "balance": "0x00000000000000000001538c165de59a",
  "locked": "0x00000000000000000000000000000000",
  "unlock_height": 0,
  "nonce": 6
}

```

**Comment by zone117x** [comment]
Endpoint appears okay now, what was the block height at the time of posting?

**Comment by aulneau** [comment]
https://discord.com/channels/621759717756370964/730814571517968436/779101970896125952
