### ISSUE TITLE
CPU and memory spikes when returning frequent 404s

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain-api#357]
**Describe the bug**
When a stream of transactions are being searched through the API which don't exist in the DB, thus returning a 404 we'll see large memory and CPU spikes in the API's resource usage. This can lead to frequent restarts caused by OOMs, or slow performance.

To clarify, the 404s are expected when searching for a TX that does not exist in the DB. However the logic executing to determine and return the 404 seems to be resource-intensive.

**To Reproduce**
Query for a large amount of TXs which don't exist through the API (1000 reqs/sec or more).

**Expected behavior**
The API should return 404s quickly under high requests/sec without over-consuming memory and CPU.

**Screenshots**
![image](https://user-images.githubusercontent.com/2747302/101409170-8234e600-38ab-11eb-8b0b-7881a57b6b6d.png)
![image](https://user-images.githubusercontent.com/2747302/101409195-8f51d500-38ab-11eb-9b1e-e213d800f13d.png)

**Additional context**
Running version`0.34.2`

**Comment by zone117x** [comment]
@timstackblock could you share the scripts/tools used to trigger this condition? I've hammered away at the `/extended/v1/tx/<missing-tx-id>` and `/extended/v1/tx/<valid-tx-id>` endpoints with a profiler attached, at can't replicate the memory spikes with 404s (or 200s). 

My initial guess was that error responses could be triggering the more resource intensive error data collection and logging, but this only happens on 500s not 404s.

**Comment by timstackblock** [comment]
**Steps to reproduce this bug**:

Donwload Jmeter and upload the load test testplan JMX file here: https://github.com/blockstackpbc/devops/blob/master/loadTest/part_2.jmx

This is the test I used to generate the load it basically hits the API with 1000 -2500 vusers and queries the DB. You can set the Vusers by clicking on  Thread group and enter the amount in the Number of threads field.

<img width="1146" alt="Screen Shot 2020-12-15 at 10 24 52 AM" src="https://user-images.githubusercontent.com/49165468/102235020-e402da80-3ebf-11eb-83df-649ba4875295.png">


This test requires you to load a list of transaction IDs then it will take the transaction IDs and append them to the API url. I have attached the list of transactions I have done to this comment.
[message (1).txt](https://github.com/blockstack/stacks-blockchain-api/files/5696790/message.1.txt)

Change the URL you are pointing to here
<img width="1146" alt="Screen Shot 2020-12-15 at 10 26 12 AM" src="https://user-images.githubusercontent.com/49165468/102235144-072d8a00-3ec0-11eb-803c-21c850611bbd.png">


You will need to update the name of the .csv file in jmeter.

You can also query the API and get a list of transactions and use those.

This is where you upload a .csv file with the transactions IDs
<img width="1148" alt="Screen Shot 2020-12-15 at 10 27 01 AM" src="https://user-images.githubusercontent.com/49165468/102235275-2b896680-3ec0-11eb-81d9-b38880a0988b.png">


One of the main things we noticed is that when we use a transaction ID that does not work in the script we get a 400 error and when we have a large amount of 400 issues we start to notice the problem instantly. The best way to do this is to enter an old list of transactions that are no longer in the DB.

I also started to see the problem at 1000 vusers but had 2 restarts and multiple OOMs at 2500 issues.

**Comment by timstackblock** [comment]
It might just be easier for us to schedule some time to run a second test and have Matt on the call it might be faster than having him run the test himself to find the errors  @CharlieC3 @zone117x what do you think?

**Comment by zone117x** [comment]
It would be helpful to re-run those tests against the latest Xenon deployment now that it has more memory allocated, and see if we still run into any OOM issues. Also, establish that it is actually 404s from `/extended/v1/tx/<id>` causing the issue. 

Other than that, there's not much I can debug from watching the tests if I can't reproduce locally.

Locally, I can see the actual object memory usage using the debugger's memory profiler. So far with ~1k requests per second on my machine using [seige](https://github.com/JoeDog/siege), nothing out of the ordinary happens with allocations / memory usage. My local load testing hits some system limit at ~1k/second, so not yet sure what happens at ~2500.

**Comment by CharlieC3** [comment]
I'm ok with retesting to verify, but even if it doesn't OOM it may still be far past acceptable memory usage, since it temporarily has 12X the normal amount of memory allocated to it. We'll be able to monitor resource usage in Grafana and see when it goes past the previous memory threshold of `256Mb`. It's possible recent updates added some necessary complexity to the API, which may be a rational cause to give it more memory, but I want to avoid unintentionally masking any underlying issue by doing that as well.

@timstackblock Let me know when you want to run another test, I'd be happy to share the metrics I'm looking at over Zoom

**Comment by zone117x** [comment]
I'm most interested in validating that there is a memory issue related to 404 handling on the `/extended/v1/tx/<id>` path. The code path for tx 404s is _almost_ the equivalent to a "hello world" Node.js Express route with the addition of out-of-the-box Prometheus and Winston logging. 

If we can confirm this is a source of memory issues, we should be able to reproduce it by running such a "hello world w/ logging" app with the same container setup and see the same memory usage.

**Comment by CharlieC3** [comment]
> If we can confirm this is a source of memory issues, we should be able to reproduce it by running such a "hello world w/ logging" app with the same container setup and see the same memory usage.

@zone117x I'm not sure how else we can reconfirm it besides re-running the test with you present. We saw a very strong correlation between `404`s and memory spikes in Grafana. Are there other ways you know of we can use to confirm this? Would it help if you were `exec`'d into the API container while Tim is running tests?

**Comment by zone117x** [comment]
Since we initially found and debugged this issue, we found some prometheus metric reported issues where each unique endpoint was causing significant overhead, which could explain this issue. We have since fixed that, and haven't experienced this problem since then. Please comment or re-open if this resurfaces.
