### ISSUE TITLE
Don't blindly increment the nonce on `ConflictingNonceInMempool`

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain-api#359]
Suppose the faucet account's confirmed nonce is _N_, and it has _k_ in-flight transactions in the mempool.  Suppose a reorg happens -- the account's confirmed nonce advances to _N + k_ when a block is mined, but it gets overtaken by a fork that hasn't seen the account's transactions.  Now in the new canonical fork, the nonce's account is reduced back to _N_.

```
          D <-- E
        /
       /
A <- B <- C
```

For example, suppose the account's confirmed nonce is _N_ in block _B_, and then block _C_ gets mined.  In _C_, the account's confirmed nonce advances to _N + k_.  But then suppose _D_ and _E_ get mined, and suppose that the miners of _D_ and _E_ never see the transactions.  So when fork _ABDE_ overtakes fork _ABC_, the account's confirmed nonce falls back to _N_, but the mempool still has all transactions from _N_ to _N + k_.

If this happens, the STX faucet will see a `ConflictingNonceInMempool` error if it tries to submit a transaction with nonce _N + i_ for some _0 < i <= k_.  If this happens, the faucet will blindly increment the nonce to use (https://github.com/blockstack/stacks-blockchain-api/blob/1532ffbefd0b485c6adf419b5ec35605c699c190/src/api/routes/faucets.ts#L172).  Moreover, if the faucet gets a `BadNonces` error (which can also happen in this forking scenario), the faucet clears the nonce and attempts to re-learn it in the next call to `makeSTXTokenTransfer` (https://github.com/blockstack/stacks-blockchain-api/blob/1532ffbefd0b485c6adf419b5ec35605c699c190/src/api/routes/faucets.ts#L156).

This behavior is incorrect.  What should happen is if the faucet encounters either error, it should (1) learn the next nonce to use off of the confirmed nonce (via `makeSTXTokenTransfer`), and (2) increment the transaction fee.  This will cause the transaction to be accepted by the node, and will bump any existing mempool transactions with the same nonce out of the mempool.  This will let the faucet keep working in the face of forks like this.

However, some care should be taken when bumping the transaction fee.  The faucet should try and chain transactions together when possible (instead of just re-sending a transaction with the same nonce over and over with higher and higher fees).  But, if it does chaining, it should check to see that whatever was the canonical chain tip at the beginning of the transaction chain is the same as it is when appending to the transaction chain.  If the canonical chain tip changes, _and_ the confirmed nonce _decreases_, then the faucet should use RBF for all transactions that have nonces between what it is now, and the highest such nonce successfully submitted.

**Comment by kantai** [comment]
I don't think that the faucet needs to actually use "replace-by-fee" for this case. The `stacks-node`'s mempool will allow replacements across forks:

```rust
        // if so, is this a replace-by-fee? or a replace-in-chain-tip?
        let add_tx = if let Some(prior_tx) = prior_tx {
            if estimated_fee > prior_tx.estimated_fee {
                // is this a replace-by-fee ?
                true
            } else if !tx.is_block_in_fork(
                chainstate,
                &prior_tx.consensus_hash,
                &prior_tx.block_header_hash,
                consensus_hash,
                block_header_hash,
            )? {
                // is this a replace-across-fork ?
                true
            } else {
                // there's a >= fee tx in this fork, cannot add
                info!("TX conflicts with sponsor/origin nonce in same fork with >= fee: new_txid={}, old_txid={}, origin_addr={}, origin_nonce={}, sponsor_addr={}, sponsor_nonce={}, new_fee={}, old_fee={}",
                      txid, prior_tx.txid, origin_address, origin_nonce, sponsor_address, sponsor_nonce, estimated_fee, prior_tx.estimated_fee);
                false
            }
        } else {
            // no conflicting TX with this origin/sponsor, go ahead and add
            true
        };
```

If we don't want the `stacks-node` mempool to automatically try to apply transactions across forks, then a client needs a way to know that the transactions previously included in the mempool are now not being processed because they are in a different fork. A client that receives a `BadNonce` error, which is the problem that the client is seeing (not `ConflictingNonceInMempool`), needs to be able to figure out what the correct nonce _should_ be. The mempool is capable of answering this question (and it even tries to in the error response), but it currently answers it _wrong_, in `core::mempool`:

```rust

    fn get_next_nonce_as_participant_type(
        conn: &DBConn,
        addr: &StacksAddress,
        as_origin: bool,
    ) -> Result<u64, db_error> {
        let sql = format!(
            "SELECT ifnull(max({0}_nonce + 1), 0) FROM mempool WHERE {0}_address = ?1",
            if as_origin { "origin" } else { "sponsor" }
        );
        match conn.query_row_and_then(&sql, &[addr.to_string()], |row| u64::from_row(row)) {
            Ok(max) => Ok(max),
            Err(db_error::SqliteError(SqliteError::QueryReturnedNoRows)) => Ok(0),
            otherwise => otherwise,
        }
    }

    pub fn get_next_nonce_for_address(
        conn: &DBConn,
        address: &StacksAddress,
    ) -> Result<u64, db_error> {
        let as_origin = MemPoolDB::get_next_nonce_as_participant_type(conn, address, true)?;
        let as_sponsor = MemPoolDB::get_next_nonce_as_participant_type(conn, address, false)?;
        Ok(cmp::max(as_origin, as_sponsor))
    }
```

That returns the max nonce across all forks, which isn't useful to a client during such a fork. I think this really should return the max nonce in the _current_ fork, because that's ultimately how the tx is going to be validated.

**Comment by zone117x** [comment]
@kantai do you know of anything I can do on the faucet side right now to help with this issue? Should it implement replace-by-fee? If so, do you have any suggestions on how to combine this with nonce stacking? I assume it would be something like:
1. Increment nonce and retry until max stack height is reached.
2. If still not accepted, start back an expected nonce, and increment the fee.

But this seems brittle in a number of ways.

**Comment by kantai** [comment]
Yeah -- I think that the faucet needs to do some combination of the following:

1. ConflictingNonceInMempool -- this means that whatever nonce was used in the submitted transaction is already used by a transaction in the mempool. The faucet can increment the nonce and resubmit until it receives a TooMuchChaining error.
2. The faucet should be monitoring its transactions. If a transaction is pending for more than a few blocks, the faucet should try to resubmit that transaction by:
        * Submitting the transaction directly to the miner rather than the follower
        * If the above _also_ fails, increase the tx fee on the stuck transaction and resubmit

**Comment by agraebe** [comment]
Seeing we merged a fix for this but with a note that some other cases might not be fixed. Should this issue stay open? If so, what cases are unresolved?

**Comment by zone117x** [comment]
Haven't seen a reported problem in a while. Closing for now (and hopefully forever).
