### ISSUE TITLE
API for postcondition generations 

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#366]
**Is your feature request related to a problem? Please describe.**
Writing postconditions can be difficult for contracts that deal with traits. A market place contract might accept any tokens that implement a certain trait. For the app developer, it is not possible to know what token types will be transferred and therefore, it is not possible to write proper postconditions 

**Describe the solution you'd like**
A new API endpoint `v1/postconditions` should return a description of postconditions for any given contract call tx. 

**Describe alternatives you've considered**
Contracts could expose meta data that help to find e.g. the native token names

Use postcondition mode `allow`

**Additional context**

http://www.openintents.org/blog/2020/12/11/contract-calls-on-speed-spend.html

**Comment by zone117x** [comment]
Hey @friedger, I'm not totally sure I understand how this request relates to this repo. If I understand the issue correctly, it sounds like something the stacks-node would provide after evaluating an arbitrary transaction? I'm closing for now, please re-open or comment if you have more details.
