### ISSUE TITLE
BNS: off-chain name database

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain-api#370]
We need to port the off-chain name database from BNS 1.0 to BNS 2.0.  In watching the off-chain name system over the years, I've noticed that basically no one uses the `NAME_TRANSFER` feature for off-chain names, so in the interest of keeping the implementation simple, I'm proposing dropping it during the port.  The off-chain name system in BNS 2.0 would only support name creation and name updates (i.e. zonefile updates), but not transfers (i.e. no re-keys).

**Comment by diwakergupta** [comment]
This is basically the original issue for the BNS work that Tintash is currently doing. We moved it over from `stacks-blockchain`: @zone117x feel free to close out if it duplicates any other existing issues. cc/ @fariedt

**Comment by zone117x** [comment]
Closing in favor of https://github.com/blockstack/stacks-blockchain-api/issues/317
