### ISSUE TITLE
Faucet is broken 🚰🚫

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain-api#371]
Let's use this issue to track when the faucet is broken generally, closing and re-opening it with more information as needed.

![image](https://user-images.githubusercontent.com/28991/102802564-23955f00-43b7-11eb-92e5-8d3ae63db0ee.png)

**Comment by aulneau** [comment]
This is the error that I've gotten related to this:

`FetchError: request to http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/fees/transfer failed, reason: connect ECONNREFUSED 10.1.233.55:20443`

**Comment by zone117x** [comment]
Looks like the follower was down or rejecting requests

**Comment by markmhx** [comment]
This is the latest manifestation for me https://github.com/blockstack/stacks-blockchain-api/issues/372
