### ISSUE TITLE
[Miners] API node reports a different balance than stacks-node

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/stacks-blockchain-api#376]
## Describe the bug

While running a miner for the Daemon competition, I noticed some odd behavior in my STX balance and was unable to find the info I was looking for based on the [get account transactions](https://blockstack.github.io/stacks-blockchain-api/#operation/get_account_transactions) endpoint.

I can see my balance and transactions via curl, but there is no `coinbase_amount` in the latter, which doesn't help me piece together why my balance is higher than expected.

Both stacks-dump and the [mining monitor](http://monitor.stxmining.xyz/mining_info) show my address has 8 actual wins, and I see the same 8 wins in the transactions endpoint.

Some history:

- 12/22 I ran stacks-dump and saw 1 actual win, 2 total wins, and a 1,500 STX balance
- 12/25 stacks-node crashed and I synced again from 0
- 12/26 from mining-bot I see 7 actual wins and 10,000 STX
- 12/28 from mining-bot I see 8 actual wins and 16,500 STX
- 12/28 stacks-node crashed and I am syncing again from 0

Addresses:

- BTC: mn4Y1j7kAgnM5mP4cMhGqSsNQtFFeWxta7
- STX: ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45

## Steps To Reproduce

1. Run stacks-node on the Krypton network
2. Wait for rewards :1st_place_medal: 

## Expected behavior

I expected my balance to increase by either 500 STX or 1000 STX, and iirc it should be 500 STX on Krypton.

`500 STX * 8 Actual Wins = 4,000 STX`

## Environment

 - OS: Ubuntu Server 20.04 (run via Virtualbox)
 - Rust version: rustc 1.46.0 (04488afe3 2020-08-24)
 - Output of `stacks-node version`: stacks-node 0.1.0 => 23.0.0.0 (master:c176dda+, release build, linux [x86_64])

## Additional context

I am running bitcoind locally connected to the Krypton regtest network, and pointing my stacks-node to the local instance at 127.0.0.1. I can provide more configuration info if necessary.

Results from the `balances` endpoint:

```bash
curl -w "\n" https://stacks-node-api.krypton.blockstack.org/extended/v1/address/ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45/balances | jq
```

```json
{
  "stx": {
    "balance": "16500000000",
    "total_sent": "0",
    "total_received": "0",
    "total_fees_sent": "0",
    "total_miner_rewards_received": "16500000000",
    "lock_tx_id": "",
    "locked": "0",
    "lock_height": 0,
    "burnchain_lock_height": 0,
    "burnchain_unlock_height": 0
  },
  "fungible_tokens": {},
  "non_fungible_tokens": {}
}
```

Results from the `transactions` endpoint:

```bash
curl -w "\n" https://stacks-node-api.krypton.blockstack.org/extended/v1/address/ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45/transactions | jq
```

```json
{
  "limit": 20,
  "offset": 0,
  "total": 8,
  "results": [
    {
      "tx_id": "0xb27a423e6b177dce343b75434a15469259e29f0c13406aaea63252a29c9546eb",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0xde47b92af15473bcdd869b80fde28290075190dae27b92d55edcbfeb809e7508",
      "block_height": 1061,
      "burn_block_time": 1609039951,
      "burn_block_time_iso": "2020-12-27T03:32:31.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x769e4acb43d40911cf03611fd42400bd168c1e28a898acdcfe3cbef177c29427",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0x55fda5b4e5db0d66eb16153c8c951655923ec29f2253d900111029c7ef6a8a6d",
      "block_height": 992,
      "burn_block_time": 1608959631,
      "burn_block_time_iso": "2020-12-26T05:13:51.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x9ff2a637d85911ef09f1f2c4280f5cc757458fe53f28fdbd7fb14db50a376764",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0x6f059a75df1baa202edc33ea7faa28507d9c32bb09d5305b6ed9723e3725391a",
      "block_height": 984,
      "burn_block_time": 1608949987,
      "burn_block_time_iso": "2020-12-26T02:33:07.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0xbcbbb26c2c7f7e15c108e553510ba3ad78870e016a4ee1a48e4f17e68ebad267",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0x28d9df6d1ffa4072f46990ed5f10b1f642c778a9d2689ae71f60a5f29c4da73e",
      "block_height": 868,
      "burn_block_time": 1608823153,
      "burn_block_time_iso": "2020-12-24T15:19:13.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x475208c9e42fb72c1f929f650ff22527213d5dc995ab552eecfc6b00629c57ae",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0x896f3670de34c1450402f4cc95b9d45ddbe1df60fdb4cfae9014ce9e1cba4e25",
      "block_height": 867,
      "burn_block_time": 1608822647,
      "burn_block_time_iso": "2020-12-24T15:10:47.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x8b96095211a97256ba5d72331a195f7396d3b04cec9ae3488e188622f9a57074",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0xfd9d010177a4b075cb1d15b55567f247cceb63a4249212ab66a94e11b5a1cbb6",
      "block_height": 863,
      "burn_block_time": 1608817522,
      "burn_block_time_iso": "2020-12-24T13:45:22.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x114f81ab6fe0e1e7cc7d4976bce7d61ec21ecfdc7cef614d14a7c2f09ebf5010",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0xb7dbf3460489a520243a0e7a0c289f1cc40f0b42a25f807a1268fb409a969916",
      "block_height": 832,
      "burn_block_time": 1608790208,
      "burn_block_time_iso": "2020-12-24T06:10:08.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    {
      "tx_id": "0x40deb0b3a88da1512a0f78505ec925bf71e4731e6c516646779d2b3df37b8933",
      "tx_type": "coinbase",
      "fee_rate": "0",
      "sender_address": "ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45",
      "sponsored": false,
      "post_condition_mode": "deny",
      "tx_status": "success",
      "block_hash": "0xe7a0436286b2e5724403c6929c3471fb2dba5cb953fa231e2df9915c4ad98975",
      "block_height": 469,
      "burn_block_time": 1608552569,
      "burn_block_time_iso": "2020-12-21T12:09:29.000Z",
      "canonical": true,
      "tx_index": 0,
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "coinbase_payload": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    }
  ]
}
```

-----

*Note: not sure if this qualifies for any of the items below, but leaving the list in case there are any items we can check off while looking into this further.*

-----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by zone117x** [comment]
> I noticed some odd behavior in my STX balance and was unable to find the info I was looking for based on the get account transactions endpoint. I can see my balance and transactions via curl, but there is no `coinbase_amount` in the latter, which doesn't help me piece together why my balance is higher than expected.

Note that transaction objects do not contain a `coinbase_amount` field. Stacks coinbase transactions do not directly encode the block reward amount. The block rewards and transaction fees mature over time and are eventually sent to the API through an event as `matured_miner_rewards`.

That said, there does appear to be a discrepancy between what the stacks-node and API are reporting:

`https://stacks-node-api.krypton.blockstack.org/v2/accounts/ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45`:

```json
{
  "balance": "4000000000",
  "locked": 0,
  "unlock_height": 0,
  "nonce": 8
}
```

vs

`https://stacks-node-api.krypton.blockstack.org/extended/v1/address/ST13WKJYTHMXXYVG80ZQ9Q6D6FXB27KB6GK0MYZ45/stx`:

```json
{
  "balance": "16500000000",
  "total_sent": "0",
  "total_received": "0",
  "total_fees_sent": "0",
  "total_miner_rewards_received": "16500000000",
  "lock_tx_id": "",
  "locked": "0",
  "lock_height": 0,
  "burnchain_lock_height": 0,
  "burnchain_unlock_height": 0
}
```

**Comment by zone117x** [comment]
Looks like this could be caused by re-org handling using the `from_index_consensus_hash` value rather than the `index_consensus_hash` from the block that it matured in. Working on fixing and testing.

**Comment by zone117x** [comment]
More info from @psq here: https://github.com/blockstack/stacks-blockchain-api/issues/410

**Comment by paradigma-cl** [comment]
I came across with different balances for a STX account.  The wallet shows that it has 35K.  Using stx balance for the same account it shows 25K.  The explorer.stacks.co shows the same 35K.   
So when trying to send the total amount of 35K, the response is that it does not have sufficient funds, and shows the value in Hex of 25K and the value of 35K.

**Comment by paradigma-cl** [comment]
This in mainnet.

**Comment by paradigma-cl** [comment]
The difference between the balance from explorer.stacks.co, or the Stacks wallet and the node balance is growing.  It is a very misleading difference. +12K STX difference.  Miner rewards grow, but the actual balance keeps being the same.

**Comment by zone117x** [comment]
@paradigma-cl do you mind posting the miner address you're using? I should be able to verify a fix with only @psq's info but more can help.

**Comment by paradigma-cl** [comment]
@zone117x  Our mining pool is SPY1PP2KZ67B4SC678YFQKQPKY8Y1AP7TJS53M64
