### ISSUE TITLE
A new RPC method for Querying block by block number

### ISSUE THREAD

**Issue by Wangmmx** [blockstack/stacks-blockchain-api#377]
Hello, can you please provide an RPC interface to get block details through blockNumber? 

At present, it can only be queried by block hash. I need to query and traverse the block number to get the details of each block. It cannot be done without knowing the hash of the block.

Thanks! Looking forward to your reply!

**Comment by psq** [comment]
use https://blockstack.github.io/stacks-blockchain-api/#tag/Blocks to get the list of blocks (with limit and offset, you should be able to get all block hashes, then you can request the blocks you want

**Comment by Wangmmx** [comment]
Well, I looked at this interface, which is what I currently do. But to find the specified block, I still need to get the current block height to calculate the offset. Well, it doesn't matter if it’s not convenient to add a new interface.

**Comment by zone117x** [comment]
@Wangmmx feel free to leave this issue open. This endpoint could be added but I most likely won't get around to it for at least a couple weeks.

**Comment by Wangmmx** [comment]
Ok, I also need to debug for a while, I will pay attention to it at any time, thanks

**Comment by agraebe** [comment]
This is possible with one of the Rosetta endpoints @Wangmmx:

Use [/rosetta/v1/block](https://blockstack.github.io/stacks-blockchain-api/#operation/rosetta_block)
```
{
    "network_identifier": {
        "blockchain": "stacks",
        "network": "testnet"
    },
    "block_identifier": {
        "index": "560" // blockNumber
    }
}
```

**Comment by Wangmmx** [comment]
> This is possible with one of the Rosetta endpoints @Wangmmx:
> 
> Use [/rosetta/v1/block](https://blockstack.github.io/stacks-blockchain-api/#operation/rosetta_block)
> 
> ```
> {
>     "network_identifier": {
>         "blockchain": "stacks",
>         "network": "testnet"
>     },
>     "block_identifier": {
>         "index": "560" // blockNumber
>     }
> }
> ```

Thanks for your reply! Can I use   "network": "testnet" for the STX mainnet?

**Comment by agraebe** [comment]
Yes, the label is hard coded and needs to be fixed: https://github.com/blockstack/stacks-blockchain-api/issues/399

**Comment by zone117x** [comment]
This was implemented in https://github.com/blockstack/stacks-blockchain-api/pull/462
