### ISSUE TITLE
Provide ability to fetch information for a pending contract

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#378]
Currently, if you hit the search endpoint with a valid and pending contract_address, the result will be found, but you cannot fetch any data related to it because the current contract endpoint does not return any data for pending contract deploys.

In the explorer you are able to view a transaction page either by the tx_id or contract_address, and behind the scenes if you're using the contract_address as the identifier, it will fetch the contract data via the contract endpoint, get the tx_id and then fetch the transaction data for that deploy. 

The same is true in the context of a pending contract deploy, but currently we have no ability to find the associated tx_id.

An interim solution is to fetch all pending transactions, or some set of them, and try to filter by the contract_address. This will not scale as there could be paginated results for pending txs (eg more than 200 pending txs).

Can either of these be possible in the near term?

- have the contract endpoint return some data for pending txs (even just the tx_id)
- have the search result end point return a tx_id for the contract_address?

Or: am i missing a currently implemented solution to this issue?

**Comment by asimm241** [comment]
I have started looking into this issue !

**Comment by asimm241** [comment]
> Can either of these be possible in the near term?
> 
> * have the contract endpoint return some data for pending txs (even just the tx_id)
> * have the search result end point return a tx_id for the contract_address?
> 

- @zone117x I am confused, the contract endpoint already returning `tx_id` and not filtering pending contracts.
   here is the query for the contract endpoint:
`
        SELECT tx_id, canonical, contract_id, block_height, source_code, abi
        FROM smart_contracts
        WHERE contract_id = $1
        ORDER BY canonical DESC, block_height DESC
        LIMIT 1
`.

- I can add `tx_id` in the search result though.

**Comment by zone117x** [comment]
The issue is referencing transactions within the mempool (AKA pending). Data for these transactions are in the `mempool_txs` table.

**Comment by asimm241** [comment]
Gottcha. I can add tx_id in the search result.
