### ISSUE TITLE
RPC v2/info can not get stacks_tip_height

### ISSUE THREAD

**Issue by Wangmmx** [blockstack/stacks-blockchain-api#379]
The data obtained by the interface v2/info does not have the latest block height and hash `stacks_tip_height` `stacks_tip`.  Before the chain reset it was correct. This time the block data is always the initial data 0. Will this be updated afterwards? Or is there any other interface to get the block height?

**Comment by zone117x** [comment]
All `/v2` endpoints are simple proxies to the stacks-blockchain core node. This issues should be re-opened there. 
I think the answer to your question is that the node was still booting up and syncing when you checked it.
