### ISSUE TITLE
Filter mempool by receiving address

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-blockchain-api#380]
In context of https://github.com/blockstack/stacks-wallet/issues/316, I'd be helpful to be able to filter mempool transactions by the receiving address & return a complete un-paginated list.

As the mempool is paginated, it's a arduous task for a client to poll & iterate through all pages of transactions and filter them.

A short-term work around would be simply to remove the 200 items limit, allowing a client to receive _all_ txs in the mempool.

**Comment by aulneau** [comment]
Agreed -- I made this issue suggesting including pending txs with the confirmed for a given address -> https://github.com/blockstack/stacks-blockchain-api/issues/299

**Comment by agraebe** [comment]
In addition to filtering by receiving address, a filter by sender would be very useful. We have a "25 txs in mempool per account" limit and knowing how many txs are still pending is difficult right now
