### ISSUE TITLE
STX/FT/NFT events are taking into account even though the tx was aborted due to post conditions

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#390]
**Describe the bug**
The balance of the 
https://stacks-node-api.blockstack.org/extended/v1/address/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV/balances is negative (2 sent, 1 received)

There is a failed transfer tx https://testnet-explorer.blockstack.org/txid/0x4acf2c480eccc0c4341f13978d9a264b95385341c48bb6dc8707dc7fdab8475c?chain=testnet with a sent event for the nft

**To Reproduce**
1. Deploy nft contract
2. Mint an nft
3. transfer without a post condition creating an invalid tx
4. transfer with post conditions creating a valid tx
5. see the account balances for the sender and receiver address

**Expected behavior**
Events of aborted txs should not be taking into account. The balance should be 0, not -1

**Screenshots**
![Screenshot from 2021-01-11 17-52-29](https://user-images.githubusercontent.com/1449049/104212714-cd579100-5435-11eb-8e62-1a0a243f83fd.png)

@timstackblock

**Comment by zone117x** [comment]
This bug seems to effect STX and FTs as well:
https://github.com/blockstack/stacks-blockchain-api/issues/431
https://github.com/blockstack/stacks-blockchain-api/issues/392
