### ISSUE TITLE
Support running in dev mode with small migration files

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#391]
Currently around 1 GB of files are required for Stacks 1.0 imported BNS support:
```
  chainstate.txt
  chainstate.txt.sha256
  name_zonefiles.txt
  name_zonefiles.txt.sha256
  subdomains.csv
  subdomains.csv.sha256
  subdomain_zonefiles.txt
  subdomain_zonefiles.txt.sha256
```
A compressed tar.gz file is still a 300+ MB file. A couple issues here:
* Committing very large files to git is typically a bad idea that causes a lot of problems.
* Importing these files into postgres during runtime makes the program init take 3-10 minutes longer. Essentially ruins the development cycle where program init takes a few seconds.
* The majority of dev, including internal, who clone this repo will not need all of this, and git cloning hundreds of megabytes of data, and waiting several minutes for init, is very counter product.

### Proposed solution:
Do not commit these production files at all. Instead, commit sample versions of each file (similar to the stacks-node core repo). During runtime, when `NODE_ENV=production` is enabled, ensure the full production files are provided otherwise exit with error. This can be done with a simple hash comparison. The production file can be uploaded as a github release artifact with some helper fetch scripts provided to make running a prod env from a `git clone` easy. Production docker images should include the full production files.

**Comment by CharlieC3** [comment]
I like the idea of using samples of each file for a `dev` build, and I agree with you WRT avoiding committing any large files directly to the repo. As you suggested I feel committing them as a release artifact could work, however have you considered using [`git-lfs`](https://git-lfs.github.com/) instead? It's designed for situations like this where you need to version a large file, or associate a large file with a repo, and I know you're able to configure it to avoid downloading the tracked file(s) by default.

Not saying `git-lfs` is the better solution, but if you find it works for your team it might be easier to manage than an additional script.
