### ISSUE TITLE
FT Rollbacks not being applied

### ISSUE THREAD

**Issue by reedrosenbluth** [blockstack/stacks-blockchain-api#392]
The API doesn't seem to be applying rollbacks properly that are triggered when a contract-call transaction fails due to a post-condition not being met.

Example:
https://testnet-explorer.blockstack.org/txid/0xa989abf5c292bb3514a14495f3a186ac81698fc61d3fa669edeec792832859fa?chain=testnet

This transaction fails, yet the API still reports the FT transfer having gone through.

As a result, the contracts account is showing a negative FT balance:
https://testnet-explorer.blockstack.org/address/ST3YJ4XYJV3S1JHQK3HG21MVTCG50ZYG9TQY10A81?chain=testnet

**Comment by zone117x** [comment]
I think this issue along with https://github.com/blockstack/stacks-blockchain-api/issues/431 has the same root problem as https://github.com/blockstack/stacks-blockchain-api/issues/390
Going close this one for now and use the original one for tracking purposes, thanks @reedrosenbluth
