### ISSUE TITLE
Lost block leads to no further processing of blocks

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain-api#397]
(h/t @CharlieC3 for digging up the relevant logs)

Observed that `v2/info` on follower was returning tip 135, but `extended/v1/block` was only showing up to block 119.

API logs show that [block 120 was not received](https://kibana.blockstack.xyz/s/blockstack/app/kibana#/discover/7c01ade0-5386-11eb-b526-63185ec699b1?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30m,to:now))&_a=(columns:!(message,req.url),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'66fbdfb0-d9f1-11ea-bc1e-910592cb0684',key:kubernetes.namespace_name,negate:!f,params:(query:prod-stacks),type:phrase),query:(match_phrase:(kubernetes.namespace_name:prod-stacks))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'66fbdfb0-d9f1-11ea-bc1e-910592cb0684',key:kubernetes.container_name,negate:!f,params:(query:stacks-node-api),type:phrase),query:(match_phrase:(kubernetes.container_name:stacks-node-api)))),index:'66fbdfb0-d9f1-11ea-bc1e-910592cb0684',interval:auto,query:(language:lucene,query:'%22Received%20block%22'),sort:!())).

Around the same time, [follower node reported](https://kibana.blockstack.xyz/s/blockstack/app/kibana#/discover/191885e0-5387-11eb-b526-63185ec699b1?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-01-15T22:44:05.393Z',to:'2021-01-15T22:44:07.188Z'))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'66fbdfb0-d9f1-11ea-bc1e-910592cb0684',key:kubernetes.namespace_name,negate:!f,params:(query:prod-stacks),type:phrase),query:(match_phrase:(kubernetes.namespace_name:prod-stacks))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'66fbdfb0-d9f1-11ea-bc1e-910592cb0684',key:kubernetes.container_name,negate:!f,params:(query:stacks-node-follower),type:phrase),query:(match_phrase:(kubernetes.container_name:stacks-node-follower)))),index:'66fbdfb0-d9f1-11ea-bc1e-910592cb0684',interval:auto,query:(language:lucene,query:event),sort:!())) "Failed HTTP connection on event 192" (and 193)

Unclear if this is an issue on stacks-node (in theory it should block if an event is not successfully consumed), or on the API side (should it request missing blocks again?), opening here so we can at least debug further cc/ @lgalabru

**Comment by CharlieC3** [comment]
> API logs show that block 120 was not received. 

I think I gave you a link that wasn't set to a specific time to find that missing block. [Try this instead.](https://kibana.blockstack.xyz/s/blockstack/goto/787293f2734613603c78e76cf1f42cbd)

**Comment by lgalabru** [comment]
Block 120 includes an occurence of a transaction described here - https://github.com/blockstack/stacks-blockchain-api/issues/396, crashing the parser.
@hstove is working on a patch.

**Comment by zone117x** [comment]
I think we can close this. We fixed the underlying issue causing issues with block 120. I don't think we should implement something like a "lossy" operating mode. Right now the API attempts to be as explicit as possible with parsing, and effectively "panics" by halting processing of new blocks when something goes wrong -- which it what happened and I think was the appropriate behavior.

**Comment by diwakergupta** [comment]
Duplicate of #396 , closing.
