### ISSUE TITLE
Expose nonce in transactions

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain-api#404]
Currently the API endpoint for a TX does not include a `nonce` when the transaction is pending. It would be super helpful to expose this.

- It would make it easier to see if an address has conflicting nonces in the mempool (although ultimately they should be purged, this would help)
- It would help debug pending TXs in general

**Comment by zone117x** [comment]
Remaining this issue to just "expose tx nonce", since it's encoded in the raw tx payload it will trickle down to the mempool responses as well 👍
