### ISSUE TITLE
API node reports a different balance than stacks-node

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain-api#410]
### Description
This seems to be mostly related to accounts that have coinbase transactions.

Taking some of the top miner addresses (mostly have coinbase transactions):

I was using requests such as `http://seed-0.mainnet.stacks.co:20443/v2/accounts/SP1RJH1641855357CXFBF1H2WFWASXDX4DZ79QH1P?proof=0` to get the balance from the node, while using the explorer to get the api node value (such as `https://explorer.stacks.co/address/SP3S9C931DEC0NZWEQBPCW6HGMN8T0TJHED5YDG5S?chain=mainnet`)

```
SP137NZXD0BM4DM875ZH2HGDNPEBP6KW18RFXQ9W3
/v2/accounts: 124221403210 = 124,221.40321
explorer: 161,217.260952
=> off by 36,996 (off by 15 block rewards, 5 orphaned blocks)

SP1RJH1641855357CXFBF1H2WFWASXDX4DZ79QH1P
/v2/accounts: 392158331793 = 392,158.331793
explorer: 424,221.34725
=> off by 32, 063 (off by 13 block rewards, 1 orphaned blocks)

SP3S9C931DEC0NZWEQBPCW6HGMN8T0TJHED5YDG5S
/v2/acounts: 97533885237 = 97,533.885237
explorer: 109,865.791317
=> off by 12,332 (off by 5 block rewards, 5 orphaned blocks)

SPP1DJ1JE2V8HYHTRHPWD7603XHJ3F7421KBC4TE
/v2/accounts: 5442865066 = 5,442.865066
explorer: 22,707
=> off by 17,265 (off by 7 block rewards, 5 orphaned blocks, but some may be after skipped blocks)
```

The miner reward totals displayed in the explorer seem to be off as well, but did not analyze in details, except it may not explain the discrepancies above.

I included the number of orphaned blocks (at least as stacks-dump report them), thinking this might explain the difference, but it does not seem to be the case...

### Expected behavior
balances should match what is reported by stacks-node

### Notes
1. this also causes the wallet to report an incorrect balance, making the `withdraw max` not so useful as you can not rely on the displayed balance.

2. I'm curious why the api node would try to reconstruct the balance rather than use what a stacks-node would have, which is the source of truth.  Especially with the coinbase transactions that have many rules like varying reward over time, reward for skipped blocks, coinbase transactions in blocks that become orphaned, to name a few...

**Comment by zone117x** [comment]
This is a known issue, related to the way reward events are being handled https://github.com/blockstack/stacks-blockchain-api/issues/376

> I'm curious why the api node would try to reconstruct the balance rather than use what a stacks-node would have, which is the source of truth

The API can break down STX balance by transfers, rewards, and fees. The API is also an order of magnitude or so faster than the stacks-node. The node lb pool would probably have to be tripled if the explorer and wallet tried using the `v2/accounts` endpoint.

**Comment by zone117x** [comment]
Close this issue in favor of the original, and renaming the original to something more accurate. 
Thanks for the data @psq this will be super helpful in testing out the fix.
