### ISSUE TITLE
Support for Bitcoin stacking transaction type 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-blockchain-api#411]
Critical to happen before eod Tues, Jan. 26 so that we can unblock the stacking 5% participation level on Wed. Jan 27th ahead of the stacking prepare phase on Thurs, Jan. 28th. 

cc @agraebe if there is better language or timing estimates here.

**Comment by diwakergupta** [comment]
> Critical to happen before eod Tues, Jan. 26 so that we can unblock the stacking 5% participation level on Wed. Jan 27th ahead of the stacking prepare phase on Thurs, Jan. 28th.
> 
> cc @agraebe if there is better language or timing estimates here.

For some additional context (based on my understanding):

* Stacks 2.0 supports STX transfers as well as stack-stx via Bitcoin transactions as [described in SIP-007](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-007-stacking-consensus.md#bitcoin-wire-formats)
* Last Friday, @hstove added the ability to process STX transfers in Bitcoin transactions, but not `stack-stx` yet. So if someone were to send a `stack-stx` via Bitcoin transaction, it will likely crash the API

**Comment by GinaAbrams** [comment]
Any update on this or blockers to discuss @zone117x ? 🙏

**Comment by zone117x** [comment]
Still working on this. Should have something ready by eod tomorrow. 👍

**Comment by zone117x** [comment]
The PR for this in review https://github.com/blockstack/stacks-blockchain-api/pull/414

We should aim to have it merged and deployed tomorrow early EST, and the btc transaction followed shortly after. This will give me and others time to react to any potential issues in mainnet that weren't caught in local testing.
