### ISSUE TITLE
Postman bundle is out of date

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain-api#417]
**Describe the bug**
Postman api bundle still includes blockstack.org links which dont work.
@zone117x Attached is an updated bundle that points to stacks.co.  May need updates for sidecar links to blockstack.xyz

[Stacks Blockchain API.postman_collection.zip](https://github.com/blockstack/stacks-blockchain-api/files/5884802/Stacks.Blockchain.API.postman_collection.zip)

**Comment by agraebe** [comment]
@rafaelcr as per our conversation today, we could explore how to auto-generate the collection from the OpenAPI spec

**Comment by rafaelcr** [comment]
#746 just filed this issue to track the autogeneration
