### ISSUE TITLE
Ingest and expose locked token information (from the genesis data, not pox related locking)

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#423]
(Reducing issue https://github.com/blockstack/stacks-blockchain/issues/2033 into the couple remaining tasks)

Import locked token data from the Stacks 1.0 chain data (can be found in this file: https://github.com/blockstack/stacks-blockchain/blob/master/stx-genesis/chainstate.txt). 

This should be performed within the [`src/import-v1/index.ts`](https://github.com/blockstack/stacks-blockchain-api/blob/b65f1d89386a7a786e9cc25ef06b05e71afed77a/src/import-v1/index.ts) file.

Account balance API endpoints then need updated to display this locked token data.

**Comment by zone117x** [comment]
Yep, we are going to ingest this data directly from the v1 dump. We'll wait until the bns branch is merged into master before working on this, as that is where all the v1 import code currently exists.

**Comment by zone117x** [comment]
Note the requested API endpoints for exposing this data:
https://github.com/blockstack/stacks-blockchain-api/issues/436
https://github.com/blockstack/stacks-blockchain-api/issues/437

**Comment by markmhx** [comment]
@zone117x We'll need this to support the display of total, unlocked and locked balances in the wallet per https://github.com/blockstack/stacks-wallet/issues/453, though you're correct that this is already resolved in the explorer.

It's not super urgent but we may be looking to develop the above wallet functionality in the coming days. Is the [work for "v1-genesis data import code in the bns branch"](https://github.com/blockstack/stacks-blockchain-api/issues/437#issuecomment-779262711) something expected to take much longer?

**Comment by zone117x** [comment]
> It's not super urgent but we may be looking to develop the above wallet functionality in the coming days. Is the work for "v1-genesis data import code in the bns branch" something expected to take much longer?

I don't know. The v1 import code can be extracted from that branch in the mean time, it's just a bit messy.

**Comment by zone117x** [comment]
Just noticed that https://github.com/blockstack/stacks-blockchain-api/issues/515 is a dupe of this issue. However, the newer issue has more useful info so I'm closing this one as the dupe.
