### ISSUE TITLE
how could i start stacks-blockchain-api in xenon mode?

### ISSUE THREAD

**Issue by panchengj** [blockstack/stacks-blockchain-api#424]
i started a xenon node with bitcoin testnet ,but when i run "docker run -p 3999:3999 blockstack/stacks-blockchain-api-standalone",i get a mainnet log
"
==> stacks-node.log <==
INFO [1612257733.904454] [src/burnchains/bitcoin/spv.rs:913] [main] Syncing Bitcoin headers: 0.3% (2000 out of 668718)
INFO [1612257734.930287] [src/burnchains/bitcoin/spv.rs:913] [main] Syncing Bitcoin headers: 0.6% (4000 out of 668718)
INFO [1612257736.067087] [src/burnchains/bitcoin/spv.rs:913] [main] Syncing Bitcoin headers: 0.9% (6000 out of 668718)
INFO [1612257737.025762] [src/burnchains/bitcoin/spv.rs:913] [main] Syncing Bitcoin headers: 1.2% (8000 out of 668718)
INFO [1612257737.905063] [src/burnchains/bitcoin/spv.rs:913] [main] Syncing Bitcoin headers: 1.5% (10000 out of 668718)

==> stacks-api.log <==
{"message":"Event observer listening at: http://127.0.0.1:3700","level":"info","timestamp":"2021-02-02T09:22:18.779Z"}
"
![image](https://user-images.githubusercontent.com/13955506/106582124-9da43080-657e-11eb-90bb-7f9ee3f87c42.png)

how could i get stacks-blockchain-api in xenon mode?

**Comment by friedger** [comment]
Could you please share your bitcoind conf? It should say regtest=1 somewhere.

**Comment by panchengj** [comment]
this is my bitcoin.conf:

datadir=/data/bitcoin
testnet=1
server=1
whitebind=127.0.0.1:18333
whitelist=127.0.0.1
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashtx=tcp://127.0.0.1:28333
zmqpubhashblock=tcp://127.0.0.1:28334
zmqpubrawblock=tcp://127.0.0.1:28335
rpcallowip=0.0.0.0/0
rpcport=18332
rpcuser=bitcorenodetest
rpcpassword=local321
uacomment=bitcore
