### ISSUE TITLE
STX balances are off for a `post_condition_failed` transaction with `stx-burn?`

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain-api#431]
Referencing this [BNS pre-order tx on testnet](https://explorer.stacks.co/address/STWXWQQ69DCT4VFA4X8R0XT9M01EYMEKED8PD7R2?chain=testnet).

The transaction has "Deny" mode as post conditions. The TX failed, because it didn't match the post conditions. However, the 2 STX were still withdrawn from the user's balance on the API DB, and there is an "STX Burn" event on the tx.

I've verified that the balance for the "real" transaction is what you'd expect - via https://stacks-node-api.testnet.stacks.co/v2/accounts/STWXWQQ69DCT4VFA4X8R0XT9M01EYMEKED8PD7R2

I would assume we are missing some logic when processing STX burn events for failed transactions, or there is some funky behavior around events emitted for `stx-burn?` calls.

**Comment by zone117x** [comment]
I think this issue, along with https://github.com/blockstack/stacks-blockchain-api/issues/392, has the same root problem as https://github.com/blockstack/stacks-blockchain-api/issues/390
I'm going close this one for now and use the original one for tracking purposes. Thanks for the info @hstove 👍
