### ISSUE TITLE
[Rosetta] Unexpected order of ECDSA signature components

### ISSUE THREAD

**Issue by pablojorge** [blockstack/stacks-blockchain-api#434]
The Rosetta specs for the `ecdsa_recovery` sig type says that the components should be in this order: `r (32-bytes) || s (32-bytes) || v (1-byte)` (https://github.com/coinbase/rosetta-specifications#supported-signaturetypes). That's the order commonly used, see for example: https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/crypto/ECKey.java#L699

But the non-rosetta specific `parseRecoverableSignature()` function expects `v` to be first: https://github.com/blockstack/stacks.js/blob/7a70542f96ec0d76645cf8988261701673c5abc5/packages/transactions/src/keys.ts#L180

Clients may workaround this by moving the last byte to the first position before sending the signature, but this requires coin-specific code. There seems to be code to do precisely that in the server, but it only applies for certain values of `v`: https://github.com/blockstack/stacks-blockchain-api/blob/268712bb05a075650ff9bc6b9a132ba8e549608a/src/api/routes/rosetta/construction.ts#L530

(Related: https://github.com/coinbase/rosetta-sdk-go/issues/201)

**Comment by noumanahmads** [comment]
@pablojorge 
We have placed this if condition
https://github.com/blockstack/stacks-blockchain-api/blob/268712bb05a075650ff9bc6b9a132ba8e549608a/src/api/routes/rosetta/construction.ts#L529
because of the `secp256k1` library. As it is explained here 
https://github.com/coinbase/rosetta-sdk-go/issues/201#issue-726991948
If any other action item is in your mind then please let me know. 

cc @zone117x

**Comment by pablojorge** [comment]
Hi @noumanahmads, thanks for taking a look. The problem is precisely that `if`.

The library used to verify the signature expects the components to be in this order: `v, r, s`. Look at the deserialization of a recoverable signature here: [blockstack/stacks.js/[...]/src/keys.ts#L175-L188](https://github.com/blockstack/stacks.js/blob/7a70542f96ec0d76645cf8988261701673c5abc5/packages/transactions/src/keys.ts#L175-L188), which is invoked from: https://github.com/blockstack/stacks-blockchain-api/blob/268712bb05a075650ff9bc6b9a132ba8e549608a/src/rosetta-helpers.ts#L427

A Rosetta-compliant client will send the components in the following order: `r, s, v`, since that's what the specification states for the [`ecdsa_recovery` signature type](https://github.com/coinbase/rosetta-specifications#supported-signaturetypes), and in fact it's the common order used in general (see for example [Bitcoin's secp256k1 lib](https://github.com/bitcoin-core/secp256k1/blob/07aa4c70ffb96d21e496854f823c3ea3353b9086/src/modules/recovery/main_impl.h#L27-L36), or [ethereumj](https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/crypto/ECKey.java#L699-L708)).

So what that `if` is doing, is taking a signature that was serialized in that 'standard' order, and moving `v` to the beginning, but _only_ when it is `01`, where there are in fact 4 possible values (see https://bitcoin.stackexchange.com/a/38909)
This means that in the other 3 cases, the signature verification will fail.

Given that no matter what the value of `v` is, since clients will always send it at the **end** but `parseRecoverableSignature()` expects it at the **beginning**, the Rosetta API should always move the last byte to the beginning, regardless of its value, like this:

```diff
diff --git a/src/api/routes/rosetta/construction.ts b/src/api/routes/rosetta/construction.ts
index b253340..3a380b9 100644
--- a/src/api/routes/rosetta/construction.ts
+++ b/src/api/routes/rosetta/construction.ts
@@ -525,10 +536,7 @@ export function createRosettaConstructionRouter(db: DataStore, chainId: ChainID)
        * the signature to match the elipcitc library
        * Discussion here: https://github.com/coinbase/rosetta-sdk-go/issues/201
        */
-      let hash = signatures[0].hex_bytes;
-      if (!hash.startsWith('01') && hash.slice(128) == '01') {
-        hash = signatures[0].hex_bytes.slice(128) + signatures[0].hex_bytes.slice(0, -2);
-      }
+      let hash = signatures[0].hex_bytes.slice(128) + signatures[0].hex_bytes.slice(0, -2);
       newSignature = createMessageSignature(hash);
     } catch (error) {
       res.status(400).json(RosettaErrors.invalidSignature);
```

The other option would be to update `parseRecoverableSignature()`, but I guess that's not feasible for backwards compability.

**Comment by zone117x** [comment]
Fixed by https://github.com/blockstack/stacks-blockchain-api/pull/463
