### ISSUE TITLE
Coinbase tx errors if it contains unlocking events

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#446]
Example: https://stacks-node-api.stacks.co/extended/v1/tx/0xdef44d1ce688bcbb57541a3d754b85b9fe341343b4c91766fe9effb50e7de27c

```json
{"error":"Error: Events exist for unexpected tx type_id: 4","stack":"Error: Events exist for unexpected tx type_id: 4\n    at Object.getTxFromDataStore (/app/lib/api/controllers/db-controller.js:484:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /app/lib/api/routes/tx.js:151:25\n    at async wrappedMiddleware (/app/node_modules/@awaitjs/express/index.js:112:7)","errorTag":"1c889b65-ce71-4e4a-836b-c0ca7edf2b44"}
```

**Comment by GinaAbrams** [comment]
I am still getting inquiries about these. What is the timeline for a fix?

**Comment by diwakergupta** [comment]
> I am still getting inquiries about these. What is the timeline for a fix?

@GinaAbrams it's already fixed. See the example Thomas posted earlier: https://stacks-node-api.stacks.co/extended/v1/tx/0xdef44d1ce688bcbb57541a3d754b85b9fe341343b4c91766fe9effb50e7de27c

**Comment by aulneau** [comment]
I will make some issues in the explorer repo to account for this new data and displaying it in a better way.
