### ISSUE TITLE
Faucet for stacking returns 500STX, not the minimum for stacking

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#451]
I'm running this command:
```
curl -X POST https://stacks-node-api.testnet.stacks.co/extended/v1/faucets/stx?address=STXJ7XT7T944MW302S3P6FM7ATEWE8D7Z3S8PYMY&stacking=true
```

Which creates a transaction like this: https://explorer.stacks.co/txid/0x01f0cc34923a9a30b277c435c899c8666077e0078ca0a6734f9b1a303abeb9b1?chain=testnet. It sends only 500STX. When I call the v2/pox endpoint to get the minimum on testnet, I get 

```
"min_amount_ustx": 85443257183791
```

Is there something wrong with the stacking faucet execution path @zone117x ?

**Comment by zone117x** [comment]
@agraebe it could be the shell version you're using is treating the ending query params as special tokens -- I think someone else reported that a while back.
Can you try this alternative curl syntax for sending the params as post data? 
```
curl -L -X POST -d address=STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP -d stacking=true https://stacks-node-api.testnet.stacks.co/extended/v1/faucets/stx
```

Seems to be working for me https://explorer.stacks.co/txid/0x4d8cf3dbfc81527a508edea2e562d253bfbf5a38f48981bb4be59633f10b5517?chain=testnet

**Comment by agraebe** [comment]
you were correct, this was related to my shell!
