### ISSUE TITLE
Total Supply Compatibility Endpoint

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain-api#455]
The Stacks 1.0 explorer API had an endpoint:

https://explorer-api.legacy.blockstack.org/api/v2/total-supply

which returned data like:

```json
{
  "unlockedPercent": "71.99",
  "totalStacks": "1352464600.000000",
  "totalStacksFormatted": "1,352,464,600.000000",
  "unlockedSupply": "973705260.219817",
  "unlockedSupplyFormatted": "973,705,260.219817",
  "blockHeight": "665746"
}
```

We should provide a similar API for Stacks 2.0, and I think the API already has enough data to compute this (basically, I think you need the `total_liquid_supply` field from the `v2/pox` endpoint, and then the locking data).

**Comment by fluidvoice** [comment]
+1  I'm guessing this is why the supply and market cap data on Coingecko.com is wrong.  

![Screenshot_2021-02-23_11-04-51](https://user-images.githubusercontent.com/373038/108855060-516d6e80-75c7-11eb-8627-6c6744453354.png)

**Comment by louiseivan** [comment]
@fluidvoice thanks Brad! Already in touch with the Coingecko team about it.

**Comment by louiseivan** [comment]
Can we re-open this issue, coingecko is already fixed while CMC is asking for two separate endpoints for the total supply and circulating supply in this exact format? [](http://chainz.cryptoid.info/grs/api.dws?q=totalcoins)

Totaly Supply = totalStacks
Circulating Supply = unlockedSupply
