### ISSUE TITLE
Bitcoin block hash in API? 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-blockchain-api#456]
Question and potential feature request, does the Blockchain API expose bitcoin block hash info for developers to use in apps? I see it in the [explorer](https://explorer.stacks.co/txid/0xc0b2e2ad7b5b21e2510687544ee72b66d5aa39a33a4fc001ece7a1b5c4800319?chain=mainnet) but am not seeing it as a category in [the API](https://blockstack.github.io/stacks-blockchain-api/#operation/get_transaction_by_id). 

cc @zone117x @aulneau 🙏

**Comment by zone117x** [comment]
Hi @GinaAbrams, the bitcoin data is associated with the block, see here: https://blockstack.github.io/stacks-blockchain-api/#operation/get_block_by_hash
The property names starting with `burn_block` are bitcoin data. The explorer appears to be looking up the transaction's block to render that page.

**Comment by GinaAbrams** [comment]
Super helpful! Thanks Matt!
