### ISSUE TITLE
Transaction not pruned from mempool after confirmation

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-blockchain-api#458]
Some transactions are not being cleared from the mempool endpoint after being confirmed. For example:

Confirmed tx:
https://stacks-node-api.stacks.co/extended/v1/tx/0xf821ec368831a421659ffd08bf8d2141591faa6838837ea1cf75b95f2ed649b7

Mempool:
https://stacks-node-api.stacks.co/extended/v1/tx/mempool?address=SP1NCG226XTNTTW0H34735VW446WR8AEYCY8Z3YBA

**Expected behavior**
The mempool endpoint should not return this transaction once it has been confirmed.

**Comment by yknl** [comment]
It looks like this problem still occurs.

Here's a recent transaction that appears both as confirmed and in the mempool:

https://stacks-node-api.stacks.co/extended/v1/tx/mempool?address=SP9SMX319J9CHQ14RSH5MR8NEHWGXJFZ35MAXCFJ

https://explorer.stacks.co/txid/0xd161b6e639a4b78e5118939ab026077d116c319f64e6175c1a7a91833170c4a7?chain=mainnet

**Comment by zone117x** [comment]
The stacks-node PR https://github.com/blockstack/stacks-blockchain/pull/2479 hasn't yet made it into a release. The API-side related changes won't have any effect until it does.
