### ISSUE TITLE
Account Assets API does not return total

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain-api#459]
**Describe the bug**
The account asset api always return total "0".  I've tried different combinations and the total never reflects what I assume should be the total number of items in the select.

**To Reproduce**
1. Go to https://stacks-node-api.testnet.stacks.co/extended/v1/address/STQTK2AMC92ZN0ZWTMB6N53E4QF6CNH98QZTF8BN/assets?limit=50&offset=17

As of this writing there are 59 assets returned by the API, but total always says 0.

**Expected behavior**
Return the total size of the query

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 84

**Comment by asimm241** [comment]
I am looking into this issue.
