### ISSUE TITLE
[PoX] wrong minimum shown

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#461]
**Describe the bug**
There are two minimum values relevant for pox:
1. the minimum to start stacking
2. the minimum to get at least one slot

The `v2/pox` endpoint shows a different one then the stacks node endpoint

https://stacks-node-api.blockstack.org/v2/pox
http://seed-0.mainnet.stacks.co:20443/v2/pox

It looks like the value [was overwritten](https://github.com/blockstack/stacks-blockchain-api/commit/be27f04625d2215c65256d648dc8ffa8a7f3750f) to reduce confusion among stackers. The confusion is now on the developers. :-/

**Comment by zone117x** [comment]
Last I checked I don't think we can get rid of the monkey patch just yet. Once the /v2/pox overhaul PR is merged in this should be resolved https://github.com/blockstack/stacks-blockchain/pull/2459
Existing issue tracking this update: https://github.com/blockstack/stacks-blockchain-api/issues/453

**Comment by friedger** [comment]
Thank you for the clarification.
