### ISSUE TITLE
Liquid STX discrepancy between sql db and /v2/pox

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#468]
Note that I'm seeing a liquid STX discrepancy of ~11 when comparing the sql query result to the `total_liquid_supply_ustx` value at https://stacks-node-api.mainnet.stacks.co/v2/pox.

The v2/pox endpoint shows `1047801298.354442` while the sql query shows `1047801309.687772`. An ~11 STX difference is a really strange amount -- the kinds of bugs that I'm thinking could cause a discrepancy would result in a much higher amount.

@kantai any ideas what this could be?

The sql query to retrieve the liquid supply is really simple: sum all STX mint amounts, sum all coinbase reward amounts:
```sql
SELECT SUM(amount) FROM (
  SELECT SUM(amount) amount
  FROM stx_events
  WHERE canonical = true
  AND asset_event_type_id = 2 -- mint events
  UNION ALL
  SELECT SUM(coinbase_amount) amount
  FROM miner_rewards
  WHERE canonical = true
) totals
```

_Originally posted by @zone117x in https://github.com/blockstack/stacks-blockchain-api/issues/466#issuecomment-786610898_

**Comment by agraebe** [comment]
pinging @kantai to move this conversation along :)

**Comment by kantai** [comment]
Hmm -- I'm not sure where this discrepancy could be coming from. I think to figure this out will require some debugging and analysis. If we can do something like compute and compare these values by block height, that may help to figure out where the difference is coming from.

**Comment by kantai** [comment]
After looking more into this, I think this query needs to account for STX burn events (from the BNS contract for example):

https://explorer.stacks.co/txid/0xdaafe4f0df756809a5b4df87ffdda362b67bc607a8903e598a71e1a1438c69ae?chain=mainnet
