### ISSUE TITLE
Stop-gap endpoint to provide correct, dynamic Stacking threshold

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain-api#474]
We need a stop-gap solution until blockstack/stacks-blockchain#2459 is merged and deployed.

@kantai suggested a client could:
1. Figure out the "next" reward cycle -- this is a simple calculation based on the bitcoin block height
2. Once the reward cycle number is known, they can query `(get-total-ustx-stacked ..)` with the reward cycle number
3. Compute the threshold from that (which is also just math)

> So there'd be 2 required lookups -- one is the bitcoin height, and the other is a read-only function call
> it would also let us cache this response (One Day) because it only changes after a block is processed

FYI @kyranjamie @GinaAbrams

**Comment by zone117x** [comment]
@kyranjamie suggestions for API shape?

**Comment by kyranjamie** [comment]
@zone117x  For the time being, can we continue down the monkey-patch route of the `/v2/pox` endpoint, so no API changes are needed?

**Comment by GinaAbrams** [comment]
Hey all checking in on this, has it been updated yet?

**Comment by agraebe** [comment]
am I assuming correctly that with https://github.com/blockstack/stacks-blockchain/pull/2459 being merged, this issue can be closed? the API update is not yet rolled out it looks like (just tested)

**Comment by zone117x** [comment]
The stacks-node release candidate has this fixed. The API should remove the `/v2/pox` override code here: 
https://github.com/blockstack/stacks-blockchain-api/blob/b6fcf1fc6696d6ab97193018d0a619d0ca4e4a5b/src/api/routes/core-node-rpc-proxy.ts#L28-L35

In the meantime, the env var `"V2_POX_MIN_AMOUNT_USTX"` should be left unspecified in new deployments using the current stacks-node RC, and the API will perform the override. cc @CharlieC3
