### ISSUE TITLE
[Rosetta] Improvements in /construction/payloads and submit

### ISSUE THREAD

**Issue by pablojorge** [blockstack/stacks-blockchain-api#482]
In https://github.com/blockstack/stacks-blockchain-api/commit/cade138987df5ffe77d683c0392900925f07a161, the `/construction/derive` endpoint was updated to return the address inside the `account_identifier` container, since the top-level `address` field in the `ConstructionDeriveResponse` is deprecated. However, the `/construction/payloads` still uses the top-level `address` field instead of `account_identifier`. It should look like this instead:

```diff
@@ -467,11 +467,15 @@ export function createRosettaConstructionRouter(db: DataStore, chainId: ChainID)

     const prehash = makeSigHashPreSign(signer.sigHash, AuthType.Standard, new BN(fees), nonce);

+    const accountIdentifier: RosettaAccountIdentifier = {
+      address: senderAddress,
+    };
     const response: RosettaConstructionPayloadResponse = {
       unsigned_transaction: '0x' + unsignedTransaction.toString('hex'),
       payloads: [
         {
           address: senderAddress,
+          account_identifier: accountIdentifier,
           hex_bytes: prehash,
           signature_type: 'ecdsa_recovery',
         },
```

Also in `/construction/payloads` the `0x` prefix of the public key is NOT removed, this is missing:
```diff
@@ -449,6 +453,9 @@ export function createRosettaConstructionRouter(db: DataStore, chainId: ChainID)
         res.status(400).json(RosettaErrors[RosettaErrorsTypes.invalidCurveType]);
         return;
       }
+      if (has0xPrefix(publicKeys[0].hex_bytes)) {
+        publicKeys[0].hex_bytes = publicKeys[0].hex_bytes.slice(2);
+      }
       // signel signature
       tokenTransferOptions = {
         recipient: recipientAddress,
```

Finally, in `/construction/submit`, the error response does NOT include any reference to the original error reported by the node, and this is super useful to determine the cause (bad nonce? not enough funds?). On my tests, I'm just appending the error string to the description, but the best approach would be the make use of the `details` container.

**Comment by zone117x** [comment]
cc @rllola

**Comment by rllola** [comment]
Preparing a PR to fix this.

**Comment by rllola** [comment]
Regarding the error in submit. I can hqve something like this using details without having too much changes.

```
    {
      code: 628,
      message: 'Invalid transaction string',
      retriable: false,
      details: 'Response 400: Bad Request fetching http://127.0.0.1:20443/v2/transactions - {"error":"transaction rejected","reason":"SignatureValidation","reason_data":{"message":"Invalid signature: failed to recover public key"},"txid":"7d60e525a0e213b5b81f39a120517e878b24c836dde339e7e9af99e40af6701f"}'
    }
```
It would be possible in `details` to return an object like this `{"error":"transaction rejected","reason":"SignatureValidation","reason_data":{"message":"Invalid signature: failed to recover public key"},"txid":"7d60e525a0e213b5b81f39a120517e878b24c836dde339e7e9af99e40af6701f"}` forwarding the node error. It required to modify this line : https://github.com/blockstack/stacks-blockchain-api/blob/master/src/core-rpc/client.ts#L123

Might be breaking so it could be a low priority issue.

**Comment by pablojorge** [comment]
> I am actually confused about the `0x` prefix on the public keys. Aren't they supposed to match the specific model defined by the `curve_type` field ? See https://www.rosetta-api.org/docs/models/PublicKey.html and see https://www.rosetta-api.org/docs/models/CurveType.html
> 
> Should we have a `validatePublicKey` function somewhere that take the `curve_type` field and ensure it match the spec ? It would avoid `if` branch.
> 
> I am going to integrate this change though. Just an improvement proposition.

Keep in mind this doesn't affect the type field, but the "data" one (`hex_bytes`). In fact, a similar fix is already applied in 3 other endpoints:

`/derive:` https://github.com/blockstack/stacks-blockchain-api/blob/b7d3d5addf1eb12c555342e92dc19128886daba9/src/api/routes/rosetta/construction.ts#L85-L87
`/metadata`: https://github.com/blockstack/stacks-blockchain-api/blob/b7d3d5addf1eb12c555342e92dc19128886daba9/src/api/routes/rosetta/construction.ts#L217-L219
`/combine`: https://github.com/blockstack/stacks-blockchain-api/blob/b7d3d5addf1eb12c555342e92dc19128886daba9/src/api/routes/rosetta/construction.ts#L542-L544

**Comment by pablojorge** [comment]
> Regarding the error in submit. I can hqve something like this using details without having too much changes.
> 
> ```
>     {
>       code: 628,
>       message: 'Invalid transaction string',
>       retriable: false,
>       details: 'Response 400: Bad Request fetching http://127.0.0.1:20443/v2/transactions - {"error":"transaction rejected","reason":"SignatureValidation","reason_data":{"message":"Invalid signature: failed to recover public key"},"txid":"7d60e525a0e213b5b81f39a120517e878b24c836dde339e7e9af99e40af6701f"}'
>     }
> ```
> 
> It would be possible in `details` to return an object like this `{"error":"transaction rejected","reason":"SignatureValidation","reason_data":{"message":"Invalid signature: failed to recover public key"},"txid":"7d60e525a0e213b5b81f39a120517e878b24c836dde339e7e9af99e40af6701f"}` forwarding the node error. It required to modify this line : https://github.com/blockstack/stacks-blockchain-api/blob/master/src/core-rpc/client.ts#L123
> 
> Might be breaking so it could be a low priority issue.

This is fine, even if it's not a representation of the original object, it helps to have a hint of what's happening. A slight improvement could be to wrap the message in an object, so if in the future you switch to a richer response, it'll just look like new fields were added, instead of a switch from string to object. Something like this: 
```
{
    code: 628,
    message: 'Invalid transaction string',
    retriable: false,
    details: {
        message: 'Response 400: Bad Request fetching http://127.0.0.1:20443/v2/transactions - {"error":"transaction rejected","reason":"SignatureValidation","reason_data":{"message":"Invalid signature: failed to recover public key"},"txid":"7d60e525a0e213b5b81f39a120517e878b24c836dde339e7e9af99e40af6701f"}'
    }
}
```

Thanks for taking a look!!!

**Comment by rllola** [comment]
> This is fine, even if it's not a representation of the original object, it helps to have a hint of what's happening. A slight improvement could be to wrap the message in an object, so if in the future you switch to a richer response, it'll just look like new fields were added, instead of a switch from string to object.

Excellent idea. Finalizing the PR.
