### ISSUE TITLE
FT Transfer updating balances despite failed TX

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain-api#498]
[Failed transaction](https://explorer.stacks.co/txid/0xbeb7e6b9a844002764ea52f9cce209e7dda03a271c070fa2da1c01a6a4248e3a?chain=testnet) with `ft-transfer` event

[Recipient of tx - explorer page](https://explorer.stacks.co/address/ST21T5JFBQQPYQNQJRKYYJGQHW4A12G5ENBBA9WS7?chain=testnet) shows a balance of "Tokensoft token" that should be zero, but is not. Also reflected in the [balances API response](https://stacks-node-api.testnet.stacks.co/extended/v1/address/ST21T5JFBQQPYQNQJRKYYJGQHW4A12G5ENBBA9WS7/balances)

But if you query the contract (i.e. via the sandbox) for the balance of this user, the balance is (correctly) zero

https://user-images.githubusercontent.com/1109058/111230388-cae3f580-85a4-11eb-830e-2a1537ff8f53.mp4

**Comment by zone117x** [comment]
I think testnet might be running the API version before this was fixed. @CharlieC3 can you confirm?
@hstove do you see this anywhere in mainnet?

**Comment by CharlieC3** [comment]
Confirmed, API running in testnet is `0.52.3`. I can update this today in testnet.

**Comment by hstove** [comment]
Ah, beautiful, good to know. Closing this
