### ISSUE TITLE
Test restart w/ existing data behavior

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#500]
Currently, if either the API or stacks-node need restarted, the workflow is:
* Shutdown both the stacks-node and API.
* Wipe the postgres DB.
* Wipe the stacks-node working_dir.

This was required because both the API and stacks-node must initialize at the same block height, and historically the stacks-node could not reliably restart with a persistent working directory. The API is also unable to re-process events from the stacks-node without the re-org detection code causing issues.

The stacks-node is now able to shutdown and restart gracefully with a persistent working_dir. In theory, it should now be possible to gracefully restart either the stacks-node or the API. Both of these scenarios need tested to ensure:
* Events are not de-synced by either getting lost during a restart, or re-played during a restart.
* HTTP server co-dependencies between the two services don't choke up during a restart.

**Comment by zone117x** [comment]
Updates:
* The stacks-node-api process can be successfully restarted while the stacks-node is running. This PR fixes a race-condition that can happen during restart: https://github.com/blockstack/stacks-blockchain-api/pull/522.
* When the stacks-node does not run into issues https://github.com/blockstack/stacks-blockchain/issues/2545 or https://github.com/blockstack/stacks-blockchain/issues/2546, it is also able to restart successfully while the stacks-node-api is running.

The BNS PR https://github.com/blockstack/stacks-blockchain-api/pull/483 will break the stacks-node-api restart due to https://github.com/blockstack/stacks-blockchain-api/issues/504. We should try to fix https://github.com/blockstack/stacks-blockchain-api/issues/504 before merging BNS as it can now be considered a significant regression.

**Comment by agraebe** [comment]
seems to be a deployment documentation task. can @blockstack/devops help?

**Comment by zone117x** [comment]
The last known issue is regarding the stacks-node restart behavior described here https://github.com/blockstack/stacks-blockchain/issues/2575
The API currently does everything it can to facilitate a graceful restart. Closing this issue.
