### ISSUE TITLE
[Rosetta] Include "suggested_fee" in the /construction/metadata response

### ISSUE THREAD

**Issue by pablojorge** [blockstack/stacks-blockchain-api#505]
Currently, to estimate the fee to be used in a transfer, we're using the `/construction/preprocess` + `/construction/metadata` + `/construction/payloads` to obtain an unsigned transaction, and multiply its size by the output of the https://blockstack.github.io/stacks-blockchain-api/#operation/get_fee_transfer operation.

This is not ideal since we need to use a custom endpoint instead of relying only on Rosetta endpoints. The specification includes an _optional_ `suggested_fee` field in the metadata response (https://www.rosetta-api.org/docs/models/ConstructionMetadataResponse.html), but the Stacks Rosetta implementation returns a null value.

Ideally, the metadata response includes the `suggested_fee` field, clients can use that and skip calling custom endpoints, relying only on Rosetta operations.

**Comment by zone117x** [comment]
Thanks for the suggestion @pablojorge!
@rllola is this something you can take on?

**Comment by rllola** [comment]
Currently implementing it.

**Comment by rllola** [comment]
@pablojorge 
The PR is here. However there is a breaking change. It is now not allow to have a `fee` operation in the operations array. It is to avoid confusion.

I hope it works for you.

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/528

**Comment by pablojorge** [comment]
> @pablojorge
> The PR is here. However there is a breaking change. It is now not allow to have a `fee` operation in the operations array. It is to avoid confusion.
> 
> I hope it works for you.

Thanks @rllola, I could only test these changes today. They work fine, I refactored how to send the fee back to the API.

There's one issue, though. `suggested_fee` should be an _array_ of values (https://www.rosetta-api.org/docs/models/ConstructionMetadataResponse.html). I think it was already declared wrongly:

https://github.com/blockstack/stacks-blockchain-api/blob/master/docs/api/rosetta/rosetta-construction-metadata-response.schema.json#L21-L23

I can't test the change easily because it requires re-packaging `@blockstack/stacks-blockchain-api-types`.

Can you update the definition and the response to return an array instead?

**Comment by rllola** [comment]
Just to let you know that we have a PR for this : https://github.com/Zondax/stacks-blockchain-api/pull/50

It has been internally reviewed. We are waiting for it to be merge upstream once higher priority changes have been merged.

**Comment by pablojorge** [comment]
Great news, thanks! I see you're also bringing back the fee operation 👍

I'll keep an eye on that PR
