### ISSUE TITLE
Streamline clarity value results

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#506]
All endpoints that return a clarity value should use the same type.

#494 introduces uses `value` of type `string` and `value_repr`. Most of the other endpoints return `value` as `{hex: string, repr: string}`. Some endpoints have additional properties `name` or `type`.

Example: 
https://stacks-node-api.blockstack.org/extended/v1/tx/0xa7058b911cb8fdf5c50468096abf867f5209f526fcda1e3d4742a9d21853b781

![Screenshot from 2021-03-18 09-21-02](https://user-images.githubusercontent.com/1449049/111594381-47f0b400-87cb-11eb-8b11-eb2079d75caa.png)

![Screenshot from 2021-03-18 09-21-17](https://user-images.githubusercontent.com/1449049/111594426-576ffd00-87cb-11eb-8b0d-9e708cf8a79d.png)

**Comment by agraebe** [comment]
is there something left that was not covered by the referenced PR @friedger ?

**Comment by friedger** [comment]
Closed by #507. I'll open a new one if I find more.
