### ISSUE TITLE
BNS: investigate name not being updated

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain-api#511]
Investigate https://stacks-node-api-bns.testnet.stacks.co/v1/names/test-registrar, and its zone file hash has not being updated.

1 transaction for registering the name (with a bad zonefile hash + inexistant zonefile) correctly executed and reported here https://explorer.stacks.co/txid/0x5c7b996dd5fb0d25059f54f87443b86756eccfbef69a115c5243d24cea7ab784?chain=testnet

1 transaction for updating the name with a correct zonefile hash + zonefile, correctly executed and reported here https://explorer.stacks.co/txid/0x7736435f2bab9a1910e7c3aab459db95712048e0ba1bd727fa8aa64c90b946d6?chain=testnet

**Comment by asimm241** [comment]
There are two bugs that I found
1) `names` table is not being updated correctly,
This is how it is doing
 
`name: attachment.attachment.metadata.name,
namespace_id: unresolvedSubdomain.result.namespace_id`

It should be doing this. 
 
`name: attachment.attachment.metadata.name.concat(
                  '.',
                  attachment.attachment.metadata.namespace
                ),
namespace_id: unresolvedSubdomain.result.namespace_id`

2) for `name-update`,  It does not update `names` tables at all, and if there is no subdomain information found in the zone file It ignores it completely where it should update the zone file in the `names` table for both cases.
cc: @lgalabru @zone117x
