### ISSUE TITLE
Expose locking / unlocking data

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#515]
The explorer is currently using 2 sets of data for displaying locking data related to addresses that have some amount of locking still in place. There is a static data [export found here](https://github.com/blockstack/explorer/blob/main/src/pages/api/vesting/lockups.json), and the explorer is also relying on a [legacy endpoint](https://github.com/blockstack/explorer/blob/main/src/common/utils/addresses.ts#L230) from the 1.0 explorer API to get a single piece of data: the total amount locked for a given address. 

Ideally we'd be able to include this data in the new API so that we can remove any dependencies on the legacy explorer.

Questions:
- Do we want to include this static unlocking schedule data in this api when an address is queried that has locked tokens?
- Do we want to include the total original amount locked? An alternative would be for the explorer to handle static data (via an exported JSON file, etc) like it currently is for the unlocking schedule.

**Comment by aulneau** [comment]
@agraebe following up on this -- curious if this can be prioritized on the platform teams schedule?

**Comment by zone117x** [comment]
The wiring for importing this Stacks v1 data is now available in the develop branch, we can start work on this 👍

**Comment by zone117x** [comment]
Some context on this issue:

There are a set of addresses that come from Stacks 1.0 that have a STX vesting/unlocking schedule. At set block heights, the stacks-node will credit STX to these address. The stacks-node emits `stx-mint` events when this happens, however, there's no way to determine the full locked balance for these addresses from the stacks-node.

NOTE: these locked balances are completely different than STX balances that are locked when participating in stacking.

This data _is_ available in the `chainstate.txt` file, which is already being used for importing BNS data from Stacks 1.0, see here: https://github.com/blockstack/stacks-blockchain-api/blob/6a2c99c284ace5c58874fb9a03cdbc4c5c59c3bf/src/import-v1/index.ts#L361-L364

The chainstate.txt file can be found here https://storage.googleapis.com/blockstack-v1-migration-data/export-data.tar.gz

The locked STX data is in the `-----BEGIN STX VESTING-----` section, and looks like this:
```
-----BEGIN STX VESTING-----
address,value,blocks
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,33477
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,29157
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,24837
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,20517
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,16197
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,11877
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,7557
112XwWYtXmVGhwKPZAijeDDxeiQzAhvyDi,4139394444,3237
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,33477
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,29157
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,24837
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,20517
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,16197
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,11877
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,7557
113E1TwrMfBNBitk4oa4uDP4u7ePZynY3Y,2403337500,3237
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,33477
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,29157
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,24837
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,20517
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,16197
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,11877
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,7557
113bkUpVynUBcEBQBFnMmkLoBze1Ce9KMD,694079166,3237
...
```


Each lines is an address, followed by a microSTX amount, followed by the block height at which the address will receive the STX.

The Stacks Explorer front-end currently uses it's own dataset derived from the chainstate.txt file to show this information, for example, see "View schedule" here https://explorer.stacks.co/address/SP04MFJ3RWTADV6ZWTWD68DBZ14EJSDXT50Q7TE6?chain=mainnet
![image](https://user-images.githubusercontent.com/1447546/114170865-d2908300-9933-11eb-8a12-8d67015e282c.png)


The API needs to parse these from the `chainstate.txt` file in the `v1-import` module and insert them into a new table. Then, the unlock schedule and total locked amount should be added to the address endpoints `/extended/v1/address/:stx_address/stx` and `/extended/v1/address/:stx_address/balances`. 
Keep in mind, this is different than the stacking-locked value, which is already using the property name `locked` in the balance response object. I think we need to come up with a new property name, like `token_offering_locked`. So the balance response would include something like:
```ts
interface AddressStxBalanceResponse {
  token_offering_locked: {
    total_locked: string; // string-quoted integer like "10000"
    unlock_schedule: Array<{
      amount: string; // string-quoted integer
      block_height: number;
    }>
  }
}
```
