### ISSUE TITLE
Mocknet mode for blockstack/stacks-blockchain-api-standalone Docker image chain ID issue

### ISSUE THREAD

**Issue by MarvinJanssen** [blockstack/stacks-blockchain-api#523]
**Describe the bug**
Running the `blockstack/stacks-blockchain-api-standalone` Docker image in mocknet mode results in the following:

```
{"level":"error","message":"The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648 The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648","stack":"Error: The configured STACKS_CHAIN_ID does not match the node's: 1 vs 2147483648\n    at init (/home/stacky/stacks-blockchain-api/lib/index.js:71:23)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2021-03-25T20:19:44.858Z"}
```

It also proceeds to spam the console with (appears unrelated):

```
Event dispatcher: connection failed  - Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
```

**To Reproduce**
1. `docker run -p 3999:20443 blockstack/stacks-blockchain-api-standalone mocknet`

**Expected behavior**
Defaulting to the proper chain ID.

**Desktop (please complete the following information):**
- Apple M1 device running macOS Big Sur.

**Additional context**
Workaround:

```
docker run -p 3999:20443 -e STACKS_CHAIN_ID=1 blockstack/stacks-blockchain-api-standalone mocknet
```

**Comment by agraebe** [comment]
this seems to be a bug - would you be able to create a PR based on your workaround?
