### ISSUE TITLE
Mocknet conf. in blockstack/stacks-blockchain-api-standalone no longer contains private keys

### ISSUE THREAD

**Issue by MarvinJanssen** [blockstack/stacks-blockchain-api#524]
## Describe the bug

`Stacks-mocknet.toml` used to contain the private keys of the test addresses seeded with STX as comments. This is no longer the case. It would be nice for (new) developers if they are added back.

```
$ cat Stacks-mocknet.toml
[node]
name = "helium-node"
rpc_bind = "0.0.0.0:20443"
#working_dir = "/tmp/stacks-blockchain-data"

[burnchain]
chain = "bitcoin"
mode = "mocknet"
commit_anchor_block_within = 10000

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000

[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000

[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000
```

**Comment by zone117x** [comment]
These can be found here https://github.com/blockstack/stacks-blockchain-api/blob/b6fcf1fc6696d6ab97193018d0a619d0ca4e4a5b/src/api/routes/debug.ts#L42-L55

**Comment by MarvinJanssen** [comment]
@agraebe yes this is just a quality of life thing for developers. Other toml files include(d) the private keys so it is nice if everything is in one spot.
