### ISSUE TITLE
Testnet Faucet is unusable

### ISSUE THREAD

**Issue by iamgenchi** [blockstack/stacks-blockchain-api#527]
**Describe the bug**
Faucet is unusable

**To Reproduce**
1. Post to `https://stacks-node-api.testnet.stacks.co/extended/v1/faucets/stx?address=YOUR_ADDRESS&stacking=true` 

```
{
    "error": "Error: Response 400: Bad Request fetching http://stacks-node-follower-blue.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"TooMuchChaining\",\"reason_data\":{\"actual\":1706,\"expected\":1705,\"is_origin\":true,\"message\":\"Nonce would exceed chaining limit in mempool\",\"principal\":\"STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6\"},\"txid\":\"b59843a67e4709cb71331c18b03ccec58994c84f2a840278749c2567385fd0fa\"}",
    "stack": "Error: Response 400: Bad Request fetching http://stacks-node-follower-blue.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"TooMuchChaining\",\"reason_data\":{\"actual\":1706,\"expected\":1705,\"is_origin\":true,\"message\":\"Nonce would exceed chaining limit in mempool\",\"principal\":\"STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6\"},\"txid\":\"b59843a67e4709cb71331c18b03ccec58994c84f2a840278749c2567385fd0fa\"}\n    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:72:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:51:30)\n    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:107:24)\n    at async /app/lib/api/routes/faucets.js:186:37\n    at async run (/app/node_modules/p-queue/dist/index.js:159:29)",
    "errorTag": "95686345-e082-4fd4-b407-df1fe1cb19be"
}
```

Doing from the explorer does the same thing:

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/81058044/112771581-3a171a80-9078-11eb-8cf2-1c324ac02ae1.png">

**Comment by iamgenchi** [comment]
@zone117x @kyranjamie @shea256 @muneeb-ali @lgalabru @larrysalibra @kyranjamie 

Is there anyone maintaining Blockstack repos?

Do you need help from the community? SPEAK UP! You have a very good ecosystem but lack of handling direct developers and users feedback is a great concern.

There are many things that are frustrating for Stacks developers:
- Testnet Faucets are not working
- Most documentation is not up-to-date with the changes that have been made in production
- [Stacks-Local-Dev ](https://github.com/blockstack/stacks-local-dev)block explorer doesn't work well. Connecting your wallet is not working

There are many things that are frustrating for Stack users:
- Social Identity confirmations are not working on Blockstack and API calls fail (/profiles twitter handle verification)
- Blockstack login don't work and API calls fail for most of our DApps
- Most DApps shown in our page end up with 404s (we should remove them)
- GAIA is incredibly slow, all Dapps using GAIA as a storage engine have response time of 5 to 10 seconds, this makes most DApps based on Gaia impossible to use

Issues have been raised for all of this but no one is responsive.

I think we need to come up with a way of making this stuff work. If we don't have someone looking at the backlog of issues, we cannot make this successful. 

So what is the strategy to make things better, and do you need help from the community? Just SPEAK UP.

**Comment by zone117x** [comment]
Hi @iamgenchi, the testnet hasn't been usable for several days due to a slow syncing issue. It's being worked on, the #stacks-testnet or #stacks-core-devs channels on Discord.

Perhaps you can raise these concerns on Discord or the forums?

https://community.stacks.org/discord

https://forum.stacks.org/

**Comment by larrysalibra** [comment]
@diwakergupta Can you share a link to the github issue where there is more information about the testnet problems? 🙏

**Comment by diwakergupta** [comment]
> @diwakergupta Can you share a link to the github issue where there is more information about the testnet problems? 🙏

"Testnet problems" is perhaps too vague. The specific issue we've been having on testnet is that syncing is too slow -- so if you spun up a new node, it would take prohibitively too long to sync. Any existing nodes that are not restarting are not impacted. The relevant issue is https://github.com/blockstack/stacks-blockchain/issues/2407.

Meanwhile, I will note the Hiro-operated testnet nodes did catch up around 10-12 hrs ago and the testnet has been operating just fine since then: http://status.test-blockstack.com/
