### ISSUE TITLE
[Rosetta] Creating a transaction required 2 operations to be defined

### ISSUE THREAD

**Issue by rllola** [blockstack/stacks-blockchain-api#529]
We can see that in order to create a transaction using the `/construction` endpoints, it currently require to define 2 operations : one with a positive amount and an opposite one with the same amount but negative.

See https://github.com/blockstack/stacks-blockchain-api/blob/master/src/tests-rosetta/api.ts#L1437-L1477

We could have only one and use `metadata` to define the recipient of the transaction. It would avoid repeating the same info.

**Comment by agraebe** [comment]
is this fixed with #528 ?

**Comment by rllola** [comment]
It actually doesn't fit with the Rosetta way as rosetta Construction api operations expect to be exactly the same as the operations shown on the Data api.

After a discussion with CB team it was decided that it should not be implemented to keep the current workflow intact.
