### ISSUE TITLE
Support 1.0 subdomains on `/v1/names/:fqn`

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain-api#534]
The `/v1/names/:subdomain` API works well for newly registered subdomains. However, it's not working for subdomains imported from 1.0. For example, this should resolve to a subdomain: https://stacks-node-api.testnet.stacks.co/v1/names/hank_testing_add_username.id.blockstack

We need support for these imported subdomains in order to restore app functionality. If there are other workarounds to fetch the same kind of data, LMK!

**Comment by noumanahmads** [comment]
@hstove 
I have checked some subdomains from the imported data.  For example

https://stacks-node-api.testnet.stacks.co/v1/names/alese.id.blockstack
https://stacks-node-api.testnet.stacks.co/v1/names/alb.id.blockstack
https://stacks-node-api.testnet.stacks.co/v1/names/dmc.id.blockstack


They are giving me the information using the API `v1/names/:subdomain` 
But I am unable to find the subdomain `hank_testing_add_username` in the data which we have imported for v1. 
Can you provide some more information about this `subdomain`?

cc @asimm241 @zone117x

**Comment by markmhx** [comment]
@asimm241 @zone117x poke ☝️

**Comment by agraebe** [comment]
we confirmed that the imports worked as expected. a few checks were completed with success. can close this for now. please open if there's anything else to discuss
