### ISSUE TITLE
CORS errors when accessing api

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain-api#540]
**Describe the bug**
Increased requests to the API from a client seem to be triggering CORS errors.

Requests can be reduced on the client for subsequent needs, once an initial download is done, but these are failing the first time we're trying to populate data.

**To Reproduce**
1. call a contract function on 300 assets, like get-meta on an nft.

**Expected behavior**
A more clear indication of the issue.  Is this rate limiting?  

**Screenshots**
![16734d5f79d1d2d1](https://user-images.githubusercontent.com/7738/113733846-ac5ab100-96af-11eb-98ad-d006ae7c2ddd.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows. Mac not tested.
 - Browser: Chrome, Brave
 - Version: 89.0.4389.95 (Official Build) (64-bit)

**Additional context**
The client shows in the screenshot is a pre-release build of Boom, from a user with 350+ NFTs.  We're downloading the NFT info and this error blocks the completion of data requests.

**Comment by diwakergupta** [comment]
@dantrevino to clarify, you only see CORS errors at higher request rates but not otherwise? Trying to understand whether you're actually hitting a CORS limitation (which should show up regardless of request volume) or a rate-limit error which is being propagated incorrectly as a CORS issue.

**Comment by dantrevino** [comment]
We're not seeing this with a low number of requests.  For instance, in my personal account, I have only 20, and never see this error on mainnet.

**Comment by aulneau** [comment]
Anecdotally, I've noticed similar errors or failures when fetching certain data from `/v2/` endpoints relating to values found in the pox contract, eg `get-total-ustx-stacked` sometimes returns broken. Previously stacking.club would query that value occasionally, but I have since removed dependency on it outside of an initial fetch due to the sporadic response issues. I have not personally seen if it was a CORS related issue, but I will keep a look out for it.

**Comment by zone117x** [comment]
I'm not quite sure what to make of this issue. @dantrevino and @aulneau both indicate issues with `/v2/` endpoints, implying some issue with CORS there. The this repo's proxy doesn't handle any rate limiting or CORs header injecting, so my assumption is something is wrong with either the stacks-node CORs handling or something in the deployment. Perhaps cloudflare or similar can be inspected to override and ensure proper CORs headers are specified? /cc @CharlieC3.

This repo has the ability to MTM `/v2/` proxied request and do things like header manipulation, so if needed I can add that, but in generally I think those are kludges that should be avoided.

**Comment by CharlieC3** [comment]
For paths `v2/contracts/call-read/SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ*`, Cloudflare is showing ~1000 requests resulting in a `499` (Client closed request), and ~300 requests resulting in a `502` (Bad Gateway) over the past 12 hours. Some thoughts below:

* It's possible the traffic was being routed through Nginx while one of our servers was restarting, but that would be extremely rare, and subsequent requests would be funneled through a different active Nginx server.
* We do have rate-limiting enabled for certain paths, but it would _not_ have been hit for `v2/contracts/call-read/SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ*`.
* CORS was not enabled during the time of these requests. I just enabled it about 10 minutes ago - @dantrevino can you give it another go?

**Comment by CharlieC3** [comment]
Also, it looks like the main error is the `404` near the top of the screenshot. I'm also getting a `404` when visiting that page:
https://release-0-0-5--quizzical-haibt-0eb096.netlify.app/__headers

Perhaps it's a legitimate error? And while the subsequent CORS errors do happen, they may not be the reason behind the uncaught exception.

**Comment by dantrevino** [comment]
the _headers file is a relic of the legacy stacks auth, where it required cors access on manifest.json to access that file remotely ... netlify uses that file.  Here are the contents:
```
/manifest.json
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Headers: "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
  Access-Control-Allow-Methods: "GET"
```

**Comment by aulneau** [comment]
> ~300 requests resulting in a 502 (Bad Gateway)

this is the error that stacking.club would get when calling `v2/contracts/call-read/SP000000000000000000002Q6VF78*`, and I fairly certain the errors would happen when nothing was changing as far as restarts were concerned (as far as I am able to tell). @CharlieC3 do you know what other issues could cause 502s?

**Comment by CharlieC3** [comment]
> the _headers file is a relic of the legacy stacks auth, where it required cors access on manifest.json to access that file remotely ... netlify uses that file. Here are the contents:
> 
> ```
> /manifest.json
>   Access-Control-Allow-Origin: *
>   Access-Control-Allow-Headers: "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
>   Access-Control-Allow-Methods: "GET"
> ```

Some of those CORS headers weren't being allowed. I adjusted our settings to allow all of those headers for the API. We're aligned with the other settings on origin and methods. @dantrevino  Can you please try calling a contract function on 300 assets again and let me know what you see?


> > ~300 requests resulting in a 502 (Bad Gateway)
> 
> this is the error that stacking.club would get when calling `v2/contracts/call-read/SP000000000000000000002Q6VF78*`, and I fairly certain the errors would happen when nothing was changing as far as restarts were concerned (as far as I am able to tell). @CharlieC3 do you know what other issues could cause 502s?

@aulneau I can see from the logs the traffic is making it through Nginx, and the API is responding with a `502`. That likely means the problem exists on the backing `stacks-node` and not necessarily the API. The logs don't contain much additional information however.

**Comment by friedger** [comment]
I see (now?) a cors error from using the Stacks Wallet for Web:

"Unable to fetch account data from https://stacks-node-api.testnet.stacks.co" due to CORS

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://stacks-node-api.testnet.stacks.co/extended/v1/tx/mempool?limit=30. (Reason: header ‘x-hiro-product’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

**Comment by CharlieC3** [comment]
@friedger Will follow up with you outside this thread. The CORS settings might need some adjustments.

**Comment by CharlieC3** [comment]
@dantrevino We've confirmed the stacks-nodes behind the API are beginning to suffer from a known resource exhaustion bug which may appear after a node has been running for a while. Let's re-test this tomorrow once replacement nodes are serving live traffic. For now, I've disabled CORS in testnet/mainnet because of a possible issue with the Stacks Web Wallet in Firefox (issue pending).

**Comment by diwakergupta** [comment]
> @dantrevino We've confirmed the stacks-nodes behind the API are beginning to suffer from a known resource exhaustion bug which may appear after a node has been running for a while. Let's re-test this tomorrow once replacement nodes are serving live traffic. For now, I've disabled CORS in testnet/mainnet because of a possible issue with the Stacks Web Wallet in Firefox (issue pending).

FYI this is issue https://github.com/blockstack/stacks-blockchain/issues/2552 which is fixed in `develop` (and available in `2.0.11-rc2`)

**Comment by 314159265359879** [comment]
> 
> 
> @dantrevino We've confirmed the stacks-nodes behind the API are beginning to suffer from a known resource exhaustion bug which may appear after a node has been running for a while. Let's re-test this tomorrow once replacement nodes are serving live traffic. For now, I've disabled CORS in testnet/mainnet because of a possible issue with the Stacks Web Wallet in Firefox (issue pending).

I no longer get the error, >350 NFT's loading perfectly again. Thanks!

**Comment by CharlieC3** [comment]
> I no longer get the error, >350 NFT's loading perfectly again. Thanks!

That's great! I switched traffic to the new API + followers about 12 hours ago, so it makes sense that the CORS issue was likely a mask for an underlying performance problem.

@dantrevino Are you ok with closing this issue? We can re-open it if you start seeing it again.

**Comment by dantrevino** [comment]
> > I no longer get the error, >350 NFT's loading perfectly again. Thanks!
> 
> That's great! I switched traffic to the new API + followers about 12 hours ago, so it makes sense that the CORS issue was likely a mask for an underlying performance problem.
> 
> @dantrevino Are you ok with closing this issue? We can re-open it if you start seeing it again.

Yup!

**Comment by dantrevino** [comment]
Thanks for the quick action everyone!

**Comment by aulneau** [comment]
This seems to be coming up again, this time from use of the extension. @whoabuddy reported errors with a new update that went out which checks the online status of the networks in the list, and disables them if the fetch fails.

This was provided as an example of the output during the errors

![image](https://user-images.githubusercontent.com/11803153/125806026-b66c85b2-def8-4051-978b-8d0c612763a7.png)

@CharlieC3 curious if there are times or settings in which this can happen on the api side? or if there is anything to be done on the application level to ignore cors? @zone117x do you have any ideas?

**Comment by whoabuddy** [comment]
This one is really bizarre, so far it's happening intermittently and in asking a few other users, 1 sees the issue and the next 2 don't.

Yesterday I took these steps:

- upgraded to `2.12.1` via extensions panel in developer mode
- had the issue, tried reloading ext, tried restarting browser, same
- extension auto-updated to `2.12.2`, issue still present
- removed and installed unpacked from @aulneau PR, issue resolved
- removed and reinstalled from chrome store, issue no longer present

Then this morning someone reported the same gray clouds in the CityCoins discord, and when I checked my network status, it was the same: all options grayed out and CORS errors in the console again.

But here's the kicker - now it's working fine again! Wondering if it's related to the load-balancing?

**Comment by whoabuddy** [comment]
Update: caught it happening again, but seeing the `access-control-allow-origin: *` header when I run curl:

```
$ curl -L -I -w "\n" https://stacks-node-api.mainnet.stacks.co
HTTP/2 302 
date: Thu, 15 Jul 2021 15:19:15 GMT
content-type: text/plain; charset=utf-8
content-length: 41
x-powered-by: Express
location: /extended/v1/status
vary: Accept
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=RIYQwxE4zDuBFU%2F7Ml8ui%2BEwkAD2iZNweZK9G%2FYT6Hpn1RP%2BKp4S9%2BNWQrSQhG34i5N5vwMOfJokygk7vxDQ7FXkAMemS0NxWpMsTeNMuMlnuzoztki1L5M0bxHHOqK7Mn%2F8wFerbemFuXzI5eUEiuDNQw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 66f3f7d14eed3604-LAX

HTTP/2 200 
date: Thu, 15 Jul 2021 15:19:15 GMT
content-type: application/json; charset=utf-8
content-length: 18
x-powered-by: Express
access-control-allow-origin: *
etag: W/"12-4TtQgvFNX2eV2jVHUVwyech4XJg"
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Oedt0ZSWXqly%2Bg5puYINN28vVinUtK6oIwY2Sm9rt7ADJME22zQqo0hAF0YrqAlcgIssOOGkmJxIDWoj1M1obCsCp8KI2HTJzfVt64k8rCrstIgxBhdl7g9xhTfcrD05IXUOMuNsYjZWrU0lpE7C%2BvmRvA%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 66f3f7d289cb3604-LAX
```

And the same CORS errors listed earlier in the console:

![Screenshot from 2021-07-15 08-22-27](https://user-images.githubusercontent.com/9038904/125813956-31ab1532-40f6-4e68-8fd7-931f7b09c50a.png)

Removing the extension and installing [this version](https://github.com/blockstack/stacks-wallet-web/pull/1448) fixed it, but everything still feels inconsistent. Will keep running this new version to see if it happens again.

**Comment by zone117x** [comment]
Can you capture the request from the network tab? The response headers would be useful.

**Comment by whoabuddy** [comment]
Will do - now it's working again so will have to wait to see if it comes back up, and will ask the same if anyone else reports it.

**Comment by whoabuddy** [comment]
Happened again today - see screenshot below:

![Screenshot from 2021-07-22 10-51-00](https://user-images.githubusercontent.com/9038904/126685800-8857e112-02f9-4bb2-b87e-d015795b28df.png)

Network requests show a 404 on the regtest preflight, other two were ok:

![Screenshot from 2021-07-22 11-15-26](https://user-images.githubusercontent.com/9038904/126694804-5c619518-db4f-4a45-bd5c-c1e5c2dd1d96.png)

## Headers from the mainnet preflight

General

```
Request URL: https://stacks-node-api.mainnet.stacks.co/
Request Method: OPTIONS
Status Code: 200 
Remote Address: 104.26.13.25:443
Referrer Policy: strict-origin-when-cross-origin
```

Response Headers

```
allow: GET,HEAD
cf-cache-status: DYNAMIC
cf-ray: 672ea3dc8c340cdb-LAX
content-encoding: br
content-type: text/html; charset=utf-8
date: Thu, 22 Jul 2021 18:12:56 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=sDJ2M5Y0GJZEd78dR3%2F4XNSvv6V5qCIpuFOL7WQ%2BlmwPiHJj1fgb3pjqLC%2BIxi5u%2Fi%2BypKP7kCZVZ7nPJ21lJ%2F4XwzlnS7063%2FukXW55USOy5kgYybx4fk%2BMfLo97od0upeEewoHdp2Jf7UIFQ3%2F8FXPMw%3D%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
x-powered-by: Express
```

Request headers

```
:authority: stacks-node-api.mainnet.stacks.co
:method: OPTIONS
:path: /
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
access-control-request-headers: x-hiro-product,x-hiro-version
access-control-request-method: GET
cache-control: no-cache
origin: chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj
pragma: no-cache
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Mobile Safari/537.36
```

## Headers from the mainnet xhr with CORS error

General

```
Request URL: https://stacks-node-api.mainnet.stacks.co/
Referrer Policy: strict-origin-when-cross-origin
```

Request Headers

```
⚠ Provisional headers are shown
DNT: 1
Referer
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Mobile Safari/537.36
x-hiro-product: stacks-wallet-web
x-hiro-version: 2.12.2
```

**Comment by zone117x** [comment]
@CharlieC3 any ideas?

**Comment by CharlieC3** [comment]
@whoabuddy Thanks for the info! With what you sent I was able to investigate further and reliably replicate the issue. I can't explain why you and other users saw this problem inconsistently -- In Chrome/Brave I do not get this issue at all, even after dozens of refreshes in the web wallet. It may be exceedingly rare in Chrome/Brave for unknown reasons. In Firefox I got the CORS issue on every reload! I'm surprised it didn't cause any further problems in the Firefox web wallet honestly.

Because of this, I was able to test and verify that enabling CORS in the API for `regtest` resolved the connection issues for `regtest` in the firefox web wallet, while `testnet` and `mainnet` were still disabled. I didn't see any problems appear after enabling CORS in `regtest` and `testnet` in the web wallets or desktop wallet, so I just enabled it in `mainnet` too.

Please let me know if you see any differences on your end, good or bad.

cc @zone117x

**Comment by whoabuddy** [comment]
@CharlieC3 That's great news! It was very random for me with Chrome/Brave, and I felt the same - it was very hard to replicate. Fortunately, it is working normally now and will report again if it comes up, thanks for the quick fix!
