### ISSUE TITLE
`v1-import` should store addresses in STX format

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#541]
It is an issue with `stacks-blockchain-api` specifically with `v1-import`. We should open up an issue there !.
@zone117x should we convert addresses to `stx addresses` before updating the DB or convert them in the API?

_Originally posted by @asimm241 in https://github.com/blockstack/subdomain-registrar/issues/48#issuecomment-814781991_

**Comment by asimm241** [comment]
I have started working on it !
