### ISSUE TITLE
[Rosetta] Offline Construction API

### ISSUE THREAD

**Issue by shermanxiong** [blockstack/stacks-blockchain-api#544]
### Context:
Rosetta-Api requires Construction API to be able to be run in a [completely offline environment](https://www.rosetta-api.org/docs/construction_api_introduction.html#completely-offline). This is a hard requirement from Coinbase for security reasons. Production transaction testing cannot commence without it.

As far as I can tell, the Stacks-API implements stacks `/v2` routes and `/rosetta/v1` routes in the same nodejs server

### Requirements
- to be able to run Construction API only in an offline environment
- `/construction/metadata` endpoint is the exception
- ideally an environment variable to toggle "online" vs "offline" modes

### Examples:
See [cardano-rosetta](https://github.com/input-output-hk/cardano-rosetta#mode)
See [rosetta-bitcoin](https://github.com/coinbase/rosetta-bitcoin/blob/7b5393dca11490da30594c211dc3b716900e4ac0/configuration/configuration.go#L41-L43)

**Comment by zone117x** [comment]
Closed by #545
