### ISSUE TITLE
How to query blocks and transaction using RPC

### ISSUE THREAD

**Issue by boohyung** [blockstack/stacks-blockchain-api#558]
Hi all. I want to make stacks 2.0 environment for local development(not docker). So I have built stacks-node(GitHub - blockstack/stacks-blockchain: The Stacks 2.0 blockchain implementation) and started node for connecting the mainnet. After I installed postgresql 12.2 and set the DB and user. And I’m trying to connect the node using stacks-blockchain-api(GitHub - blockstack/stacks-blockchain-api: API for the Stacks 2.0 blockchain)

**But I found the problems using Stacks Blockchain API(https://blockstack.github.io/stacks-blockchain-api).** 

.env:
```
PG_HOST=127.0.0.1
PG_PORT=5432
PG_USER=stacks
PG_PASSWORD=123
PG_DATABASE=stacks

STACKS_CORE_EVENT_PORT=3700
STACKS_CORE_EVENT_HOST=127.0.0.1

STACKS_BLOCKCHAIN_API_PORT=3999
STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
# STACKS_BLOCKCHAIN_API_DB=pg

STACKS_CORE_RPC_HOST=0.0.0.0
STACKS_CORE_RPC_PORT=20443

# STACKS_CORE_PROXY_HOST=127.0.0.1
# STACKS_CORE_PROXY_PORT=20443

# V2_POX_MIN_AMOUNT_USTX=9876543210

# STACKS_FAUCET_NODE_HOST=<IP or hostname>
# STACKS_FAUCET_NODE_PORT=<port number>

## configure the chainID/networkID; testnet: 0x80000000, mainnet: 0x00000001
STACKS_CHAIN_ID=0x00000001
# STACKS_CHAIN_ID=0x80000000

BTC_RPC_HOST="bitcoin.blockstack.com"
# BTC_RPC_HOST="bitcoind.xenon.blockstack.com"
BTC_RPC_PORT=8332
# BTC_RPC_PORT=18332
BTC_RPC_USER="blockstack"
BTC_RPC_PW="blockstacksystem"
#BTC_FAUCET_PK=29c028009a8331358adcc61bb6397377c995d327ac0343ed8e8f1d4d3ef85c27

# The contracts used to query for inbound transactions
TESTNET_SEND_MANY_CONTRACT_ID=STR8P3RD1EHA8AA37ERSSSZSWKS9T2GYQFGXNA4C.send-many-memo
MAINNET_SEND_MANY_CONTRACT_ID=SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo
```

Postgres DB setting:
```
psql (12.6, server 12.2)
Type "help" for help.

stacks=# \list
                              List of databases
   Name    | Owner | Encoding |   Collate   |    Ctype    | Access privileges 
-----------+-------+----------+-------------+-------------+-------------------
 postgres  | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 stacks    | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/bhlee        +
           |       |          |             |             | bhlee=CTc/bhlee  +
           |       |          |             |             | stacks=CTc/bhlee
 template0 | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/bhlee         +
           |       |          |             |             | bhlee=CTc/bhlee
 template1 | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/bhlee         +
           |       |          |             |             | bhlee=CTc/bhlee
(4 rows)
```

API Call result:
```
curl http://192.168.56.114:3999/extended/v1/block
{"limit":20,"offset":0,"total":0,"results":[]}
curl http://localhost:3999/extended/v1/tx
{"limit":96,"offset":0,"total":0,"results":[]}
```

Command for executing the API server:
```
cd stacks-blockchain-api
npm install
npm run dev
```

API Server(stacks-blockchain-api) Log:
```
{"message":"Event observer listening at: http://127.0.0.1:3700","level":"info","timestamp":"2021-04-15T00:07:51.300Z"}
{"message":"/v2/* proxying to: 0.0.0.0:20443","level":"info","timestamp":"2021-04-15T00:07:51.749Z"}
[HPM] Proxy created: /  -> http://0.0.0.0:20443
{"message":"API server listening on: http://0.0.0.0:3999","level":"info","timestamp":"2021-04-15T00:07:51.779Z"}
{"message":"@promster/server started on port 9153.","level":"info","timestamp":"2021-04-15T00:07:51.780Z"}
{"message":"App initialized","level":"info","timestamp":"2021-04-15T00:07:51.780Z"}
{"message":"Connection to Stacks core node API server at: 0.0.0.0:20443","level":"info","timestamp":"2021-04-15T00:07:51.912Z"}
{"message":"Event observer listening at: http://127.0.0.1:3700","level":"info","timestamp":"2021-04-15T00:26:50.914Z"}
{"message":"/v2/* proxying to: 0.0.0.0:20443","level":"info","timestamp":"2021-04-15T00:26:51.246Z"}
[HPM] Proxy created: /  -> http://0.0.0.0:20443
{"message":"API server listening on: http://0.0.0.0:3999","level":"info","timestamp":"2021-04-15T00:26:51.271Z"}
{"message":"@promster/server started on port 9153.","level":"info","timestamp":"2021-04-15T00:26:51.271Z"}
{"message":"App initialized","level":"info","timestamp":"2021-04-15T00:26:51.271Z"}
{"message":"Connection to Stacks core node API server at: 0.0.0.0:20443","level":"info","timestamp":"2021-04-15T00:26:51.380Z"}
{"req":{"url":"/extended/v1/block","headers":{"user-agent":"curl/7.29.0","host":"192.168.56.114:3999","accept":"*/*"},"method":"GET","httpVersion":"1.1","originalUrl":"/extended/v1/block","query":{}},"res":{"statusCode":200},"responseTime":29,"level":"info","message":"HTTP GET /extended/v1/block","timestamp":"2021-04-15T00:59:34.026Z"}
{"req":{"url":"/extended/v1/tx","headers":{"user-agent":"curl/7.29.0","host":"localhost:3999","accept":"*/*"},"method":"GET","httpVersion":"1.1","originalUrl":"/extended/v1/tx","query":{}},"res":{"statusCode":200},"responseTime":25,"level":"info","message":"HTTP GET /extended/v1/tx","timestamp":"2021-04-15T01:00:08.659Z"}
{"req":{"url":"/extended/v1/block/by_height/123","headers":{"user-agent":"curl/7.29.0","host":"localhost:3999","accept":"*/*"},"method":"GET","httpVersion":"1.1","originalUrl":"/extended/v1/block/by_height/123","query":{}},"res":{"statusCode":404},"responseTime":6,"level":"info","message":"HTTP GET /extended/v1/block/by_height/123","timestamp":"2021-04-15T01:03:53.429Z"}
{"req":{"url":"/extended/v1/block/0xbc2a4a75cf7e508d683481a7b952c5e52bda2c6a4096210da1fcc7d81ee15e5c","headers":{"user-agent":"curl/7.29.0","host":"localhost:3999","accept":"*/*"},"method":"GET","httpVersion":"1.1","originalUrl":"/extended/v1/block/0xbc2a4a75cf7e508d683481a7b952c5e52bda2c6a4096210da1fcc7d81ee15e5c","query":{}},"res":{"statusCode":404},"responseTime":3,"level":"info","message":"HTTP GET /extended/v1/block/0xbc2a4a75cf7e508d683481a7b952c5e52bda2c6a4096210da1fcc7d81ee15e5c","timestamp":"2021-04-15T01:04:03.241Z"}
```

**I think my API Server(stacks-blockchain-api) cannot find any transaction data although running node well. I want to query block & transaction data. Please let me know how to resolve the problem. Thanks.**

**Comment by zone117x** [comment]
How are you running `stacks-node`? Did you configure the event observer? If you run all the dependencies yourself, you need to replicate the correct config. Event observer can be configured with an env var like this https://github.com/blockstack/stacks-blockchain-api/blob/e625623ae5daa78096dbd6e510ad4240bf8e87f8/docker-compose.dev.stacks-blockchain.yml#L9

You should also refer to this repo for additional config guidelines: https://github.com/blockstack/stacks-local-dev/tree/mainnet

**Comment by boohyung** [comment]
@zone117x 

I didn't configure the event observer. Now I added as shown below. 

stacks-node config: stacks-config.toml
```
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
working_dir = "/home/bhlee/data/chain"
bootstrap_node = "02da7a464ac770ae8337a343670778b93410f2f3fef6bea98dd1c3e9224459d36b@seed-0.mainnet.stacks.co:20444,02afeae522aab5f8c99a00ddf75fbcb4a641e052dd48836408d9cf437344b63516@seed-1.mainnet.stacks.co:20444,03652212ea76be0ed4cd83a25c06e57819993029a7b9999f7d63c36340b34a4e62@seed-2.mainnet.stacks.co:20444"

[[events_observer]]
endpoint = "127.0.0.1:3700"
retry_count = 255
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "mainnet"
peer_host = "bitcoin.blockstack.com"
rpc_port = 8332
peer_port = 8333
username = "blockstack"
password = "blockstacksystem"
magic_byte = "X2"
```

But stacks-node is stucked after registering event observer. So it doesn't listen to the rpc port either. 

stacks-node log:
- command to start: ./stacks-node start --config=stacks-config.toml 

```
INFO [1618983867.872031] [testnet/stacks-node/src/main.rs:80] [main] stacks-node 2.0.10.0.1 (HEAD:f9e91d9, release build, linux [x86_64])
INFO [1618983867.872065] [testnet/stacks-node/src/main.rs:125] [main] Loading config at path stacks-config.toml
INFO [1618983868.288721] [testnet/stacks-node/src/run_loop/neon.rs:134] [main] Will run as a Follower node
INFO [1618983868.288748] [testnet/stacks-node/src/run_loop/neon.rs:141] [main] Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while
INFO [1618983870.178128] [testnet/stacks-node/src/event_dispatcher.rs:561] [main] Registering event observer at: 127.0.0.1:3700
```

What should I do?

**Comment by boohyung** [comment]
@zone117x Please I'm waiting any update, comment or information for solving the problem.

**Comment by zone117x** [comment]
Looks like the API is not reachable at `127.0.0.1:3700`. Have you checked if that port is accepting http requests when you see the error message `Event dispatcher: connection failed - Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }` ?

**Comment by boohyung** [comment]
Event dispatcher problem is resolved now. Thanks.

Another problem of stacks-blockchain-api is found. I think the MAINNET block data cannot save to PostgreSQL(already installed postgres 12.2 in my machine)

Error log of stacks-blockchain-api:
```bash
Error processing core node block message
Error: DB does not contain a parent block at height 285 with index_hash 0x53fca20f2d7aedd556598d7eee912852a66d57cc471f246243f1b1cf1e6f500c
    at PgDataStore.handleReorg (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:876:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:451:7
    at /home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:414:24
    at PgDataStore.query (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:400:22)
    at PgDataStore.queryTx (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:411:12)
    at PgDataStore.update (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:449:5)
    at handleClientMessage (/home/bhlee/stacks-blockchain-api/src/event-stream/event-server.ts:365:3)
    at run (/home/bhlee/stacks-blockchain-api/node_modules/p-queue/dist/index.js:163:29)
```

environment variables of stacks-blochain-api:
```
PG_HOST=127.0.0.1
PG_PORT=5432
PG_USER=stacks
PG_PASSWORD=123
PG_DATABASE=stacks

STACKS_CORE_EVENT_PORT=3700
STACKS_CORE_EVENT_HOST=127.0.0.1

STACKS_BLOCKCHAIN_API_PORT=3999
STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
STACKS_BLOCKCHAIN_API_DB=pg

STACKS_CORE_RPC_HOST=127.0.0.1
STACKS_CORE_RPC_PORT=20443

## configure the chainID/networkID; testnet: 0x80000000, mainnet: 0x00000001
STACKS_CHAIN_ID=0x00000001

BTC_RPC_HOST="bitcoin.blockstack.com"
BTC_RPC_PORT=8332
BTC_RPC_USER="blockstack"
BTC_RPC_PW="blockstacksystem"
```

Settings of postgreSQL:
```
postgres=# \list
                              List of databases
   Name    | Owner | Encoding |   Collate   |    Ctype    | Access privileges 
-----------+-------+----------+-------------+-------------+-------------------
 postgres  | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 stacks    | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/bhlee        +
           |       |          |             |             | bhlee=CTc/bhlee  +
           |       |          |             |             | stacks=CTc/bhlee
 template0 | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/bhlee         +
           |       |          |             |             | bhlee=CTc/bhlee
 template1 | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/bhlee         +
           |       |          |             |             | bhlee=CTc/bhlee
(4 rows)

postgres=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 bhlee     | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 stacks    |                                                            | {}
```

**Comment by boohyung** [comment]
> @zone117x Event dispatcher problem is resolved now. Thanks.
> 
> Another problem of stacks-blockchain-api is found. I think the MAINNET block data cannot save to PostgreSQL(already installed postgres 12.2 in my machine)
> 
> Error log of stacks-blockchain-api:
> 
> ```shell
> Error processing core node block message
> Error: DB does not contain a parent block at height 285 with index_hash 0x53fca20f2d7aedd556598d7eee912852a66d57cc471f246243f1b1cf1e6f500c
>     at PgDataStore.handleReorg (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:876:15)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at /home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:451:7
>     at /home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:414:24
>     at PgDataStore.query (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:400:22)
>     at PgDataStore.queryTx (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:411:12)
>     at PgDataStore.update (/home/bhlee/stacks-blockchain-api/src/datastore/postgres-store.ts:449:5)
>     at handleClientMessage (/home/bhlee/stacks-blockchain-api/src/event-stream/event-server.ts:365:3)
>     at run (/home/bhlee/stacks-blockchain-api/node_modules/p-queue/dist/index.js:163:29)
> ```
> 
> environment variables of stacks-blochain-api:
> 
> ```
> PG_HOST=127.0.0.1
> PG_PORT=5432
> PG_USER=stacks
> PG_PASSWORD=123
> PG_DATABASE=stacks
> 
> STACKS_CORE_EVENT_PORT=3700
> STACKS_CORE_EVENT_HOST=127.0.0.1
> 
> STACKS_BLOCKCHAIN_API_PORT=3999
> STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
> STACKS_BLOCKCHAIN_API_DB=pg
> 
> STACKS_CORE_RPC_HOST=127.0.0.1
> STACKS_CORE_RPC_PORT=20443
> 
> ## configure the chainID/networkID; testnet: 0x80000000, mainnet: 0x00000001
> STACKS_CHAIN_ID=0x00000001
> 
> BTC_RPC_HOST="bitcoin.blockstack.com"
> BTC_RPC_PORT=8332
> BTC_RPC_USER="blockstack"
> BTC_RPC_PW="blockstacksystem"
> ```
> 
> Settings of postgreSQL:
> 
> ```
> postgres=# \list
>                               List of databases
>    Name    | Owner | Encoding |   Collate   |    Ctype    | Access privileges 
> -----------+-------+----------+-------------+-------------+-------------------
>  postgres  | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
>  stacks    | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/bhlee        +
>            |       |          |             |             | bhlee=CTc/bhlee  +
>            |       |          |             |             | stacks=CTc/bhlee
>  template0 | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/bhlee         +
>            |       |          |             |             | bhlee=CTc/bhlee
>  template1 | bhlee | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/bhlee         +
>            |       |          |             |             | bhlee=CTc/bhlee
> (4 rows)
> 
> postgres=# \du
>                                    List of roles
>  Role name |                         Attributes                         | Member of 
> -----------+------------------------------------------------------------+-----------
>  bhlee     | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
>  stacks    |                                                            | {}
> ```

Now I have change environment variable "PG_USER" stacks -> bhlee due to roles and authority.

**Comment by zone117x** [comment]
> Error processing core node block message
> Error: DB does not contain a parent block at height 285 with index_hash 0x53fca20f2d7aedd556598d7eee912852a66d57cc471f246243f1b1cf1e6f500c

This usually indicates postgres DB is out of sync. It currently has to be wiped if the node + API are restarted from scratch.

**Comment by boohyung** [comment]
Thanks for your comment. But I found the another problem.

I used latest node and api and opened 3700, 3999, 20444, 8333 port now.

error: 
 1. stuck at "stacks_tip_height" 0 burnchain 
 2. cannot listen to port 3999 to stacks-blockchain-api

error log(stack-node): 
WARN [1619516350.173343] [src/net/rpc.rs:630] [p2p] Failed to get peer info GetInfo(HttpRequestMetadata { version: Http11, peer: PeerHost::IP(00000000000000000000ffff7f000001,20443), keep_alive: false }): DBError(NotFoundError)

response v2/info:
{
    "burn_block_height": 667563,
    "exit_at_block_height": null,
    "genesis_chainstate_hash": "74237aa39aa50a83de11a4f53e9d3bb7d43461d1de9873f402e5453ae60bc59b",
    "network_id": 1,
    "parent_network_id": 3652501241,
    "peer_version": 402653184,
    "pox_consensus": "4b1d720384b2bf69f05763c49dbef4fd31698ca3",
    "server_version": "stacks-node 2.0.11.0.0 (HEAD:bf4a577, release build, linux [x86_64])",
    "stable_burn_block_height": 667556,
    "stable_pox_consensus": "8f21ea125946d403b0f58a4240bef70a263a0294",
    "stacks_tip": "0000000000000000000000000000000000000000000000000000000000000000",
    "stacks_tip_consensus_hash": "0000000000000000000000000000000000000000",
    "stacks_tip_height": 0,
    "unanchored_seq": 0,
    "unanchored_tip": "4ec7ae4a471502547f69ff7165ce5eab0257def1a6607770512fb66e5fcc7e79"
}

**Comment by boohyung** [comment]
rpc_bind and p2p_bind value is changed and reset DB/remove working_dir.

When a node download bitcoin(burnchain) block data, an error is occurred and sync is so slow.

stacks-node log:
WARN [1619571377.295411] [src/burnchains/bitcoin/network.rs:199] [main] Failed to handshake with 34.86.174.130:8333: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" }), WARN [1619571378.317520] [src/burnchains/bitcoin/indexer.rs:501] [main] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })

stacks-blockchain-api log: following messages are looped.
{"message":"Received burn block message hash 0x000000000000000000022f5e2ab1fa0bce06438b1cc11560593483e8d74e6d49, height: 666888","level":"verbose","timestamp":"2021-04-28T01:01:33.002Z"}
{"message":"Received burn block rewards for 0 recipients","level":"verbose","timestamp":"2021-04-28T01:01:33.002Z"}

**Comment by wileyj** [comment]
> 34.86.174.130

This is likely a timeout in the codebase since the connection is taking too long. This IP is a public bitcoin node that is in the US - do you have a local or regionally available bitcoin node you can try?
https://github.com/blockstack/stacks-blockchain-api/issues/558#issuecomment-823796249

essentially you may need to try updating this in your stacks-config.toml (sample update where `10.0.1.100` is a local btc node):
```
[burnchain]
chain = "bitcoin"
mode = "mainnet"
peer_host = "10.0.1.100"
rpc_port = 8332
peer_port = 8333
username = "bitcoin"
password = "bitcoin"
magic_byte = "X2"
```

Otherwise, I'd expect some slower header sync times from the default bitcoin node in the config - and as you've noticed, there will be timeouts depending on current network latency.

**Comment by agraebe** [comment]
looks like there's no further activity on this issue - should it be closed?

**Comment by boohyung** [comment]
I have closed now. Thanks.
