### ISSUE TITLE
[TESTNET BUG] rosetta submit API returns  SignatureValidation for  the correctly signed raw transaction

### ISSUE THREAD

**Issue by ChuYimeng** [blockstack/stacks-blockchain-api#581]
## Describe the bug
Today I find that the raw transaction generated by the program written by myself can not success to send rosetta  submit request. In order to verify the rosetta  API, firstly I send the raw transacction returned from faucet api, so the raw transacction must be signed correctly, but Rosetta submit API for  the correctly signed raw transaction returns:

```json
{
    "code": 628,
    "message": "Invalid transaction string",
    "retriable": false,
    "details": {
        "message": "Response 400: Bad Request fetching http://stacks-node-follower-blue.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"SignatureValidation\",\"reason_data\":{\"message\":\"Invalid signature: failed to decode recoverable signature\"},\"txid\":\"6d12ccbfc35df5555694d249aa25ada7827b92c750464fb88373d31764b14e51\"}"
    }
}
```
instead of `nonce too low`
## Steps To Reproduce

POST `https://stacks-node-api.testnet.stacks.co/rosetta/v1/construction/submit` with
```json
{
    "network_identifier": {
        "blockchain": "stacks",
        "network": "testnet"
    },
    "signed_transaction": "80800000000400164247d6f2b425ac5771423ae6c80c754f7172b00000000000000e8e00000000000000b400014977aebdd567bdf14b6347791367e71b2afd0a34d9a1ae63d756328d56c6bb74187afda46fbc1c0e63b5a95db5400782bdd4e74d97d828a4cb0d3421d16709f503020000000000051ad2f414a81b37f611612bf520c40d61cbfcdd5d35000000001dcd650046617563657400000000000000000000000000000000000000000000000000000000"
}
```

## Expected behavior

return `nonce too low` , because the raw transaction is generated from the faucet api

## Environment

 - OS: Windows
 - App: Postman

**Comment by zone117x** [comment]
> raw transaction generated by the program written by myself

Can you provide details on how you're doing this?

Also see this related PR on the rosetta /submit signature format https://github.com/blockstack/stacks-blockchain-api/pull/572

**Comment by ChuYimeng** [comment]
@zone117x  The raw transaction is from the `txRaw` field of  Faucets API (https://stacks-node-api.testnet.stacks.co/extended/v1/faucets/stx), so the signature must be correct, but Calling rosetta submit API with the raw transaction from Faucets returns `SignatureValidation` rather than `nonce too low`. In addition, The http tool is Postman.

**Comment by ChuYimeng** [comment]
@zone117x
The raw transaction is from txRaw field: 
![image](https://user-images.githubusercontent.com/29088201/117392966-add4fe80-af25-11eb-9f0a-16320da64297.png)

POST rosetta submit:
![image](https://user-images.githubusercontent.com/29088201/117393585-08228f00-af27-11eb-8567-ee47b7819b9f.png)
Expected error is `nonce too low` rather than `Invalid signature`.

**Comment by zone117x** [comment]
See this PR for context around signature formatting for Rosetta endpoints: https://github.com/blockstack/stacks-blockchain-api/pull/572

Rosetta supports signatures with the `r (32-bytes) || s (32-bytes) || v (1-byte)` format, where the `stacks-node` expects a different ordering. See https://github.com/coinbase/rosetta-specifications#supported-signaturetypes

**Comment by ChuYimeng** [comment]
@zone117x  thanks, rosetta has different  signature format.
