### ISSUE TITLE
/v1/names/*/zonefile endpoint returning empty zone file

### ISSUE THREAD

**Issue by MarvinJanssen** [blockstack/stacks-blockchain-api#582]
**Describe the bug**
The `/v1/names/*/zonefile` and `/v1/names/*/zonefile/*` API endpoints return an empty zone file at times. The [docs](https://blockstack.github.io/stacks-blockchain-api/#operation/fetch_zone_file) state:

>Fetch a user’s raw zone file. This only works for RFC-compliant zone files. This method returns an error for names that have non-standard zone files.

But I do not get an error. Instead, I get a HTTP 200 OK when I [query the endpoint](https://stacks-node-api.mainnet.stacks.co/v1/names/test.btc/zonefile/b07cad4ddd53c09342d6030154e16d7cad90fef5):

```JSON
{"zonefile":""}
```

The zone file is definitely on Atlas, as evidenced [here](https://stacks-node-api.mainnet.stacks.co/v2/attachments/b07cad4ddd53c09342d6030154e16d7cad90fef5):
```JSON
"244f524947494e20746573742e6274632e0a2454544c20333630300a0a746573742e6274632e09494e0941093136312e33352e3232382e36310a746573742e6274632e09494e0954585409224564697420746573742033220a"
```

When decoded:

```
$ORIGIN test.btc.
$TTL 3600

test.btc.	IN	A	161.35.228.61
test.btc.	IN	TXT	"Edit test 3"

```

Here is one that does work:

- [Zonefile endpoint](https://stacks-node-api.mainnet.stacks.co/v1/names/test.btc/zonefile/943f469cf471a9b15efc3bef06119a020b0d4542)
- [Attachment endpoint](https://stacks-node-api.mainnet.stacks.co/v2/attachments/943f469cf471a9b15efc3bef06119a020b0d4542)

**To Reproduce**
Not sure.

**Expected behavior**
For the endpoint to return the zone file.

**Additional context**

Is it something in Blockstack's [custom version of `zone-file`](https://github.com/blockstack/zone-file-js)?

https://github.com/blockstack/stacks-blockchain-api/blob/37bc66c6b5f9e8a687026810d9b32f2ae104787d/src/event-stream/event-server.ts#L66
https://github.com/blockstack/stacks-blockchain-api/blob/37bc66c6b5f9e8a687026810d9b32f2ae104787d/src/event-stream/event-server.ts#L471 

I use the original [`zone-file` package](https://www.npmjs.com/package/zone-file) and it parses the zone file above successfully:

```JS
> parseZoneFile(zone)
{
  '$origin': 'test.btc.',
  '$ttl': 3600,
  a: [ { name: 'test.btc.', ip: '161.35.228.61' } ],
  txt: [ { name: 'test.btc.', txt: 'Edit test 3' } ]
}
```

It is [impossible to write a clean lexer for DNS zone files](https://www.nlnetlabs.nl/documentation/nsd/grammar-for-dns-zone-files/), according to the author of NSD.

**Comment by MarvinJanssen** [comment]
Looking at the code, I am pretty sure it has to do with this:

https://github.com/blockstack/stacks-blockchain-api/blob/37bc66c6b5f9e8a687026810d9b32f2ae104787d/src/event-stream/event-server.ts#L473-L513

So my test TXT entry causes the API to enter the sub domain flow. It therefore seems like arbitrary TXT entries are not possible with the current model? Is there a spec about TXT entries on BNS? Should we avoid them? That would be unfortunate because TXT is useful.

**Comment by zone117x** [comment]
Found the corresponding error log entry for these txs:
```
Error: zone file contents missing URI: $ORIGIN test.btc.
$TTL 3600

test.btc.	IN	A	161.35.228.61
test.btc.	IN	TXT	"Edit test 3"

    at handleNewAttachmentMessage (/app/src/event-stream/event-server.ts:513:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at run (/app/node_modules/p-queue/dist/index.js:159:29)
```


> So my test TXT entry causes the API to enter the sub domain flow. It therefore seems like arbitrary TXT entries are not possible with the current model?

Yep looks like this is currently the situation, but I think it's a bug. If a `ZoneFileTXT` can't be parsed out of the zonefile content, it probably shouldn't go down the subdomain path at all.

cc/ @asimm241

**Comment by MarvinJanssen** [comment]
Thanks @zone117x. The missing $ORIGIN one is due to an earlier mistake on my part. The later transactions did include an $ORIGIN. (See the OP.) 

I understand sub domains are encoded in TXT records? Is there more information to be found about it somewhere? (Observing `parseZoneFileTxt()`:)

https://github.com/blockstack/stacks-blockchain-api/blob/37bc66c6b5f9e8a687026810d9b32f2ae104787d/src/bns-helpers.ts#L184-L215

**Comment by zone117x** [comment]
The https://github.com/blockstack/subdomain-registrar codebase is probably the best source of truth for the subdomain zonefile encoding.

**Comment by MarvinJanssen** [comment]
I agree, and if zone files with TXT records that do not conform to the sub domain mechanism are still indexed, that would be great as well. (Instead of saving an empty string.)

**Comment by asimm241** [comment]
> Note: the error condition brought up here (where `$ORIGIN` is missing) needs changed. Event observer handlers should only throw due to an unknown critical bug. In this case, it's throwing on malformed user input (zonefile content). It should probably just accept zonefiles/subdomains with an empty `$ORIGIN`, and allow clients to choose how to handle these zonefiles from endpoints like `/v1/names/*/zonefile` and `/v1/names/*/zonefile/*`.
> 
> Alternatively, malformed zonefiles can be discarded (without throwing), although that would create hard to debug situations like the original issue here.
> 
> cc @asimm241

The Error is due to missing `URI` not the `$ORIGIN`  and `URI` is important for the subdomain redirect feature.

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/592
