### ISSUE TITLE
/v1/addresses endpoint returning empty names array

### ISSUE THREAD

**Issue by mostafaamr137** [blockstack/stacks-blockchain-api#584]
**Describe the bug**
addresses end point https://stacks-node-api.stacks.co/v1/addresses/stacks/${stxAddress} returns an empty array

**To Reproduce**
1. https://stacks-node-api.stacks.co/v1/names/mostafaamr137.id.blockstack
2. you can see that this is registered subdomain with address SP3272W9PE0P9CY1K8SFM0BS6HMAB50M2BTFZ0AG1
3. now going to the addresses end point with the same address https://stacks-node-api.stacks.co/v1/addresses/stacks/SP3272W9PE0P9CY1K8SFM0BS6HMAB50M2BTFZ0AG1
4. they names array is empty.

**Expected behavior**
the addresses end point should have an array with [mostafaamr137.id.blockstack] is it.

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/594

**Comment by mostafaamr137** [comment]
i have noticed that there is a release happened yesterday and it include the fix for this issue at commit https://github.com/blockstack/stacks-blockchain-api/commit/20bb6f3e6f528162c17c2e7eb560630585edab2c
but the issue is still there so i wanted to confirm.
