### ISSUE TITLE
Rosetta's /network/options switching between slightly different responses

### ISSUE THREAD

**Issue by GCrispino** [blockstack/stacks-blockchain-api#591]
**Describe the bug**
When requesting the `/rosetta/v1/network/options` endpoint, the error 613's object (inside the response's `allow.errors` array) sometimes has the `details` property set, and sometimes not.
I'm not really sure if this is expected behavior, but I'm using [Rosetta's Go SDK](https://github.com/coinbase/rosetta-sdk-go) and when this error object has the details property set, the SDK request to get the Network's options gives the following error:

```
error details populated in /network/options: /network/options <nil> false
```
Which as far as I understand means that this error object shouldn't have the details property populated.
This also does not look like a result of an error from Stacks' implementation, because the rest of the response looks the same as far as I could tell.

**To Reproduce**
1. Make a request to the API's endpoint `/rosetta/v1/network/options`;
2. Sometimes the response contains the detail property in the error with code 613 in the `allow.errors` array, looking something like this:
```
{
    "code": 613,
    "message": "Network identifier object is null.",
    "retriable": false,
    "details": {
        "message": "should have required property 'network_identifier'"
    }
}
```
, or like this (which doesn't trigger errors in the Rosetta SDK):
```
{
    "code": 613,
    "message": "Network identifier object is null.",
    "retriable": false
}
```

**Expected behavior**
Always return one response or the other.

You can check out the request and response format in [this link](https://reqbin.com/ukp8yilp).

**Comment by zone117x** [comment]
@GCrispino can you open an issue in the Rosetta Go SDK repo? It looks like a bug on their end. The `details` field appears to be supported https://www.rosetta-api.org/docs/models/Error.html

**Comment by GCrispino** [comment]
> @GCrispino can you open an issue in the Rosetta Go SDK repo? It looks like a bug on their end. The `details` field appears to be supported https://www.rosetta-api.org/docs/models/Error.html

Sure, that sounds right.

However, the Stacks API doesn't always return the error object with the details field. Isn't this unexpected behavior? If you repeat the request a few times you might notice this.

**Comment by agraebe** [comment]
did the PR resolve your issue @GCrispino? should we close the issue?

**Comment by GCrispino** [comment]
@agraebe I think so, but haven't tested anything. @zone117x it was fixed, wasn't it?

**Comment by zone117x** [comment]
Should be fixed, feel free to reopen if you see it again

**Comment by GCrispino** [comment]
Awesome, thanks!
