### ISSUE TITLE
Availability of /v1/names/{name}/history?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain-api#604]
Hi folks,

@Exulansis (from Jolocom) is coming up to the point in his implementation of the DID resolver where he needs to be able to query the history of txids for a name in order to resolve a DID to its _current_ public key (i.e. in the face of multiple name-transfers and name-renewals).  Is there an ETA when this will be implemented?  Right now it seems to be stubbed to 404.

**Comment by agraebe** [comment]
it'll be difficult for us to prioritize this right now. is there an expectation for this to be completed soon (any dependencies we have)?

**Comment by jcnelson** [comment]
I'll let @Exulansis answer that.

**Comment by Exulansis** [comment]
Thank you @jcnelson for opening this issue, and thank you @agraebe for the response,

Wrgt. timelines -- this feature would be required for our [DID resolver implementation](github.com/jolocom/stacks-DID-Resolver) to be fully functional. The resolver is still being developed, but the intention is to finalize it in the upcoming month(s). The current time frame we have for the resolver implementation would end on the 30.06.21.

We can mock this endpoint as part of our (being developed) test suite for the DID resolver, and substitute the mocked call with a call to the exposed endpoint once the feature is implemented. This would allow us to continue building out the resolution logic while this feature is being developed.

**Comment by zone117x** [comment]
@Exulansis is this still required for the DID resolver, did you end up mocking the endpoint? Or did you find another way around it?

**Comment by Exulansis** [comment]
@zone117x Sorry for not getting back to this issue with an update sooner. This endpoint is no longer required for DID resolution due to a change in the design / resolution process (specifically wrgt. how key rotation is handled). Therefore there was no need to mock it.

I suppose this issue can be closed now.
