### ISSUE TITLE
Expose associated transactions for FT/NFTs for a given address

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#615]
We have an endpoint that does this but only for transactions that have a token transfer (stx) event -> https://blockstack.github.io/stacks-blockchain-api/#operation/get_account_inbound

We need an ability to see these kind of events for FT and NFT tokens too. 

Until this is exposed via the API, the wallets won't be able to display incoming transactions from others that result in some amount of a token being sent to the recipient. 

cc @andresgalante, maybe this is something user-x can take on?

**Comment by zone117x** [comment]
Note: the equivalent STX tx endpoint to replicate for this is actually https://blockstack.github.io/stacks-blockchain-api/#operation/get_account_transactions_with_transfers
`https://stacks-node-api.mainnet.stacks.co/extended/v1/address/{principal}/transactions_with_transfers`
