### ISSUE TITLE
/v1/addresses endpoint returning empty names array 

### ISSUE THREAD

**Issue by mostafaamr137** [blockstack/stacks-blockchain-api#618]
**Describe the bug**
addresses end point https://stacks-node-api.stacks.co/v1/addresses/stacks/${stxAddress} returns an empty array

**To Reproduce**
1. https://stacks-node-api.stacks.co/v1/names/mostafaamr137.id.blockstack
2. you can see that this is registered subdomain with address SP3272W9PE0P9CY1K8SFM0BS6HMAB50M2BTFZ0AG1
3. now going to the addresses end point with the same address https://stacks-node-api.stacks.co/v1/addresses/stacks/SP3272W9PE0P9CY1K8SFM0BS6HMAB50M2BTFZ0AG1
4. they names array is empty.

**Expected behavior**
the addresses end point should have an array with [mostafaamr137.id.blockstack] is it.

it should have been done like 2 weeks ago but the bug is still there with this example

**Comment by agraebe** [comment]
@asimm241 to take a look

**Comment by mostafaamr137** [comment]
i have submitted the same issue before and it got fixed and released at v0.61 but this case is still happening with me.
the old issue link: https://github.com/blockstack/stacks-blockchain-api/issues/584

**Comment by asimm241** [comment]
I have investigated this on my end, It is working and there is a test case written for this specific case to test it. 
I don't know if `v0.61.0` is deployed. @agraebe how do I confirm that?

**Comment by agraebe** [comment]
It looks like this is the deployed version, based on the [bot comment](https://github.com/blockstack/stacks-blockchain-api/pull/609#issuecomment-844242393). @wileyj or @CharlieC3, can you quickly +1 if that's right? thanks!

**Comment by CharlieC3** [comment]
@agraebe `v0.61.0` is only deployed to testnet at the moment. Mainnet is running `0.56.0`. I'll check with Matt to see if we're able to upgrade it today.

**Comment by CharlieC3** [comment]
@mostafaamr137 @asimm241 `0.61.0` has been deployed to mainnet! [This URL](https://stacks-node-api.stacks.co/v1/addresses/stacks/SP3272W9PE0P9CY1K8SFM0BS6HMAB50M2BTFZ0AG1) is now returning a valid array.
