### ISSUE TITLE
Singular tx with STX transfer events endpoint

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-blockchain-api#622]
The wallet's now consuming the [`get_account_transactions_with_transfers`](https://blockstack.github.io/stacks-blockchain-api/#operation/get_account_transactions_with_transfers) endpoint. 

It would be helpful if there were an endpoint that will return the same format, so it can be used consistently throughout.

**Comment by zone117x** [comment]
@kyranjamie could you give a bit more context to this request? I'm not totally sure what's being requested.

**Comment by kyranjamie** [comment]
Yes, sorry. The response format where a transaction & all its summed STX transfers are returned, only exists as an array response of _all_ transactions.

I'd like an endpoint where I can get the same JSON format, but only for a single txid.

**Comment by zone117x** [comment]
Ah okay, that makes sense. So something like `/extended/v1/address/{principal}/{tx_id}/with_transfers` right?

**Comment by asimm241** [comment]
@kyranjamie  what do you think of the above suggestion?

**Comment by kyranjamie** [comment]
@zone117x  @asimm241 Yes, this'd be perfect.

**Comment by agraebe** [comment]
with the PRs merged, can this be closed out?
