### ISSUE TITLE
name-transfer ownership doesn't update the address on /v1/names endpoint

### ISSUE THREAD

**Issue by mostafaamr137** [blockstack/stacks-blockchain-api#623]
**Describe the bug**
After making a name-transfer with new owner address it should be updated to the address field for the /v1/names endpoint 
for example 
this transaction: https://explorer.stacks.co/txid/0x842aa4c610c722b9bd0817b6a38e5ab11126115b78f3e0cb633a61300bde4238?chain=mainnet
updates the name to the new owner address: SPF2HQPGY29464X0TWFVF1J7431HF99TATGE5A87
but this end point: https://stacks-node-api.stacks.co/v1/names/mostafa.btc
still shows the old owner address but the last_txid field is updated and expire_block is 0 which is weird too.

**Comment by zone117x** [comment]
I think the `name-transfer` function in the bns contract is currently buggy https://github.com/blockstack/stacks-blockchain/discussions/2685

**Comment by agraebe** [comment]
if this cannot be fixed on the API side of things, should we close this @zone117x ?
