### ISSUE TITLE
API client docs cannot be generated

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#633]
Inside the `client` folder the `generate:docs` command is available to generate Typedoc references for the API client. The command is currently failing:

```
Alexanders-MBP:client alexandergraebe$ yarn generate:docs
yarn run v1.22.10
$ typedoc
Error: Tried to set an option (inputFiles) that was not declared.
Error: Tried to set an option (mode) that was not declared.
error Command failed with exit code 1.
```

It might be released to an update of typedoc (eg [release v0.20.0](https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0))

**Comment by zone117x** [comment]
Yeah it was related to typedoc breaking changes. I fixed it a while ago in the microblocks branch

**Comment by agraebe** [comment]
ahh, I'll close this issue in that case. can reopen later otherwise
