### ISSUE TITLE
Harden API against malicious or invalid HTTP requests

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain-api#636]
**Describe the bug**
The API should handle malicious or invalid HTTP requests gracefully.

Contact either @lgalabru or @CharlieC3 for more info.

[Some details can be found here](https://discord.com/channels/621759717756370964/816365424349282334/857652592724803594).

**Expected behavior**
The API should be able to handle malicious or invalid HTTP requests gracefully.

**Screenshots**
Contact either @lgalabru or @CharlieC3 for more info.

**Console log**
Contact either @lgalabru or @CharlieC3 for more info.

**Additional context**
API version `0.61.0`

**Comment by asimm241** [comment]
As far as the specific issue **I am unable to reproduce issue on my end , It crashes the server but the service never went down.** 

After R&D I propose the following changes: 
### nginx changes

- add rate limiter 
- add_header `X-Content-Type-Options : nosniff.` 
- add_header `Content-Security-Policy "default-src 'self'"`. 

- blacklist IPs for multiple invalid api request: not sure if we can handle it at inginx

### app changes
- add a generic route to handle all invalid routes and method gracefully
- disable x-powered-by

As per npm security advisory https://www.npmjs.com/advisories 
The following dependencies should be updated to avoid potential attacks. 

- [prisms](https://www.npmjs.com/advisories/1762) 
- [set-getter](https://www.npmjs.com/advisories/1759) 
- [normalize-url](https://www.npmjs.com/advisories/1755) 
- [css-what](https://www.npmjs.com/advisories/1754)
- [trim-newlines](https://www.npmjs.com/advisories/1753)  
- [glob-parent](https://www.npmjs.com/advisories/1751)  
- [ws](https://www.npmjs.com/advisories/1748)
- [browserslist](https://www.npmjs.com/advisories/1747)

cc: @zone117x @CharlieC3

**Comment by asimm241** [comment]
@CharlieC3 I took the basic request `/extended/v1/tx/0x[object%20Object]` and tried some fuzzing and see if the API went down.

**Comment by CharlieC3** [comment]
Small update: Discussed with Asim on Discord and Zoom. It seems 1 out of 2 malicious URLs do not cause a crash, but the other consistently does. Asim has narrowed down where this may be happening and is working on applying a patch.

**Comment by agraebe** [comment]
this can be closed now, right?

**Comment by asimm241** [comment]
> As far as the specific issue is concerned **I am unable to reproduce the issue on my end, It crashes the server but the service never went down.**
> 
> After R&D I propose the following changes:
> 
> ### nginx changes
> * add rate limiter
> * add_header `X-Content-Type-Options : nosniff.`
> * add_header `Content-Security-Policy "default-src 'self'"`.
> * blacklist IPs for multiple invalid API requests: not sure if we can handle it at inginx
> 
> ### app changes
> * add a generic route to handle all invalid routes and methods gracefully
> * disable x-powered-by
> 
> As per npm security advisory https://www.npmjs.com/advisories
> The following dependencies should be updated to avoid potential attacks.
> 
> * [prisms](https://www.npmjs.com/advisories/1762)
> * [set-getter](https://www.npmjs.com/advisories/1759)
> * [normalize-url](https://www.npmjs.com/advisories/1755)
> * [css-what](https://www.npmjs.com/advisories/1754)
> * [trim-newlines](https://www.npmjs.com/advisories/1753)
> * [glob-parent](https://www.npmjs.com/advisories/1751)
> * [ws](https://www.npmjs.com/advisories/1748)
> * [browserslist](https://www.npmjs.com/advisories/1747)
> 
> cc: @zone117x @CharlieC3

@zone117x do we need to do something about?

**Comment by CharlieC3** [comment]
@asimm241 I've created an internal issue to review the nginx suggestions you made above. Thanks again for them!
