### ISSUE TITLE
Integrate live production profiling

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#641]
Implement the ability to enable live application profiling (toggled with an env var, process signal, config file, etc).

Ideally the outcome would be a way to see something like a flame graph that shows source line numbers and fully supports CPU and wall time for async functions. Memory allocation visualization would also be helpful.

A cursory overview shows some promising free/open-source options, as well as some paid options:
* Node.js built-in `inspector` https://nodejs.org/api/inspector.html
* Clinic https://www.npmjs.com/package/clinic
* Raygun AMP https://www.npmjs.com/package/raygun-apm
* Instana https://www.npmjs.com/package/@instana/collector

Ideally this repo would only add a dependency to something free and open source that exported profiler data in a generic fashion, then infrastructure like Hiro could have a custom setup to ingest the data to anything specific to our deployment or to one of the paid services.

/cc @CharlieC3 @wileyj feel free to comment with any other options, suggestions, requirements, preferences

**Comment by CharlieC3** [comment]
Ideally the tracing metrics generated would be compatible to be displayed in Grafana. Grafana's open source distributed tracing backend is called [Tempo](https://github.com/grafana/tempo), which uses Jaeger internally. It seems OpenTelemetry generates tracing reports that can be fed into Tempo and displayed in Grafana seamlessly with [this lib](https://github.com/mnadeem/nodejs-opentelemetry-tempo).

There may be other ways to integrate distributed traces into Grafana, but this seemed to be one of the more popular choices for the tools we use.

**Comment by MHassanTariq** [comment]
[Jaeger](https://www.jaegertracing.io/docs/1.26/) with [OpenTelemetry](https://opentelemetry.io/) is also an option. However, [Jaeger UI doesn't provide FlameGraph](https://github.com/jaegertracing/jaeger-ui/issues/525) but it does provide details to the span of functions.
Using [Tempo](https://github.com/grafana/tempo) is a good approach, but [Grafana](https://grafana.com/) is paid.
Let me know which approach is preferred.

**Comment by CharlieC3** [comment]
@MHassanTariq I believe only Grafana Cloud or Enterprise support has a fee to it. Self-managed Grafana is [open source](https://github.com/grafana/grafana) and is free to use (that's what Hiro uses), so we'd prefer an implementation that generates reports which can be ingested by Tempo.

**Comment by zone117x** [comment]
This looks interesting if we go the OpenTelemetry route https://www.npmjs.com/package/@opentelemetry/instrumentation-pg
Related to https://github.com/blockstack/stacks-blockchain-api/issues/738 /cc @rafaelcr

**Comment by rafaelcr** [comment]
Thanks for the tip @zone117x , I was actually looking at this solution: https://github.com/prometheus-community/postgres_exporter which would be on top of our current Prometheus configuration. I'd love to see what @CharlieC3 this of something like this (more instructions at https://promcat.io/apps/postgresql#SetupGuide)

**Comment by CharlieC3** [comment]
The postgres exporter would definitely be useful I think in our infra, but it wouldn't serve as a substitution for live profiling in the API. Not sure if that's what you were implying :)

**Comment by MHassanTariq** [comment]
@CharlieC3 I'm using [OpenTelemetry Metrics](https://www.npmjs.com/package/@opentelemetry/metrics) for generating metrics and [OpenTelemetry Auto Instrumentations Node](https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node) for generating traces. For exporting our traces and metrics, I use [OpenTelemetry Exporter Collector](https://www.npmjs.com/package/@opentelemetry/exporter-collector). 
OpenTelemetry Exporter exports data in [OTLP](https://github.com/open-telemetry/oteps/blob/main/text/0035-opentelemetry-protocol.md), [which can be ingested by Tempo](https://grafana.com/docs/tempo/latest/operations/architecture/#distributor). Does this approach look good to you?
cc: @zone117x

**Comment by CharlieC3** [comment]
@MHassanTariq We already use the Prometheus library to export metrics. Is OpenTelemetry Metrics easier to use or better than Prometheus in some way? Or does it make more sense to use OpenTelemetry Metrics since we'd use OpenTelemetry for its traces?

If it makes more sense to use OT Metrics and remove the Prometheus library from the API's code, I wouldn't oppose as long as we're still able to track the same metrics.

@wileyj Do you have any comments you'd like to add?

What you're using for tracing and exporting sounds good and should work for us.

**Comment by wileyj** [comment]
To change this to Opentelemetry vs the current prometheus library is a @zone117x @rafaelcr discussion. the metrics collected will essentially be the same. 

for the tracing, using this library is perfectly fine.

**Comment by MHassanTariq** [comment]
@CharlieC3 the only problem I face with OpenTelemetry Matrices is that there is not any auto instrumentation tool for metrices, unlike [auto-instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node) for traces.
As far as setup is concerned, it is as easy as Prometheus.

So far, my traces read as:
```
{
  traceId: '8ec994dcbe0c6d01bf8ec51e692d1ed1',
  parentId: '508dcf1eb022d0fd',
  name: 'request handler - /new_block',
  id: '0b85ec04a0fdcf60',
  kind: 0,
  timestamp: 1631535736747403,
  duration: 23,
  attributes: {
    'http.route': '/new_block',
    'express.name': '/new_block',
    'express.type': 'request_handler'
  },
  status: { code: 0 },
  events: []
}
```

and for my metrices, I just log the number of each request counted for now:
```
{
  name: 'requests-counter',
  description: 'Count all incoming requests',
  unit: '1',
  metricKind: 0,
  valueType: 1
}
{ route: '/extended/v1/status' }
value: 2
```

**Comment by CharlieC3** [comment]
@MHassanTariq yeah when it comes metrics libraries it seems most (or all) of them are manual implementations since they're bound to the application's logic whereas traces operate at a lower level and don't need to know about high-level business logic.

Very cool! Interested to hear @zone117x and @rafaelcr thoughts on the above, including replacing the prometheus metrics lib for the OpenTelemtry lib.

**Comment by MHassanTariq** [comment]
@CharlieC3 Do we have a Tempo server where I can export my traces to?
cc: @zone117x @rafaelcr

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/821
