### ISSUE TITLE
Ability to run the API in a read-only mode

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#642]
The API currently must be ran in a mode that handles both writing (consuming event-emitter data and performing postgres updates) and reading (serving the public API requests). 

It would be useful if the API could be ran in a read-only mode where it's only responsible for serving API requests. It would only perform postgres reads, and would not require running alongside an event-emitter stacks-node.

These read-only instances could be easily spun up and load balanced. A single write-mode instance would be populating the postgres db, and multiple read-mode instances could read from the db.

An initial point of complexity that comes to mind is supporting client-push (i.e. websockets / socket.io) when in read-only mode. The way it currently works is that the datastore class emits events on writes, which are picked up by the socket.io handler to send updates to clients. This EventEmitter mechanism could be replaced with a postgres LISTEN/NOTIFY system. This lib looks promising https://www.npmjs.com/package/pg-listen.

/cc @CharlieC3 @wileyj for any comments, suggestions

**Comment by CharlieC3** [comment]
> supporting client-push (i.e. websockets / socket.io) when in read-only mode

Would this need to be supported? A read-only API would not have a stacks-node emitting events to it, so I would think the stacks-node would not be able to connect to a read-only API.

Additionally, any API in read-only mode would need another ENV variable to tell it where it can reach a read/write API node. All load-balanced APIs will be behind the same public VIP/subdomain, so a read-only API may receive some HTTP POSTs, and will have to be able to redirect them internally to the known read/write API node's _internal_ address.

```
HTTP POST
-------------> read-only API
                    |
                    |
                    V           writes
             read/write API   ----------> DB
```


Under extremely high traffic, this would also give us the option to _only_ expose read-only APIs on a subdomain and have them internally forward write requests to a private read/write API.

**Comment by zone117x** [comment]
> Would this need to be supported? A read-only API would not have a stacks-node emitting events to it, so I would think the stacks-node would not be able or need to connect to a read-only API.

So the problem is clients (e.g. the wallet, explorer, etc) that open a websocket "read" request to the API, and the API needs to push data updates to these clients as they happen. At the moment, a naive implementation of a read-only API instance could not power these websocket notifications, because they are triggered by the API's db write code path. It's certainly possible and reasonable I think to implement the postgres LISTEN/NOTIFY system to fix this.
