### ISSUE TITLE
Search endpoint docs/types broken

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#645]
https://github.com/blockstack/stacks-blockchain-api/blob/cab3ab93b96852fcea748d24909f23e5a57e9465/docs/openapi.yaml#L1279-L1285

😬

**Comment by asimm241** [comment]
@zone117x as I have understood from this issue, we need to update the schemas for search as per [these types](https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/search.ts#L19) ?

**Comment by zone117x** [comment]
@asimm241 yes that is correct

**Comment by MHassanTariq** [comment]
I'm working on this issue.

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/727
