### ISSUE TITLE
REQUEST/QUESTION: Connect to api db via ssl

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain-api#653]
**Is your feature request related to a problem? Please describe.**
I would like to connect from the event server to the event db via ssl.  I do not see a way to configure this in any of the available examples/configs.

**Describe the solution you'd like**
Maybe an env variable `SSL=true` that would append `?ssl=true` to the connection string 

**Describe alternatives you've considered**
Turning off db ssl is one option, but seems like a bad one.

**Additional context**
Although my connections are on a private network, I still want the communication via ssl.  This is not for a public endpoint.

**Comment by whoabuddy** [comment]
I tried walking backwards through the code and may have an idea, but would definitely love some input from those more knowledgeable to see if I'm going in the right direction. @zone117x @CharlieC3 @wileyj 

Based on the `connect()` function here, the `ClientConfig` is what's used to connect to the pg db on line 1094 and 1096.

https://github.com/blockstack/stacks-blockchain-api/blob/9ec64ad13403a7e82e6aa5d3648a17cb3133c809/src/datastore/postgres-store.ts#L1087-L1097

The `ClientConfig` is built from the `.env` file here:

https://github.com/blockstack/stacks-blockchain-api/blob/9ec64ad13403a7e82e6aa5d3648a17cb3133c809/src/datastore/postgres-store.ts#L68-L77

But there is no option to add the optional `ssl?: boolean` value [defined here](http://definitelytyped.org/docs/pg--pg/interfaces/pg.clientconfig.html#ssl).

So my theory is: add a line to the `getPgClientConfig()` function that checks for the SSL value in `.env`:

```
export function getPgClientConfig(): ClientConfig {
  const config: ClientConfig = {
    database: process.env['PG_DATABASE'],
    user: process.env['PG_USER'],
    password: process.env['PG_PASSWORD'],
    host: process.env['PG_HOST'],
    port: parsePort(process.env['PG_PORT']),
    ssl: process.env['PG_SSL'],        <------- new
  };
  return config;
}
```

Then add `PG_SSL=true` to the `.env` file?

**Comment by zone117x** [comment]
@whoabuddy's suggestion makes sense to me, and is the least disruptive. 
Another approach is adding support for "connection URIs" https://node-postgres.com/features/connecting#connection-uri
So all the `PG_*` env vars could be replaced by a `PG_CONNECTION_URI`.

Supporting both options (a new `PG_SSL`, and `PG_CONNECTION_URI`) seems like a good idea. Any takers?

**Comment by whoabuddy** [comment]
Opened a draft PR with more questions than answers :upside_down_face:

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/666
