### ISSUE TITLE
[Rosetta] account/balance endpoint errors when both block hash and index are included in request

### ISSUE THREAD

**Issue by shermanxiong** [blockstack/stacks-blockchain-api#667]
**Describe the bug**
The `v1/rosetta/account/balance` endpoint errors when the request includes both `index` and `hash` in the `block_identifier` object.
Eg:
```
"block_identifier": {
      "index": 730,
      "hash": "0x713a55efa8848517d44e3e4ef9ddb6b64751fa8f1af5759195ce412f0702df0e"
 }
```

When only `index` is supplied, it works fine, or when only `hash` is supplied, it works fine but not when both are.

## Example Request
```
curl --location --request POST 'https://stacks-node-api.testnet.stacks.co/rosetta/v1/account/balance' --header 'Content-Type: application/json' --data-raw '{
    "network_identifier": {
        "blockchain": "stacks",
        "network": "testnet"
    },
     "account_identifier": {
        "address": "ST1NPTQX1XZHGG9S50RGQCT4TAF147D7JD21PQEVQ",
        "metadata": {}
    },
    "block_identifier": {
      "index": 730,
      "hash": "0x713a55efa8848517d44e3e4ef9ddb6b64751fa8f1af5759195ce412f0702df0e"
    }
}'
```

## Expected Response
when omitting `block_identifier` entirely or having one of either `index` or `hash` but not both, the expected response is returned.
```
{
  "block_identifier": {
    "index": 730,
    "hash": "0x713a55efa8848517d44e3e4ef9ddb6b64751fa8f1af5759195ce412f0702df0e"
  },
  "balances": [
    {
      "value": "500000000",
      "currency": {
        "symbol": "STX",
        "decimals": 6
      }
    }
  ],
  "metadata": {
    "sequence_number": 0
  }
}
```

## Actual Response
only when including both `index` and `hash` in the `block_identifier` does this error message happen
```
{
  "code": 606,
  "message": "Invalid block hash.",
  "retriable": true
}
```

**Comment by diwakergupta** [comment]
cc/ @asimm241 

I think the bug manifests here if both properties are set: https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/account.ts#L62

**Comment by asimm241** [comment]
> cc/ @asimm241
> 
> I think the bug manifests here if both properties are set: https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/account.ts#L62

Yes, it is happening because of this line. It should be fixed in this another PR from `zondax` guys. 
https://github.com/blockstack/stacks-blockchain-api/pull/613/files

**Comment by zone117x** [comment]
Should be closed by https://github.com/blockstack/stacks-blockchain-api/pull/689
