### ISSUE TITLE
Incorrect tx_status after error

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#671]
**Describe the bug**
The `tx_status` of https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x38e2f50a4c410e2835a3497d0a7f68c2e81150a3f95956333c31d7b68beb647b?chain=mainnet  is shown as `abort_by_post_condition`. However, the tx result is `(err u5)`.

**Comment by zone117x** [comment]
@friedger can you describe the behavior you expected to see?

**Comment by friedger** [comment]
@zone117x I's expect `abort_by_response`

**Comment by zone117x** [comment]
The abort reason comes directly from the stacks-node, the API doesn't do any transformations or decision overriding around this. You may want to open this issue in the blockchain repo.
