### ISSUE TITLE
[Rosetta][Construction-API][feature] pass in valid BTC address for constructing stacking transaction

### ISSUE THREAD

**Issue by shermanxiong** [blockstack/stacks-blockchain-api#672]
the entire transaction construction flow:
`/preprocess` -> `/metadata` -> `/payloads` -> etc
needs to be able to handle passing in and using valid BTC address for constructing a stacking transaction to tell the it to send BTC rewards to that address for that stacking cycle.

This is so we can specify the BTC reward address to stack. Right now looking at `/payloads` it looks like the bitcoin address cannot be passed in and uses the BTC address that is converted from the key that made the STX address of the stacker.
https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/construction.ts#L582-L585

The stack-stx contract should be able to take in a specified BTC address: https://docs.stacks.co/references/stacking-contract#stack-stx

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/688
