### ISSUE TITLE
[Rosetta][Construction-API][bug] /payloads will always error when constructing a stacking transaction

### ISSUE THREAD

**Issue by shermanxiong** [blockstack/stacks-blockchain-api#673]
Since there is no token_transfer_recipient_address when constructing a stacking transaction, I believe /payloads will always error here:
https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/construction.ts#L532-L536

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/682
