### ISSUE TITLE
[Rosetta][Construction-API][bug] constructing stacking tx using /preprocess not offline

### ISSUE THREAD

**Issue by shermanxiong** [blockstack/stacks-blockchain-api#674]
when sending a stacking operation for constructing a transaction using /preprocess using the OFFLINE stacks API, it errors with
```
"error": "FetchError: request to http://127.0.0.1:20443/v2/contracts/interface/ST000000000000000000002AMW42H/pox failed, reason: connect ECONNREFUSED 127.0.0.1:20443" 
```
meaning that this is not offline as its trying to connect to the node.

/preprocess endpoint needs to be entirely offline, ie. cannot connect to the node.

I suspect it might be due to when creating a dummy stacking transaction: https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/construction.ts#L205-L214

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/679
