### ISSUE TITLE
Add endpoint for `block` by burn block height or burn block hash

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#675]
**Is your feature request related to a problem? Please describe.**
I would like to find the stacks block that was mined at a certain burn block that includes a certain burn tx.

**Describe the solution you'd like**
Similar to `block/by_height/1234`, I would like to call `block/by_burn_block_height/4566` and `block/by_burn_block_hash/0x01234`

**Describe alternatives you've considered**
Wait for 2.1 and query a smart contract using `get-burn-block-info?` (https://github.com/blockstack/stacks-blockchain/pull/2770) 

**Additional Context**
PoX transactions contain the stacks block in the OP_RETURN, however, I would like to handle any tx for catamaran swaps.

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/676
