### ISSUE TITLE
Better messaging/return code around "TooMuchChaining"

### ISSUE THREAD

**Issue by wileyj** [blockstack/stacks-blockchain-api#677]
From the web wallet: "Broadcast error: "transaction rejected - TooMuchChaining"

and the dev console when someone attempted to POST to the testnet faucet (while the mempool was full):
![image](https://user-images.githubusercontent.com/2847772/127214244-d2912bd7-cdb6-4ceb-b0bd-bab2ccf94d76.png)

Currently, if we're getting that error back from the stacks-node, it's returning a `500` and the message isn't exactly descriptive about what to do next. 

I propose adding a specific return code (that in turn the wallet(s) know how to address):
example:
HTTP status: `510` (or a 4XX status is also reasonable, there is no precedent here). 
Message: "...transaction rejected... what to do next"

These errors seem to come from the middleware, so to add something like this would be more of a custom response to specific events, but i feel it would help answer questions when certain things happen.

**Comment by zone117x** [comment]
I'm not sure what to do here. When the API gets a valid response from the stacks-node (including valid error responses like TooMuchChaining), it proxies it along. 

The API _does_ already check the stacks-node error response type in order to determine if nonce-incrementing logic should be attempted, so already precedent there. However, this is essentially a work around the API performs due to the stacks-node not supporting returning a "real" next nonce that accounts for the mempool. 

The API _could_ extend this work around to send a custom response, but in this case I'm not sure what "return code that in turn the wallet(s) know how to address" would be. The recent testnet faucet issue resulting in `TooMuchChaining` has no work around for a wallet, nothing that a wallet could programmatically address.

I think wallets (or any faucet client) needs to handle 3 scenarios:
1. Tx success, happy path.
2. Tx denied because of rate limiting, UI should indicate you are rate limited.
3. Unexpected error, report to faucet maintainers. Doesn't really matter what the error is.

**Comment by wileyj** [comment]
the message itself probably isn't relevant here - but in cases like this, if we were to add a specific HTTP status like `510` vs the current and nebulous `500` - downstream services like a wallet could see that return and craft a custom message if applicable.
could that be done on the stacks-blockchain side vs the api? sure, i can see the case for moving it there. if this would add too much customization, we can explore doing it in that repo and then the API wouldn't have to change to address errors like this (while still allowing downstream consumers to message specifically based on status codes)

**Comment by zone117x** [comment]
If simply adding a `if (TooMuchChaining) return 510` helps, I'm not opposed to adding it. It's a couple lines, no prob.

I'd just note this is essentially extending the work-around in the API, and it's likely a future error condition will not be the same TooMuchChaining error.

**Comment by wileyj** [comment]
I see your point - i'd say let's hold off for now. i'll look at the stacks-blockchain code and see if it makes more sense to try to do something there.

**Comment by zone117x** [comment]
👍 
For context, here's the API code for the bit of error handling to do the brute-force nonce-incrementing technique: https://github.com/blockstack/stacks-blockchain-api/blob/22e9a4f64f093fd9982dde570e18278b65e4b934/src/api/routes/faucets.ts#L228-L239

**Comment by zone117x** [comment]
@wileyj btw the while the API sends over the stacks-node response in the __payload__, it does not mirror/proxy the http response code.

In this example, the http response payload looks like:
```
$ curl -L -d POST https://stacks-node-api.testnet.stacks.co/extended/v1/faucets/stx?address=ST2CCPXP84PQCVQF3YTEQJ43GDYA6H3Z8BAT2EEGR
{"error":"Error: Response 400: Bad Request fetching http://stacks-node-follower-green.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"TooMuchChaining\",\"reason_data\":{\"actual\":450,\"expected\":449,\"is_origin\":true,\"message\":\"Nonce would exceed chaining limit in mempool\",\"principal\":\"ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2\"},\"txid\":\"4c9de3d1485886487bda63b471ef4f5edfc7585923c6287b3b4d302623b2eda4\"}","stack":"Error: Response 400: Bad Request fetching http://stacks-node-follower-green.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"TooMuchChaining\",\"reason_data\":{\"actual\":450,\"expected\":449,\"is_origin\":true,\"message\":\"Nonce would exceed chaining limit in mempool\",\"principal\":\"ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2\"},\"txid\":\"4c9de3d1485886487bda63b471ef4f5edfc7585923c6287b3b4d302623b2eda4\"}\n    at StacksCoreRpcClient.fetchText (/app/src/core-rpc/client.ts:125:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at StacksCoreRpcClient.fetchJson (/app/src/core-rpc/client.ts:104:26)\n    at StacksCoreRpcClient.sendTransaction (/app/src/core-rpc/client.ts:165:20)\n    at /app/src/api/routes/faucets.ts:222:25\n    at run (/app/node_modules/p-queue/dist/index.js:163:29)","errorTag":"4d2e5bd7-1584-4667-991a-e1be6b436e75"}
```

But the API's http response is still 500. I can definitely make the API mirror the status code (400 in this case) if that helps.

**Comment by wileyj** [comment]
I'm going to close this - we can think about this later on but it's not a priority whatsoever at the moment.
