### ISSUE TITLE
Fast graceful shutdown

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#681]
When shutting down the handlers wait for all client connections to be closed. This causes issues with socket.io/websocket connections that can take hours to close on their own. Especially if the shutdown was caused by an unhandled exception. A critical error can happen, be logged, then not surface any problems for an extended period of time.

The shutdown handlers should give client connections a few seconds to close then force close them if necessary.

**Comment by CharlieC3** [comment]
I think I have this mentioned in another ticket somewhere, but shutdowns should also result in the main process dying. Currently when the API shuts down, the ports are closed but the main process never dies. If the main process dies, K8s can restart the pod and the API would recover in a short amount of time.

**Comment by zone117x** [comment]
Process should die from https://github.com/blockstack/stacks-blockchain-api/blob/d112c4c9e5d0ee3393a217b22429080c688fd7bb/src/shutdown-handler.ts#L26-L29
AFAIK there's no escaping [`process.exit`](https://nodejs.org/api/process.html#process_process_exit_code).

My guess is the code is never reached because there's always a registered handler (like websocket client waits) that have maybe never completed so far.
