### ISSUE TITLE
Represent value transfer operations with type "token_transfer" instead of "contract_call"

### ISSUE THREAD

**Issue by pablojorge** [blockstack/stacks-blockchain-api#683]
When tokens are moved in the context of a contract call, like [in this case](https://explorer.stacks.co/txid/0xe0f00221eb8b802dd848fa3c1cdfb755c8b7ef3f9cc21cf8781eac71dd98f0dd?chain=mainnet), where 19 STX were moved from `SP1SEV44PF93QAXVA3G4NDDNW9REDBXVCZ5T1VB3Y` to `SP1GHG0TPP2ZMSZJ0M5VVMJCAFV9SQXJ5HWR6KX6T` the Rosetta response includes 4 operations:
- 1 `fee` op
- 1 `contract_call` op (with the info about the call itself)
- 2 `contract_call` ops, with the transfer amounts (negative for the sender, positive for the receiver)

Shouldn't the last 2 operations have type=`token_transfer`? That way, by filtering by that type, clients can always detect value-transfer operations, for both plain transfers and as the side effect of a contract call. Otherwise, clients must filter both `token_transfer` and `contract_call` types, only considering the 2nd one when there is an amount set in the operations (to ignore the call operation itself)

Full dump:
```json
{
    "transaction_identifier": {
      "hash": "0xe0f00221eb8b802dd848fa3c1cdfb755c8b7ef3f9cc21cf8781eac71dd98f0dd"
    },
    "operations": [
      {
        "operation_identifier": {
          "index": 0
        },
        "type": "fee",
        "status": "success",
        "account": {
          "address": "SP1SEV44PF93QAXVA3G4NDDNW9REDBXVCZ5T1VB3Y"
        },
        "amount": {
          "value": "-265",
          "currency": {
            "decimals": 6,
            "symbol": "STX"
          }
        }
      },
      {
        "operation_identifier": {
          "index": 1
        },
        "type": "contract_call",
        "status": "success",
        "account": {
          "address": "SP1SEV44PF93QAXVA3G4NDDNW9REDBXVCZ5T1VB3Y",
          "sub_account": {
            "address": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo",
            "metadata": {
              "contract_call_function_name": "send-many",
              "contract_call_function_args": "0x000000010b000000010c00000003046d656d6f020000000002746f051661180356b0bf4cfe40a177ba498a7ed39bf6458f0475737478010000000000000000000000000121eac0",
              "raw_result": "0x0703"
            }
          }
        }
      },
      {
        "operation_identifier": {
          "index": 2
        },
        "type": "contract_call",
        "status": "success",
        "account": {
          "address": "SP1SEV44PF93QAXVA3G4NDDNW9REDBXVCZ5T1VB3Y"
        },
        "amount": {
          "value": "-19000000",
          "currency": {
            "decimals": 6,
            "symbol": "STX"
          }
        },
        "coin_change": {
          "coin_action": "coin_spent",
          "coin_identifier": {
            "identifier": "0xe0f00221eb8b802dd848fa3c1cdfb755c8b7ef3f9cc21cf8781eac71dd98f0dd:2"
          }
        }
      },
      {
        "operation_identifier": {
          "index": 3
        },
        "related_operations": [
          {
            "index": 2
          }
        ],
        "type": "contract_call",
        "status": "success",
        "account": {
          "address": "SP1GHG0TPP2ZMSZJ0M5VVMJCAFV9SQXJ5HWR6KX6T"
        },
        "amount": {
          "value": "19000000",
          "currency": {
            "decimals": 6,
            "symbol": "STX"
          }
        },
        "coin_change": {
          "coin_action": "coin_created",
          "coin_identifier": {
            "identifier": "0xe0f00221eb8b802dd848fa3c1cdfb755c8b7ef3f9cc21cf8781eac71dd98f0dd:3"
          }
        }
      }
    ]
  }
```

**Comment by zone117x** [comment]
Seems reasonable to me, assuming it doesn't violate the rosetta spec in some strange way. We have quite a backlog of higher priority issues though, so PRs definitely welcome! Otherwise I don't think this will be done for a while.

**Comment by shermanxiong** [comment]
> Shouldn't the last 2 operations have type=token_transfer? That way, by filtering by that type, clients can always detect value-transfer operations, for both plain transfers and as the side effect of a contract call. Otherwise, clients must filter both token_transfer and contract_call types, only considering the 2nd one when there is an amount set in the operations (to ignore the call operation itself)

yes that sounds correct to me

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/728
