### ISSUE TITLE
[Rosetta][Construction]  /payloads always return error on contract_address and contract_name

### ISSUE THREAD

**Issue by asimm241** [blockstack/stacks-blockchain-api#684]
**Describe the bug**
In rosetta construction `/payloads` api will always fails due to the following checks 
- https://github.com/blockstack/stacks-blockchain-api/blob/d112c4c9e5d0ee3393a217b22429080c688fd7bb/src/api/routes/rosetta/construction.ts#L601

- https://github.com/blockstack/stacks-blockchain-api/blob/d112c4c9e5d0ee3393a217b22429080c688fd7bb/src/api/routes/rosetta/construction.ts#L605

**To Reproduce**
`/payloads` will always fail 

Suggested Solution: 
Provide `contract_name` and `contract_address` in the metadata as we already do for `number_of_cycles`
https://www.rosetta-api.org/docs/ConstructionApi.html#constructionpayloads

**Comment by zone117x** [comment]
@asimm241 I think you should go with your suggested solution for now if that unblocks the Rosetta workstream(s). 

@shermanxiong do you have any guidance on if the solution makes sense?

**Comment by shermanxiong** [comment]
the flow of endpoints calls for constructing a Rosetta transaction follows this flow :
1. make a request to `construction/preprocess` with the proper `operations`
2. The `options` object returned from `construction/preprocess` will be sent to the `/construction/metadata` endpoint UNMODIFIED by the caller
3. the `operations` and the `metadata` object returned by `construction/metadata` endpoint will be sent to `construction/payloads` 

So if `construction/metadata` returns `contract_name` and `contract_address` in the `metadata` field, then it should be included in `construction/payload` as well

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/687
