### ISSUE TITLE
[Rosetta] /account/balance returning increased sequence_number before transaction lands on-chain

### ISSUE THREAD

**Issue by shermanxiong** [blockstack/stacks-blockchain-api#718]
## Versions
API version: [v0.64.1](https://github.com/blockstack/stacks-blockchain-api/releases/tag/v0.64.1)
Node version: `2.0.11.2.0`

## Description
When creating and submitting a transaction, we expect that the `sequence_number` for that account is increased by 1 _after_ the transaction lands on-chain. However, on this version of API, I've found that it may increase the sequence number _before_ the transaction lands on-chain. I have not encountered this behaviour in any previous versions before (have been using `v0.63.1` for testing this week).

Our services frequently check `/account/balance` and compare internally saved balance and sequence number with what's returned by the endpoint. And if there is a discrepancy with no detected transaction that caused the discrepancy, we quarantine the address. API version `v0.64.1` caused all of our test addresses to be quarantined right after sending a transaction. When we reverted to API version `v0.63.1`, and sent more test transactions, addresses stopped being quarantined right after sending a transaction. This is what leads me to believe `v0.64.1` may have a bug.

## Context:
- Using this testnet account to send transactions: [STN82AQ8HG55ZFY7F5PE73GVDXM9Y51FYXVRV290](https://explorer.stacks.co/address/STN82AQ8HG55ZFY7F5PE73GVDXM9Y51FYXVRV290?chain=testnet)
- this `token_transfer` [transaction](https://explorer.stacks.co/txid/0xe38cbada56fa79324222ccf2737f5fb4917175374ea7d00f453f321d53105372) mined at block 6022 should have increased the `sequence_number` from `3` to `4`
- this subsequent `token_transfer` [transaction](https://explorer.stacks.co/txid/0xcbe14771e028e168ac14b8bc9fd5a0cae0e437ace9f9c51e0b683586e131cfbb) mined at block 6024 should have increased the `sequence_number` from `4` to `5`

### /account/balance request
```
curl --location --request POST 'localhost:3007/rosetta/v1/account/balance' --header 'Content-Type: applicationjson' --data-raw '{
  "network_identifier": {
      "blockchain": "stacks",
      "network": "testnet"
  },
    "account_identifier": {
      "address": "STN82AQ8HG55ZFY7F5PE73GVDXM9Y51FYXVRV290",
      "metadata": {}
  }
}'
```

###  /account/balance called when testnet had height 6023 => sequence_number=5 [incorrect, somehow already updated]
```
{
  "block_identifier": {
    "index": 6023,
    "hash": "0x0acc180402177ca7727b7c5524578619a6f3af97b3145251524a25edf6912da5"
  },
  "balances": [
    {
      "value": "30224555",
      "currency": {
        "symbol": "STX",
        "decimals": 6
      }
    }
  ],
  "metadata": {
    "sequence_number": 5
  }
}
```

###  /account/balance called when testnet had height 6024 => sequence_number=5 [stayed the same]
```
{
  "block_identifier": {
    "index": 6024,
    "hash": "0xea65eddcd07823088d15c3b72ae6fcc5466bc9d65eeee2d7367bd8a22ccb1a33"
  },
  "balances": [
    {
      "value": "21460593",
      "currency": {
        "symbol": "STX",
        "decimals": 6
      }
    }
  ],
  "metadata": {
    "sequence_number": 5
  }
```

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/719
