### ISSUE TITLE
Certain transaction endpoints can be very slow

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#725]
I noticing some pretty significant slow downs with this endpoint: https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP000000000000000000002Q6VF78.pox/transactions?limit=50&offset=250, it's intermittent, but reproducible. If you change the offset to random numbers, i've been getting load times over 15 seconds. I've also pretty consistently been getting 524 status code from it.

![Screen Shot 2021-08-25 at 3 11 35 PM](https://user-images.githubusercontent.com/11803153/130862561-c182c38a-207b-49fe-a3e8-03d3d64f85ca.png)

Some extra context from chat:

> mattlittle — Today at 3:19 PM
note: there's definitely a missing optimization / borked sql query behind the endpoint for https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP000000000000000000002Q6VF78.pox/transactions
it's on my todo list

> jw — Today at 3:31 PM
not sure - but something definitely seems to be going on with the API
resources are all OK, DB also appears fine from a resource persepctive
howerver, mattlittle that transactions JOIN is horrendous on the DB load
the query itself from time it's run to the time it's returned is reporting an avg of 8s
this is just the query at the DB layer
this query has also been called a few thousands times over the past hour

@wileyj is it possible to add some additional specific urls for monitoring (if we don't have them already)? I think it'd be helpful to add some popular addresses/contracts to our monitoring to replicate more real-world data.

**Comment by dantrevino** [comment]
+1 for special attention to transactions and nft_events

**Comment by zone117x** [comment]
@dantrevino got any example URLs that are slow for you? That would be helpful for optimizing

**Comment by whoabuddy** [comment]
Noting that I saw this in trying to load the [miamicoin-token](https://explorer.stacks.co/txid/0xc513b769c261233865c43f101438bd6359636ecacfe34576e6424d6c2629174e?chain=mainnet) contract, the first two tries timed out with the error below (also highlighted what I see in the network tab), third try it loaded really fast.

file:///home/whoabuddy/Pictures/Screenshot%20from%202021-09-02%2012-28-56.png

Note that the 250ms shown there != the 15s or so I waited before the error came up and the network tab populated with info.

I've also seen a similar patter on the [Recent Blocks](https://explorer.stacks.co/blocks?chain=mainnet) page.

**Comment by dantrevino** [comment]
Boom client apps pull from https://${BASE_API_URL}/extended/v1/address/${STX_ADDRESS}/transactions?limit=50&offset=${PAGE}
and 
https://${BASE_API_URL}/extended/v1/address/${STX_ADDRESS}/nft_events?limit=50&offset=${PAGE}

We default to the max page size of 50 because we have a lot of folks with multiple NFT series

**Comment by zone117x** [comment]
These performance issues should be fixed. Please comment if anyone notices any `/extended` endpoints are still taking longer than ~1 second to load.
