### ISSUE TITLE
New competitive fee endpoint

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-blockchain-api#729]
Per the requirement to set higher fees, the API should expose an additional endpoint that contains fee rate information for clients.

This is preferable to hard coding in our client apps, as updates would require us to go through the slow release cycles.

The simplest implementation of this would be an endpoint with the schema:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "FeeRate",
  "type": "object",
  "additionalProperties": false,
  "required": ["fee_rate"],
  "properties": {
    "fee_rate": {
      "type": "integer"
    }
  }
}
```

**Comment by asimm241** [comment]
@zone117x What I understand from the issue is we will add a new endpoint `extended/v1/fee_rate` in the API which will fetch the `fee_rate` from RPC client using `v2/fees/transfer` and return it in the above-mentioned format., right?

**Comment by kyranjamie** [comment]
No. The aim is to return a hard-coded fee value, not the value coming from the node itself.

**Comment by asimm241** [comment]
@kyranjamie  What should be the value?

**Comment by kyranjamie** [comment]
> What should be the value?

Sorry, missed this. Discussion in PR

**Comment by Eshwari007** [comment]
@kyranjamie 
I do not see the setting option as we see in WW and testing concludes hard coded value as fee.
Attaching the screenshot for your input if this is as per design
<img width="504" alt="Screen Shot 2021-09-08 at 4 49 13 PM" src="https://user-images.githubusercontent.com/38872890/132583669-916c52ee-2aaf-4653-b006-c52e401d60db.png">
<img width="494" alt="Screen Shot 2021-09-08 at 4 49 26 PM" src="https://user-images.githubusercontent.com/38872890/132583671-27ddd062-e5b6-475a-970c-ed58149d7f58.png">
