### ISSUE TITLE
Return block execution cost data

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#735]
As a followup to https://github.com/blockstack/stacks-blockchain-api/issues/734, it would also be helpful if block data API responses included the total execution cost (should be a simple sum of the execution costs for each tx included in the block).

This can be done in a followup PR and is lower priority, since #734 would allow for clients to calculate this themselves. However, we'd want to implement this directly in the API if the Explorer were to present this data in order to prevent tx endpoints from being hammered.

Total block execution costs should probably be calculated and stored as new columns in the block table (as opposed to adding mildly expensive JOINs to the block sql queries).

**Comment by MHassanTariq** [comment]
@zone117x I'm working on this issue.
