### ISSUE TITLE
add prometheus metrics for postgres queries

### ISSUE THREAD

**Issue by rafaelcr** [blockstack/stacks-blockchain-api#738]
Some of the extended API endpoints are taking a very long time to respond (some even timeout after 60s), for example: https://stacks-node-api.stacks.co/extended/v1/tx?limit=10&type=coinbase&type=token_transfer&type=smart_contract&type=contract_call&unanchored=true

At first sight, it looks like the internal postgres queries could be the bottleneck as they usually involve joining several tables and performing sub-queries to get the required results. In order to determine if that is true, we should add Prometheus metrics that measure the time it takes for queries to complete and in which endpoints they are taking place. This way, we could detect which particular endpoints have problems and work on optimizations.

**Comment by wileyj** [comment]
https://github.com/blockstack/stacks-blockchain-api/issues/725

**Comment by rafaelcr** [comment]
Before adding the instrumentation manually, I've been looking into options and found two that look compelling (thanks @zone117x for pointing me to OpenTelemetry):

1. [Prometheus Postgres Exporter](https://github.com/prometheus-community/postgres_exporter): A Docker container that runs in parallel to Postgres, connects to it, pulls instrumentation, and creates a `/metrics` endpoint for Prometheus consumption.
    - **Upside**: all we'd need to do is have our current Prometheus consume these new metrics
    - **Downside**: we have to run this new container
2. [OpenTelemetry Postgres Instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pg): A node module that collects telemetry from Postgres and makes it available to OpenTelemetry.
    - **Upside**: it's just a node module so it's easy to integrate. It also might be more future-proof if we want to use OpenTelemetry for other kinds of instrumentation (CPU, etc.)
    - **Downside**: I assume more devops work would be necessary to enable and configure OpenTelemetry and start consuming the data

I'd love to see what @CharlieC3 and @wileyj think about these two options or if you have any more suggestions. My opinion is that any of these two would work great because AFAIK they give us very detailed information about pg and its performance.

**Comment by wileyj** [comment]
> Before adding the instrumentation manually, I've been looking for existing options and found two that look compelling (thanks @zone117x for pointing me to OpenTelemetry):
> 
> 1. [Prometheus Postgres Exporter](https://github.com/prometheus-community/postgres_exporter): A Docker container that runs in parallel to Postgres, connects to it, pulls instrumentation, and creates a `/metrics` endpoint for Prometheus consumption.
>    
>    * **Upside**: all we'd need to do is have our current Prometheus consume these new metrics
>    * **Downside**: we have to run this new container
> 2. [OpenTelemetry Postgres Instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pg): A node module that collects telemetry from Postgres and makes it available to OpenTelemetry.
>    
>    * **Upside**: it's just a node module so it's easy to integrate. It also might be more future-proof if we want to use OpenTelemetry for other kinds of instrumentation (CPU, etc.)
>    * **Downside**: I assume more devops work would be necessary to enable and configure OpenTelemetry and start consuming the data
> 
> I'd love to see what @CharlieC3 and @wileyj think about these two options or if you have any more suggestions. My opinion is that any of these two would work great because AFAIK they give us very detailed information about pg and its performance.

The first option is something we had run in the past for local postgres instances. We'll have to see if the same method will work for the API DB.

**Comment by CharlieC3** [comment]
I think both options are needed if we want to paint the full picture and have better traceability of a single API request throughout the system. I would suggest opening a ticket in the devops repo regarding the prom postgres exporter.

**Comment by rafaelcr** [comment]
Closing this issue as we're already looking at it in the devops repo and it looks like it won't involve any code changes in the API. Will reopen if necessary.
