### ISSUE TITLE
Unable to query the stacks-blockchain-api-standalone on 3999

### ISSUE THREAD

**Issue by vishalgupta96** [blockstack/stacks-blockchain-api#740]
hi Team,

We are trying to run stacks-blockchain node and trying to use Rosetta APIs for our project purpose. We have used the instructions provided on this link:
 https://github.com/blockstack/stacks-blockchain-api

I am using the below compose file for starting a node and trying to query it on 3999 but it gives "Recv failure: Connection reset by peer":

Compose file:

`version: '3.3'
services:
    stacks-blockchain-api-standalone:
        ports:
            - '3999:3999'
        volumes:
            - ./data/stacks-blockchain:/root/stacks-node/data
        command:
            - mainnet
        image: blockstack/stacks-blockchain-api-standalone`

Please help as soon as possible as this issue is pending from long,

**Comment by agraebe** [comment]
seems like we're already engaging on the forum to resolve this issue: https://forum.stacks.org/t/blockstack-how-can-i-setup-a-blockstack-full-node-not-testnet/11257/34
