### ISSUE TITLE
Uneven utilization for proxied follower nodes

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain-api#756]
**Describe the bug**
Not sure if this is still an issue, or if it's an issue specific to Hiro's deployment vs. API internals -- opening this issue for tracking.

Last week we observed that when more nodes were added to the proxied followed nodes, traffic did NOT get evenly distributed to the new nodes. In particular, the original set of nodes showed much higher CPU usage than the newer nodes, suggesting that they were still serving the majority of the traffic.

![image](https://user-images.githubusercontent.com/15990/133116093-0ae92c1a-065b-4cde-969a-b78b913f2b4e.png)

At some point @wileyj introduced sticky-connection settings, so that might have been a confounding factor. This was later removed by @CharlieC3 .

What we expect to see is new nodes are added to the proxied load balancer, traffic gets evenly distributed across all nodes.

Also worth considering is whether this load balancing capability should continue to live within the API. An alternative would be the API just has a configurable endpoint that's meant to serve `/v2` endpoints; and this load-balanced endpoint could then live and be managed outside the API.

**Comment by wileyj** [comment]
This may have been a result of the test we did on friday per @zone117x initial request (and subsequently promoted that environment without rolling back those test changes). Things look much better today, but we'll want to double-check the traffic is being spread correctly before closing.

**Comment by CharlieC3** [comment]
If we don't see an improvement this week, I would recommend trying to run the kube-proxy (the service which manages the routing for all internal VIPs) to be ran in [IPVS mode](https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-ipvs).

This mode has been considered stable for a while, and would allow us to route traffic to the backend followers via least connection instead of round-robin. We would have to test this out in the monitoring cluster first.

[More info on IPVS mode can be found here.](https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/)

**Comment by zone117x** [comment]
We should revisit this config https://github.com/blockstack/stacks-blockchain-api/blob/9a7165e3c9a2185684f77145f9d391991981cb82/src/api/routes/core-node-rpc-proxy.ts#L28-L33

A while back we changed the proxy to use keep-alive in an effort to increase performance of the stacks-node's http server, but that may no longer be helpful, and seems like it would contribute to this uneven distribution.

**Comment by wileyj** [comment]
hmm, yeah with more services running i'd say that long keep-alive wouldn't be very useful anymore. 
@CharlieC3 i looked at IPVS as well, but that's a private discussion

**Comment by CharlieC3** [comment]
> A while back we changed the proxy to use keep-alive in an effort to increase performance of the stacks-node's http server, but that may no longer be helpful, and seems like it would contribute to this uneven distribution.

@zone117x It's difficult to say for sure. The API is only given a single DNS record to the backend followers which resolves to a single IP address. The API isn't aware that it's a virtual IP and there's additional routing happening at the network layer once traffic reaches the VIP. I would hazard a guess that the API isn't locking to a single stacks follower as a result of this configuration.

If it were happening as you said, then I think this issue would've been exposed shortly after 2.0 went live.

**Comment by zone117x** [comment]
> @zone117x It's difficult to say for sure. The API is only given a single DNS record to the backend followers which resolves to a single IP address. The API isn't aware that it's a virtual IP and there's additional routing happening at the network layer once traffic reaches the VIP. I would hazard a guess that the API isn't locking to a single stacks follower as a result of this configuration.

This wouldn't surprise me, however, my understanding is that the `keep-alive` directive will cause a stateful-enough TCP connection to a given stacks-node to bypass that network routing. Or, to put another way, I can't imagine WebSocket connections (for example) would work correctly if there was a network layer routing individual tcp packets to an instance other than the one from the initial handshake.

**Comment by CharlieC3** [comment]
ah good point, I missed that the configuration was for socketed connections. 🤔
