### ISSUE TITLE
set api version in openapi.yaml automatically

### ISSUE THREAD

**Issue by rafaelcr** [blockstack/stacks-blockchain-api#764]
The API version exposed by `openapi.yaml` is [currently hardcoded](https://github.com/blockstack/stacks-blockchain-api/blob/develop/docs/openapi.yaml#L13) to `1.0.0`. This is confusing to users [in the API docs](https://blockstack.github.io/stacks-blockchain-api/) because the real API version reported by `/extended/v1/status` looks very different (e.g. `v0.66.1`).

Now that we have the latest version string exposed through the `.git-info` file, we should modify our Github actions so they append that value into `openapi.yaml` before generating the Github pages documentation.

**Comment by rafaelcr** [comment]
> Ideally this version string would be checked in to the `openapi.yaml` file 

Hmm that could be very tricky since version numbers are taken from git tags so it happens outside of the coding flow. Can you point me to the process you currently use for building the new unified documentation site? Maybe we can figure out a way in which you could pull the generated `openapi.yaml` instead of directly from the repo.

**Comment by pgray-hiro** [comment]
I just provide a qualified URL for the spec and the builder does the rest on the fly, you can see the config [here](https://github.com/hirosystems/docs/blob/26d887abe5aec837f1c7e2c60985449818919845/docusaurus.config.js#L40). One solution could be to use a GH action to generate the spec with the correct version and check it in to the docs repo, then we could reference the file that's checked into the docs repo rather than the blockchain repo.

**Comment by rafaelcr** [comment]
Cool, yeah, I believe it is possible for Github actions to generate `openapi.yaml` as an artifact for you to link to directly. I can look into it.

**Comment by pgray-hiro** [comment]
Awesome, let me know!

**Comment by rafaelcr** [comment]
@pgray-hiro could you check if this link would work for you in your docs builder? https://raw.githubusercontent.com/blockstack/stacks-blockchain-api/gh-pages/openapi.resolved.yaml

If so, the PR for this change becomes trivial 👍

**Comment by pgray-hiro** [comment]
@rafaelcr Just built the site with that URL as the target for the spec and it works fine.
