### ISSUE TITLE
Incorrect STX balance

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#804]
See https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP1VA9HEH5VJFBCGJ6F8VF9BGS8WF6DJE9AD7856/stx
```json
{
  "balance": "-144884439",
  "total_sent": "368999000",
  "total_received": "239000000",
  "total_fees_sent": "14885439",
  "total_miner_rewards_received": "0",
  "lock_tx_id": "",
  "locked": "0",
  "lock_height": 0,
  "burnchain_lock_height": 0,
  "burnchain_unlock_height": 0
}
```
https://explorer.stacks.co/address/SP1VA9HEH5VJFBCGJ6F8VF9BGS8WF6DJE9AD7856?chain=mainnet

**Comment by rafaelcr** [comment]
After further investigation, @zone117x found that this issue is caued by a bug in the block re-org handling code related to microblocks. He's currently working on reproducing the issue in order to write a generalized fix.
