### ISSUE TITLE
Health check: check last block

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#94]
Seems like a common issue is this path -> https://sidecar.staging.blockstack.xyz/sidecar/v1/tx/ gets frozen at an arbitrary block height. It would be helpful to check the last time compared to current and if it's over a certain amount of time, alert a slack channel or something.

**Comment by zone117x** [comment]
Devops setup runscope alerts. If a new block isn't showing after 1 hour then alerts go off.
